[package]
name = "layoutng_forms"
version = "0.0.1"
edition = "2021"

[dependencies]
foundation = { path = "../foundation", package = "layoutng_foundation" }
font_engine = { path = "../font_engine" }
layoutng_assembly = { path = "../layoutng_assembly" }
layoutng_geometry = { path = "../layoutng_geometry" }
layoutng_style = { path = "../layoutng_style" }
