[package]
name = "interaction"
version = "0.0.1"
edition = "2021"

[dependencies]
paint = { path = "../paint", features = ["translation_in_progress"] }
layoutng_assembly = { path = "../layoutng_assembly" }
dom = { path = "../dom" }
foundation = { package = "layoutng_foundation", path = "../foundation" }

[dev-dependencies]
html = { path = "../html" }
