import * as os from 'os';
import * as std from 'std';
const root = std.getenv('QUICKJS_HOST_FIXTURE_DIR');
function check(value, message) { if (!value) throw Error(message); }
function out(...values) { console.log(JSON.stringify(values,(_key,value)=>typeof value==='bigint'?value+'n':value)); }
function caught(fn) { try { fn(); return 'no exception'; } catch (e) { return e.name+':'+e.message; } }
out('exports', Object.keys(os).sort(), Object.getOwnPropertyDescriptors(os).open.enumerable);
out('cwd', os.getcwd()[0].length > 0, os.getcwd()[1], os.realpath(root)[1], os.chdir(root));
let path=root+'/file', renamed=root+'/renamed', link=root+'/link', dir=root+'/dir';
let order=[];
let fd=os.open({toString(){order.push('name');return path;}}, {valueOf(){order.push('flags');return os.O_RDWR|os.O_CREAT|os.O_TRUNC;}}, {valueOf(){order.push('mode');return 0o600;}});
check(fd>=0,'open'); out('open order',order,os.isatty(fd),os.ttyGetWinSize(fd));
let buffer=new Uint8Array([97,0,98,10]);
out('write',os.write(fd,buffer.buffer,0,4),os.seek(fd,0n,std.SEEK_SET),typeof os.seek(fd,0n,std.SEEK_CUR));
let read=new Uint8Array(6);
out('read',os.read(fd,read.buffer,1,4),Array.from(read),os.seek(fd,0,std.SEEK_CUR));
out('fd errors',os.seek(fd,-1,std.SEEK_SET),caught(()=>os.read(fd,read.buffer,4,3)),caught(()=>os.write(fd,read,0,1)),caught(()=>os.read(fd,read.buffer,-1,1)),caught(()=>os.open(Symbol(),0)));
let duplicate=os.dup(fd), destination=os.dup(fd);
check(duplicate>=0&&destination>=0,'dup');
out('dup',os.dup2(duplicate,destination)===destination,os.close(duplicate),os.close(destination),os.close(fd));
out('missing',os.open(root+'/missing',os.O_RDONLY),os.stat(root+'/missing'),os.realpath(root+'/missing'),os.readlink(root+'/missing'),os.remove(root+'/missing'));
out('rename',os.rename(path,renamed),os.mkdir(dir,0o700),os.mkdir(dir,0o700));
out('directory',os.readdir(root)[0].sort(),os.readdir(root+'/missing'));
out('symlink',os.symlink('renamed',link),os.readlink(link));
let [stat,se]=os.stat(link),[lstat,le]=os.lstat(link);
out('stat',Object.keys(stat),stat.size,stat.mode&os.S_IFMT,se,lstat.mode&os.S_IFMT,le);
out('utimes',os.utimes(renamed,100123,200456));
stat=os.stat(renamed)[0];out('times',stat.atime,stat.mtime);
out('sleep',os.sleep(-10),caught(()=>os.sleep(Symbol())),caught(()=>os.sleepAsync(Symbol())));
let log=[];
let removed=os.setTimeout(()=>log.push('removed'),0);os.clearTimeout(removed);
os.setTimeout(()=>{log.push('first');os.setTimeout(()=>log.push('nested'),0);},0);
os.setTimeout(()=>log.push('second'),0);
await os.sleepAsync(0);
await os.sleepAsync(0);
out('timers',log,os.clearTimeout(0),caught(()=>os.setTimeout(1,0)));
let [r,w]=os.pipe();
os.setReadHandler(r,()=>{let b=new Uint8Array(2);log.push('read:'+os.read(r,b.buffer,0,2)+':'+b[0]+':'+b[1]);os.setReadHandler(r,null);os.close(r);os.close(w);});
os.write(w,new Uint8Array([4,5]).buffer,0,2);
await os.sleepAsync(5);out('read handler',log.at(-1));
[r,w]=os.pipe();
os.setWriteHandler(w,()=>{log.push('writable');os.setWriteHandler(w,null);os.close(r);os.close(w);});
await os.sleepAsync(5);out('write handler',log.at(-1));
out('handler errors',caught(()=>os.setReadHandler(9,1)),caught(()=>os.signal(64,null)),caught(()=>os.signal(os.SIGUSR1,1)));
os.signal(os.SIGUSR1,()=>{log.push('signal');os.signal(os.SIGUSR1,null);});
check(os.kill(os.getpid(),os.SIGUSR1)===0,'kill');
await os.sleepAsync(0);out('signal',log.at(-1));
out('exec',os.exec(['/bin/sh','-c','exit 7']),os.exec(['sh','-c','exit 9']),os.exec(['does-not-exist']),os.exec(['/bin/sh','-c','kill -TERM $$']));
out('exec opts',os.exec(['/bin/sh','-c','test "$QQ_ENV" = "hello" && test "$PWD" = "$QQ_ROOT"'],{env:{QQ_ENV:'hello',QQ_ROOT:root},cwd:root}),os.exec(['/bin/sh','-c','exit 4'],{usePath:false}),os.exec(['fake','-c','exit 0'],{file:'/bin/sh'}));
out('exec errors',caught(()=>os.exec([])),caught(()=>os.exec(['x'],{get block(){throw Error('block');}})),caught(()=>os.exec([Symbol()])),caught(()=>os.exec(['x'],{env:{get x(){throw Error('env');}}})));
let pid=os.exec(['/bin/sh','-c','exit 6'],{block:false});let wait=os.waitpid(pid,0);
out('wait',wait[0]===pid,wait[1],os.waitpid(pid,0));
[r,w]=os.pipe();pid=os.exec(['/bin/sh','-c','printf x'],{block:false,stdout:w});os.close(w);let byte=new Uint8Array(1);let count=os.read(r,byte.buffer,0,1);os.close(r);wait=os.waitpid(pid,0);out('redirect',count,byte[0],wait[0]===pid,wait[1]);
const data=await import('./libc_os_data.json',{with:{type:'json'}});
const extended=await import('./libc_os_data.json5',{with:{type:'json5'}});
const esm=await import('./libc_os_dependency.mjs');
out('loader',data.default,extended.default,esm.answer,esm.main,esm.url.endsWith('/libc_os_dependency.mjs'));
try {await import('./absent.so');} catch(e) {out('shared missing',e.name,e.message.endsWith("absent.so' as shared library"));}
out('cleanup',os.remove(link),os.remove(renamed),os.remove(dir),os.readdir(root)[0].sort());
