[package]
name = "renderer"
version = "0.0.1"
edition = "2021"

[dependencies]
browser_tracing = { path = "../tracing" }
skia = { path = "../skia" }
paint = { path = "../paint" }
layer_tile = { path = "../layer_tile" }
viz = { path = "../viz" }
raster = { path = "../raster" }
layoutng_assembly = { path = "../layoutng_assembly" }

[features]
default = []
text = ["raster/text"]
source_replay = ["raster/source_replay"]
pure_replay = ["raster/pure_replay"]
compose_work_profile = []
profiling = ["raster/profiling", "skia/profiling"]

[dev-dependencies]
compositor = { path = "../compositor" }
