#include "quickjs.c"
#include "quickjs_diagnostic_allocator.h"
static void *slots[900];static size_t sizes[900],nslots,icount;
static void iter_write(void *opaque,void*p){icount++;for(size_t i=0;i<nslots;i++){if(slots[i] && (p==slots[i]||p==js_rc(slots[i]))){unsigned sum=0;for(size_t j=0;j<sizes[i]&&j<11;j++)sum+=((unsigned char*)slots[i])[j];printf("%zu:%zu:%u\n",i,sizes[i],sum);return;}}assert(!nslots);}
static void snapshot(JSMallocContext*s,const char*name){printf("phase %s\n",name);icount=0;js_malloc_iter(s,iter_write,NULL);printf("count %zu stats %zu %zu\n",icount,s->malloc_state.malloc_count,s->malloc_state.malloc_size);}
int main(void){JSMallocContext s;js_malloc_init(&s);s.mf=DIAGNOSTIC_MALLOC;s.malloc_state.malloc_limit=SIZE_MAX;printf("layouts %zu %zu %zu %zu\n",sizeof(JSMallocArena),sizeof(JSMallocBlockHeader),sizeof(JSMallocLargeBlockHeader),sizeof(JSMallocContext));
for(int i=0;i<650;i++){size_t n=i<320?8:i<520?32:(i-519)*8;slots[i]=__js_malloc(&s,n);assert(slots[i]);sizes[i]=n;memset(slots[i],i%251,n);}slots[650]=__js_malloc(&s,0);sizes[650]=0;nslots=651;snapshot(&s,"allocated");
for(int i=0;i<650;i+=3){__js_free(&s,slots[i]);slots[i]=NULL;}snapshot(&s,"holes");for(int i=0;i<180;i++){size_t n=i%2==0?8:40;slots[nslots]=__js_malloc(&s,n);sizes[nslots]=n;memset(slots[nslots],(650+i)%251,n);nslots++;}snapshot(&s,"reuse");
int ids[]={1,4,7,523,527,620,622,625,628};for(size_t k=0;k<countof(ids);k++){int i=ids[k];if(!slots[i])continue;size_t old=sizes[i],n=i%2==0?64:1500;void*q=__js_realloc(&s,slots[i],n);assert(q);for(size_t j=0;j<(old<n?old:n);j++)assert(((unsigned char*)q)[j]==i%251);memset(q,i%251,n);slots[i]=q;sizes[i]=n;}snapshot(&s,"reallocated");
s.malloc_state.malloc_limit=s.malloc_state.malloc_size;int oomids[]={1,4,7,620,622,625,628};for(size_t k=0;k<countof(oomids);k++){int i=oomids[k];if(slots[i])assert(!__js_realloc(&s,slots[i],50000));}assert(!__js_malloc(&s,50000));snapshot(&s,"oom");s.malloc_state.malloc_limit=SIZE_MAX;for(size_t i=0;i<nslots;i++){__js_free(&s,slots[i]);slots[i]=NULL;}snapshot(&s,"freed");assert(!s.malloc_state.malloc_count);
JSRuntime*rt=JS_NewRuntime2(&DIAGNOSTIC_MALLOC,NULL);assert(rt);JSContext*ctx=JS_NewContext(rt);assert(ctx);nslots=0;snapshot(&rt->malloc_ctx,"context");const char*text="(()=>{for(let i=0;i<300;i++){let a={i};a.self=a;}})()";JSValue v=JS_Eval(ctx,text,strlen(text),"iter.js",0);assert(!JS_IsException(v));JS_FreeValue(ctx,v);snapshot(&rt->malloc_ctx,"cycles");JS_RunGC(rt);snapshot(&rt->malloc_ctx,"gc");JS_FreeContext(ctx);JS_RunGC(rt);snapshot(&rt->malloc_ctx,"contextfreed");JS_FreeRuntime(rt);return 0;}
