#include "quickjs.c"
static void scalar(JSValue v){int tag=JS_VALUE_GET_NORM_TAG(v);uint64_t bits;if(tag==JS_TAG_FLOAT64){double d=JS_VALUE_GET_FLOAT64(v);memcpy(&bits,&d,8);}else bits=(uint64_t)(uint32_t)JS_VALUE_GET_INT(v);fwrite(&tag,4,1,stdout);fwrite(&bits,8,1,stdout);}
static void result(JSContext *ctx,JSValue v,int object){if(object&&JS_IsObject(v)){JSValue x=JS_GetProperty(ctx,v,JS_ATOM_value),d=JS_GetProperty(ctx,v,JS_ATOM_done);scalar(x);scalar(d);JS_FreeValue(ctx,x);JS_FreeValue(ctx,d);}else scalar(v);}
static void promise(JSContext *ctx,JSValue p,int object){assert(!JS_IsException(p));int state=JS_PromiseState(ctx,p);fwrite(&state,4,1,stdout);JSValue r=JS_PromiseResult(ctx,p);result(ctx,r,object);JS_FreeValue(ctx,r);}
static void drain(JSRuntime *rt){JSContext *ctx;int n,count=0;while((n=JS_ExecutePendingJob(rt,&ctx))!=0){assert(n>0);assert(++count<100);}}
static JSValue function(JSContext *ctx,int kind,const uint8_t *code,int len){JSFunctionBytecode *b=js_mallocz(ctx,sizeof(*b)+len);assert(b);js_rc(b)->ref_count=1;add_gc_object(ctx->rt,&b->header,JS_GC_OBJ_TYPE_FUNCTION_BYTECODE);b->realm=JS_DupContext(ctx);b->stack_size=8;b->func_kind=kind;b->func_name=JS_DupAtom(ctx,JS_ATOM_empty_string);b->byte_code_buf=(uint8_t *)(b+1);b->byte_code_len=len;memcpy(b->byte_code_buf,code,len);JSValue f=js_closure(ctx,JS_MKPTR(JS_TAG_FUNCTION_BYTECODE,b),NULL,NULL,FALSE);assert(!JS_IsException(f));return f;}
static void push(uint8_t *code,int *len,int value){code[(*len)++]=OP_push_i32;memcpy(code+*len,&value,4);*len+=4;}
int main(void){JSRuntime *rt=JS_NewRuntime();assert(rt);JSContext *ctx=JS_NewContextRaw(rt);assert(ctx);JSCFunctionType ft;ft.generic_magic=js_function_constructor;ctx->function_ctor=JS_NewCFunction2(ctx,ft.generic,"Function",1,JS_CFUNC_constructor_or_func_magic,JS_FUNC_NORMAL);assert(!JS_IsException(ctx->function_ctor));assert(JS_AddIntrinsicPromise(ctx)==0);JSValue arg=JS_NewInt32(ctx,37);
 for(int i=0;i<64;i++){
  uint8_t code[64];int len=0;code[len++]=OP_initial_yield;push(code,&len,i-17);code[len++]=OP_yield;code[len++]=OP_drop;code[len++]=OP_drop;push(code,&len,i+29);code[len++]=OP_return_async;
  JSValue f=function(ctx,JS_FUNC_GENERATOR,code,len);
  for(int start=GEN_MAGIC_NEXT;start<=GEN_MAGIC_THROW;start++){JSValue g=JS_Call(ctx,f,JS_UNDEFINED,0,NULL);assert(!JS_IsException(g));for(int k=0;k<3;k++){int done;JSValue v=js_generator_next(ctx,g,1,&arg,&done,k==0?start:GEN_MAGIC_NEXT);fwrite(&done,4,1,stdout);scalar(v);if(JS_IsException(v)){JSValue e=JS_GetException(ctx);scalar(e);JS_FreeValue(ctx,e);}JS_FreeValue(ctx,v);}JS_FreeValue(ctx,g);}JS_FreeValue(ctx,f);
  for(int await_value=0;await_value<2;await_value++){len=0;push(code,&len,i-17);if(await_value)code[len++]=OP_await;code[len++]=OP_return_async;f=function(ctx,JS_FUNC_ASYNC,code,len);JSValue p=JS_Call(ctx,f,JS_UNDEFINED,0,NULL);promise(ctx,p,FALSE);drain(rt);promise(ctx,p,FALSE);JS_FreeValue(ctx,p);JS_FreeValue(ctx,f);}
  for(int await_value=0;await_value<2;await_value++){len=0;code[len++]=OP_initial_yield;push(code,&len,i-17);if(await_value){code[len++]=OP_await;code[len++]=OP_drop;push(code,&len,i+19);}code[len++]=OP_yield;code[len++]=OP_drop;code[len++]=OP_drop;push(code,&len,i+29);code[len++]=OP_return_async;f=function(ctx,JS_FUNC_ASYNC_GENERATOR,code,len);JSValue g=JS_Call(ctx,f,JS_UNDEFINED,0,NULL);assert(!JS_IsException(g));for(int k=0;k<3;k++){JSValue p=js_async_generator_next(ctx,g,1,&arg,GEN_MAGIC_NEXT);promise(ctx,p,TRUE);drain(rt);promise(ctx,p,TRUE);JS_FreeValue(ctx,p);}JS_FreeValue(ctx,g);JS_FreeValue(ctx,f);}
 }
 assert(rt->current_stack_frame==NULL);JS_FreeContext(ctx);JS_FreeRuntime(rt);return 0;}
