{
 num(&mut out,size_of::<JSClosureVar>() as u64,4);num(&mut out,core::mem::align_of::<JSClosureVar>() as u64,4);
 num(&mut out,size_of::<JSBytecodeVarDef>() as u64,4);num(&mut out,core::mem::align_of::<JSBytecodeVarDef>() as u64,4);
 num(&mut out,size_of::<JSFunctionBytecode>() as u64,4);num(&mut out,core::mem::align_of::<JSFunctionBytecode>() as u64,4);
 num(&mut out,size_of::<JSBoundFunction>() as u64,4);num(&mut out,core::mem::align_of::<JSBoundFunction>() as u64,4);
 num(&mut out,size_of::<JSForInIterator>() as u64,4);num(&mut out,core::mem::align_of::<JSForInIterator>() as u64,4);
 num(&mut out,size_of::<JSRegExp>() as u64,4);num(&mut out,core::mem::align_of::<JSRegExp>() as u64,4);
 num(&mut out,size_of::<JSProxyData>() as u64,4);num(&mut out,core::mem::align_of::<JSProxyData>() as u64,4);
 num(&mut out,size_of::<JSArrayBuffer>() as u64,4);num(&mut out,core::mem::align_of::<JSArrayBuffer>() as u64,4);
 num(&mut out,size_of::<JSTypedArray>() as u64,4);num(&mut out,core::mem::align_of::<JSTypedArray>() as u64,4);
 num(&mut out,size_of::<JSGlobalObject>() as u64,4);num(&mut out,core::mem::align_of::<JSGlobalObject>() as u64,4);
 num(&mut out,size_of::<JSAsyncFunctionState>() as u64,4);num(&mut out,core::mem::align_of::<JSAsyncFunctionState>() as u64,4);
 num(&mut out,size_of::<JSBinaryOperatorDefEntry>() as u64,4);num(&mut out,core::mem::align_of::<JSBinaryOperatorDefEntry>() as u64,4);
 num(&mut out,size_of::<JSBinaryOperatorDef>() as u64,4);num(&mut out,core::mem::align_of::<JSBinaryOperatorDef>() as u64,4);
 num(&mut out,size_of::<JSOperatorSetData>() as u64,4);num(&mut out,core::mem::align_of::<JSOperatorSetData>() as u64,4);
 num(&mut out,size_of::<JSReqModuleEntry>() as u64,4);num(&mut out,core::mem::align_of::<JSReqModuleEntry>() as u64,4);
 num(&mut out,size_of::<JSExportEntry>() as u64,4);num(&mut out,core::mem::align_of::<JSExportEntry>() as u64,4);
 num(&mut out,size_of::<JSStarExportEntry>() as u64,4);num(&mut out,core::mem::align_of::<JSStarExportEntry>() as u64,4);
 num(&mut out,size_of::<JSImportEntry>() as u64,4);num(&mut out,core::mem::align_of::<JSImportEntry>() as u64,4);
 num(&mut out,size_of::<JSModuleDef>() as u64,4);num(&mut out,core::mem::align_of::<JSModuleDef>() as u64,4);
 num(&mut out,size_of::<JSJobEntry>() as u64,4);num(&mut out,core::mem::align_of::<JSJobEntry>() as u64,4);
 num(&mut out,size_of::<JSObject>() as u64,4);num(&mut out,core::mem::align_of::<JSObject>() as u64,4);
 num(&mut out,size_of::<JSMapRecord>() as u64,4);num(&mut out,core::mem::align_of::<JSMapRecord>() as u64,4);
 num(&mut out,size_of::<JSMapState>() as u64,4);num(&mut out,core::mem::align_of::<JSMapState>() as u64,4);
 num(&mut out,offset_of!(JSClosureVar,var_idx) as u64,4);
 num(&mut out,offset_of!(JSClosureVar,var_name) as u64,4);
 num(&mut out,offset_of!(JSBytecodeVarDef,scope_next) as u64,4);
 num(&mut out,offset_of!(JSBytecodeVarDef,var_ref_idx) as u64,4);
 num(&mut out,offset_of!(JSFunctionBytecode,js_mode) as u64,4);
 num(&mut out,offset_of!(JSFunctionBytecode,byte_code_buf) as u64,4);
 num(&mut out,offset_of!(JSFunctionBytecode,byte_code_len) as u64,4);
 num(&mut out,offset_of!(JSFunctionBytecode,vardefs) as u64,4);
 num(&mut out,offset_of!(JSFunctionBytecode,closure_var) as u64,4);
 num(&mut out,offset_of!(JSFunctionBytecode,var_ref_count) as u64,4);
 num(&mut out,offset_of!(JSFunctionBytecode,realm) as u64,4);
 num(&mut out,offset_of!(JSFunctionBytecode,cpool) as u64,4);
 num(&mut out,offset_of!(JSFunctionBytecode,closure_var_count) as u64,4);
 num(&mut out,offset_of!(JSFunctionBytecode,debug) as u64,4);
 num(&mut out,offset_of!(JSFunctionBytecode,debug.pc2line_buf) as u64,4);
 num(&mut out,offset_of!(JSFunctionBytecode,debug.source) as u64,4);
 num(&mut out,offset_of!(JSBoundFunction,argc) as u64,4);
 num(&mut out,offset_of!(JSBoundFunction,argv) as u64,4);
 num(&mut out,offset_of!(JSForInIterator,is_array) as u64,4);
 num(&mut out,offset_of!(JSForInIterator,tab_atom) as u64,4);
 num(&mut out,offset_of!(JSArrayBuffer,data) as u64,4);
 num(&mut out,offset_of!(JSArrayBuffer,array_list) as u64,4);
 num(&mut out,offset_of!(JSArrayBuffer,free_func) as u64,4);
 num(&mut out,offset_of!(JSTypedArray,offset) as u64,4);
 num(&mut out,offset_of!(JSTypedArray,track_rab) as u64,4);
 num(&mut out,offset_of!(JSAsyncFunctionState,resolving_funcs) as u64,4);
 num(&mut out,offset_of!(JSAsyncFunctionState,frame) as u64,4);
 num(&mut out,offset_of!(JSExportEntry,export_type) as u64,4);
 num(&mut out,offset_of!(JSExportEntry,export_name) as u64,4);
 num(&mut out,offset_of!(JSModuleDef,link) as u64,4);
 num(&mut out,offset_of!(JSModuleDef,req_module_entries) as u64,4);
 num(&mut out,offset_of!(JSModuleDef,module_ns) as u64,4);
 num(&mut out,offset_of!(JSModuleDef,init_func) as u64,4);
 num(&mut out,offset_of!(JSModuleDef,dfs_index) as u64,4);
 num(&mut out,offset_of!(JSModuleDef,stack_prev) as u64,4);
 num(&mut out,offset_of!(JSModuleDef,async_parent_modules) as u64,4);
 num(&mut out,offset_of!(JSModuleDef,async_evaluation_timestamp) as u64,4);
 num(&mut out,offset_of!(JSModuleDef,promise) as u64,4);
 num(&mut out,offset_of!(JSModuleDef,eval_exception) as u64,4);
 num(&mut out,offset_of!(JSModuleDef,meta_obj) as u64,4);
 num(&mut out,offset_of!(JSModuleDef,private_value) as u64,4);
 num(&mut out,offset_of!(JSJobEntry,realm) as u64,4);
 num(&mut out,offset_of!(JSJobEntry,argc) as u64,4);
 num(&mut out,offset_of!(JSJobEntry,argv) as u64,4);
 num(&mut out,offset_of!(JSObject,class_id) as u64,4);
 num(&mut out,offset_of!(JSObject,weakref_count) as u64,4);
 num(&mut out,offset_of!(JSObject,shape) as u64,4);
 num(&mut out,offset_of!(JSObject,prop) as u64,4);
 num(&mut out,offset_of!(JSObject,u) as u64,4);
 num(&mut out,offset_of!(JSObject,u.func) as u64,4);
 num(&mut out,offset_of!(JSObject,u.cfunc.magic) as u64,4);
 num(&mut out,offset_of!(JSObject,u.array.count) as u64,4);
 num(&mut out,offset_of!(JSObject,u.regexp) as u64,4);
 num(&mut out,offset_of!(JSMapRecord,link) as u64,4);
 num(&mut out,offset_of!(JSMapRecord,hash_next) as u64,4);
 num(&mut out,offset_of!(JSMapRecord,key) as u64,4);
 num(&mut out,offset_of!(JSMapRecord,value) as u64,4);
 num(&mut out,offset_of!(JSMapState,records) as u64,4);
 num(&mut out,offset_of!(JSMapState,record_count) as u64,4);
 num(&mut out,offset_of!(JSMapState,hash_table) as u64,4);
 num(&mut out,offset_of!(JSMapState,weakref_header) as u64,4);
}
