static void dump_names(JSContext*ctx,JSValue obj,int flags){JSPropertyEnum*tab=NULL;uint32_t count=0;int ret=JS_GetOwnPropertyNames(ctx,&tab,&count,obj,flags);num(ret,4);num(count,4);dump_exception(ctx);if(!ret){for(uint32_t i=0;i<count;i++){JSAtom key=tab[i].atom;num(JS_AtomGetKind(ctx,key),4);JSValue val=JS_AtomToString(ctx,key);dump_val(val);JS_FreeValue(ctx,val);num(tab[i].is_enumerable,4);}JS_FreePropertyEnum(ctx,tab,count);}}
static void names_private_global_fixtures(JSContext*ctx,struct host*h){
 JSValue name=JS_NewSymbolFromAtom(ctx,JS_ATOM_name,JS_ATOM_TYPE_PRIVATE),obj=JS_NewObject(ctx),other=JS_NewObject(ctx);JS_PreventExtensions(ctx,obj);JSValue targets[]={obj,other,JS_TRUE,JS_NULL};
 for(int i=0;i<4;i++){JSValue target=targets[i];num(JS_DefinePrivateField(ctx,target,name,JS_NewInt32(ctx,91)),4);dump_exception(ctx);num(JS_DefinePrivateField(ctx,target,name,JS_NewInt32(ctx,92)),4);dump_exception(ctx);JSValue val=JS_GetPrivateField(ctx,target,name);dump_val(val);JS_FreeValue(ctx,val);dump_exception(ctx);num(JS_SetPrivateField(ctx,target,name,JS_NewInt32(ctx,93)),4);dump_exception(ctx);}
 num(JS_DefinePrivateField(ctx,obj,JS_TRUE,JS_NewInt32(ctx,1)),4);dump_exception(ctx);JSValue home=JS_NewObject(ctx),func=JS_NewObjectClass(ctx,JS_CLASS_BYTECODE_FUNCTION);JS_VALUE_GET_OBJ(func)->u.func.home_object=JS_VALUE_GET_OBJ(home);JSValue branded[]={JS_NULL,obj,obj,other,JS_TRUE};for(int i=0;i<5;i++){num(JS_AddBrand(ctx,branded[i],home),4);dump_exception(ctx);num(JS_CheckBrand(ctx,branded[i],func),4);dump_exception(ctx);}JS_VALUE_GET_OBJ(func)->u.func.home_object=NULL;JS_FreeValue(ctx,func);JS_FreeValue(ctx,home);JS_FreeValue(ctx,other);JS_FreeValue(ctx,obj);JS_FreeValue(ctx,name);
 obj=JS_NewObject(ctx);const char*keys[]={"z","10","2","01","4294967294","4294967295","a","0"};for(int i=0;i<8;i++)JS_DefinePropertyValueStr(ctx,obj,keys[i],JS_NewInt32(ctx,i),JS_PROP_CONFIGURABLE|JS_PROP_WRITABLE|((i%2)?JS_PROP_ENUMERABLE:0));int kinds[]={JS_ATOM_TYPE_SYMBOL,JS_ATOM_TYPE_PRIVATE};for(int i=0;i<2;i++){JSValue key=JS_NewSymbolFromAtom(ctx,JS_ATOM_name,kinds[i]);JS_DefinePropertyValue(ctx,obj,js_symbol_to_atom(ctx,key),JS_NewInt32(ctx,8),JS_PROP_C_W_E);JS_FreeValue(ctx,key);}for(int flags=0;flags<64;flags++)dump_names(ctx,obj,flags);for(int fail=1;fail<8;fail++){h->fail=h->calls+fail;dump_names(ctx,obj,JS_GPN_STRING_MASK|JS_GPN_SYMBOL_MASK|JS_GPN_SET_ENUM);h->fail=0;}
 JSValue arr=JS_NewArray(ctx);for(int i=0;i<4;i++)JS_SetPropertyUint32(ctx,arr,i,JS_NewInt32(ctx,i));for(int flags=0;flags<64;flags++)dump_names(ctx,arr,flags);JS_FreeValue(ctx,arr);JS_FreeValue(ctx,obj);
 JSValue boxed=JS_ToObjectFree(ctx,JS_NewString(ctx,"\xc4\x80" "ab"));JS_VALUE_GET_OBJ(boxed)->is_exotic=1;for(int flags=0;flags<64;flags++)dump_names(ctx,boxed,flags);JS_FreeValue(ctx,boxed);
 ctx->global_obj=JS_NewObjectClass(ctx,JS_CLASS_GLOBAL_OBJECT);JS_VALUE_GET_OBJ(ctx->global_obj)->u.global_object.uninitialized_vars=JS_NewObject(ctx);ctx->global_var_obj=JS_NewObject(ctx);JSAtom atom=JS_ATOM_name;JS_DefinePropertyValue(ctx,ctx->global_obj,atom,JS_NewInt32(ctx,17),JS_PROP_WRITABLE|JS_PROP_ENUMERABLE);int modes[]={0,DEFINE_GLOBAL_LEX_VAR,DEFINE_GLOBAL_FUNC_VAR};for(int i=0;i<3;i++){num(JS_CheckDefineGlobalVar(ctx,atom,modes[i]),4);dump_exception(ctx);}JSValue sp[2]={JS_UNDEFINED,JS_UNDEFINED};num(JS_GetGlobalVarRef(ctx,atom,sp),4);for(int i=0;i<2;i++){dump_val(sp[i]);JS_FreeValue(ctx,sp[i]);}dump_exception(ctx);num(JS_DeleteGlobalVar(ctx,atom),4);dump_exception(ctx);
 JSProperty*pr=add_property(ctx,JS_VALUE_GET_OBJ(ctx->global_var_obj),atom,JS_PROP_C_W_E|JS_PROP_VARREF);JSVarRef*vr=js_create_var_ref(ctx,0);pr->u.var_ref=vr;vr->value=JS_UNINITIALIZED;for(int i=0;i<3;i++){num(JS_CheckDefineGlobalVar(ctx,atom,modes[i]),4);dump_exception(ctx);}sp[0]=sp[1]=JS_UNDEFINED;num(JS_GetGlobalVarRef(ctx,atom,sp),4);dump_exception(ctx);dump_names(ctx,ctx->global_var_obj,JS_GPN_STRING_MASK|JS_GPN_SET_ENUM);vr->value=JS_NewInt32(ctx,88);sp[0]=sp[1]=JS_UNDEFINED;num(JS_GetGlobalVarRef(ctx,atom,sp),4);for(int i=0;i<2;i++){dump_val(sp[i]);JS_FreeValue(ctx,sp[i]);}dump_exception(ctx);num(JS_DeleteGlobalVar(ctx,atom),4);dump_exception(ctx);JS_FreeValue(ctx,ctx->global_var_obj);JS_FreeValue(ctx,ctx->global_obj);ctx->global_var_obj=JS_UNDEFINED;ctx->global_obj=JS_UNDEFINED;
}
