static int free_calls,sab_calls;static void array_free(JSRuntime*rt,void*opaque,void*data){free_calls++;num((uintptr_t)opaque,4);js_free_rt(rt,data);}static void sab_free(void*opaque,void*data){sab_calls++;num(0xf00d,4);js_free_rt(opaque,data);}
static void record_mark(JSRuntime*rt,JSGCObjectHeader*p){num(js_rc(p)->gc_obj_type,4);}
static JSValue owned_string(JSRuntime*rt,int n){uint16_t units[5]={1,2,3,4,5};return JS_MKPTR(JS_TAG_STRING,make_string(rt,units,n%6,n%2));}
static JSValue async_owned(JSRuntime*rt,JSObject*held,int n){return n%3?owned_string(rt,n):JS_DupValueRT(rt,JS_MKPTR(JS_TAG_OBJECT,held));}
int main(void){
 JSRuntime rt={0};struct host h={0};h.trace=1469598103934665603ULL;js_malloc_init(&rt.malloc_ctx);rt.malloc_ctx.mf=(JSMallocFunctions){host_malloc,host_free,host_realloc,NULL};rt.malloc_ctx.malloc_state.opaque=&h;JS_InitAtoms(&rt);JSContext ctx={0};ctx.rt=&rt;init_list_head(&rt.gc_obj_list);rt.sab_funcs.sab_opaque=&rt;
 num(sizeof(JSGeneratorData),4);num(sizeof(JSArrayIteratorData),4);num(sizeof(JSRegExpStringIteratorData),4);num(sizeof(JSMapIteratorData),4);
 num(sizeof(JSPromiseData),4);num(sizeof(JSPromiseFunctionDataResolved),4);num(sizeof(JSPromiseFunctionData),4);num(sizeof(JSPromiseReactionData),4);num(sizeof(JSAsyncGeneratorRequest),4);num(sizeof(JSAsyncGeneratorData),4);num(sizeof(JSAsyncFromSyncIteratorData),4);
 for(int t=0;t<4096;t++){
  JSObject holder={0};JSValue val=JS_MKPTR(JS_TAG_OBJECT,&holder);num(t,4);
  JSVarRef*refs[4];for(int j=0;j<4;j++){refs[j]=js_mallocz_rt(&rt,sizeof(JSVarRef));js_rc(refs[j])->ref_count=1;add_gc_object(&rt,&refs[j]->header,JS_GC_OBJ_TYPE_VAR_REF);refs[j]->is_detached=TRUE;refs[j]->value=owned_string(&rt,t+j);refs[j]->pvalue=&refs[j]->value;}
  holder.u.array.u.var_refs=js_malloc_rt(&rt,4*sizeof(JSVarRef*));memcpy(holder.u.array.u.var_refs,refs,4*sizeof(JSVarRef*));holder.u.array.count=4;js_mapped_arguments_mark(&rt,val,record_mark);js_mapped_arguments_finalizer(&rt,val);num(list_empty(&rt.gc_obj_list),4);
  JSAsyncFunctionState*af=js_mallocz_rt(&rt,sizeof(*af));js_rc(af)->ref_count=2;js_rc(af)->gc_obj_type=JS_GC_OBJ_TYPE_ASYNC_FUNCTION;JSGeneratorData*g=js_mallocz_rt(&rt,sizeof(*g));g->state=t%5;g->func_state=t%2?af:NULL;holder.class_id=JS_CLASS_GENERATOR;holder.u.generator_data=g;js_generator_mark(&rt,val,record_mark);free_generator_stack_rt(&rt,g);num(g->state,4);num(g->func_state==NULL,4);num(js_rc(af)->ref_count,4);js_generator_finalizer(&rt,val);js_free_rt(&rt,af);
  JSArrayIteratorData*ai=js_mallocz_rt(&rt,sizeof(*ai));ai->obj=owned_string(&rt,t);holder.u.array_iterator_data=ai;js_array_iterator_mark(&rt,val,record_mark);js_array_iterator_finalizer(&rt,val);
  holder.u.regexp.pattern=t%2?NULL:JS_VALUE_GET_STRING(owned_string(&rt,t));holder.u.regexp.bytecode=t%3?NULL:JS_VALUE_GET_STRING(owned_string(&rt,t+1));js_regexp_finalizer(&rt,val);
  JSRegExpStringIteratorData*ri=js_mallocz_rt(&rt,sizeof(*ri));ri->iterating_regexp=owned_string(&rt,t);ri->iterated_string=owned_string(&rt,t+1);holder.u.regexp_string_iterator_data=ri;js_regexp_string_iterator_mark(&rt,val,record_mark);js_regexp_string_iterator_finalizer(&rt,val);
  JSProxyData*proxy=js_mallocz_rt(&rt,sizeof(*proxy));proxy->target=owned_string(&rt,t);proxy->handler=owned_string(&rt,t+1);holder.class_id=JS_CLASS_PROXY;holder.u.proxy_data=proxy;js_proxy_mark(&rt,val,record_mark);js_proxy_finalizer(&rt,val);
  JSObject*buffer=js_mallocz_rt(&rt,sizeof(*buffer));js_rc(buffer)->ref_count=100;buffer->free_mark=t%2;JSMapRecord*mr=js_mallocz_rt(&rt,sizeof(*mr));mr->ref_count=1;mr->empty=TRUE;struct list_head records;init_list_head(&records);list_add_tail(&mr->link,&records);JSMapIteratorData*mi=js_mallocz_rt(&rt,sizeof(*mi));mi->obj=JS_MKPTR(JS_TAG_OBJECT,buffer);mi->cur_record=t%3?mr:NULL;holder.u.map_iterator_data=mi;js_map_iterator_mark(&rt,val,record_mark);js_map_iterator_finalizer(&rt,val);num(js_rc(buffer)->ref_count,4);num(list_empty(&records),4);if(!list_empty(&records))js_free_rt(&rt,mr);js_free_rt(&rt,buffer);
  // The buffer can be finalized before views, and shared callbacks take precedence.
  buffer=js_mallocz_rt(&rt,sizeof(*buffer));js_rc(buffer)->ref_count=100;JSArrayBuffer*ab=js_mallocz_rt(&rt,sizeof(*ab));ab->shared=t%2;ab->data=js_malloc_rt(&rt,17);ab->opaque=(void*)(uintptr_t)(t+1);ab->free_func=t%3?array_free:NULL;init_list_head(&ab->array_list);rt.sab_funcs.sab_free=t%4?sab_free:NULL;buffer->u.array_buffer=ab;
  JSObject views[4]={0};JSTypedArray*tas[4];for(int j=0;j<4;j++){tas[j]=js_mallocz_rt(&rt,sizeof(*tas[j]));tas[j]->obj=&views[j];tas[j]->buffer=buffer;tas[j]->offset=123;tas[j]->length=456;views[j].class_id=j%2?JS_CLASS_DATAVIEW:JS_CLASS_UINT8_ARRAY;views[j].u.array.u.ptr=(void*)16;views[j].u.array.count=789;views[j].u.typed_array=tas[j];list_add_tail(&tas[j]->link,&ab->array_list);js_typed_array_mark(&rt,JS_MKPTR(JS_TAG_OBJECT,&views[j]),record_mark);}
  if(t%2){js_typed_array_finalizer(&rt,JS_MKPTR(JS_TAG_OBJECT,&views[3]));tas[3]=NULL;}
  void*data=ab->data;int callback_will_free=(ab->shared&&rt.sab_funcs.sab_free)||ab->free_func;js_array_buffer_finalizer(&rt,JS_MKPTR(JS_TAG_OBJECT,buffer));if(!callback_will_free)js_free_rt(&rt,data);
  for(int j=0;j<4;j++)if(tas[j]){num(tas[j]->link.next==NULL,4);num(tas[j]->link.prev==NULL,4);num(tas[j]->offset,4);num(tas[j]->length,4);if(j%2==0){num(views[j].u.array.count,4);num(views[j].u.array.u.ptr==NULL,4);}js_typed_array_finalizer(&rt,JS_MKPTR(JS_TAG_OBJECT,&views[j]));}
  num(js_rc(buffer)->ref_count,4);js_free_rt(&rt,buffer);num(free_calls,4);num(sab_calls,4);
  JSObject*held=js_mallocz_rt(&rt,sizeof(*held));js_rc(held)->ref_count=100;
  JSPromiseData*ps=js_mallocz_rt(&rt,sizeof(*ps));ps->promise_state=t%3;ps->promise_result=async_owned(&rt,held,t);for(int i=0;i<2;i++){init_list_head(&ps->promise_reactions[i]);for(int j=0;j<t%5;j++){JSPromiseReactionData*rd=js_mallocz_rt(&rt,sizeof(*rd));rd->resolving_funcs[0]=async_owned(&rt,held,t+j);rd->resolving_funcs[1]=async_owned(&rt,held,t+j+1);rd->handler=async_owned(&rt,held,t+j+2);list_add_tail(&rd->link,&ps->promise_reactions[i]);}}
  holder.class_id=JS_CLASS_PROMISE;holder.u.promise_data=ps;num(JS_PromiseState(&ctx,val),4);JSValue result=JS_PromiseResult(&ctx,val);num(JS_VALUE_GET_TAG(result),4);JS_FreeValue(&ctx,result);js_promise_mark(&rt,val,record_mark);js_promise_finalizer(&rt,val);
  JSPromiseFunctionDataResolved*sr=js_mallocz_rt(&rt,sizeof(*sr));sr->ref_count=2;for(int j=0;j<2;j++){JSPromiseFunctionData*pf=js_mallocz_rt(&rt,sizeof(*pf));pf->presolved=sr;pf->promise=async_owned(&rt,held,t+j);holder.u.promise_function_data=pf;js_promise_resolve_function_mark(&rt,val,record_mark);js_promise_resolve_function_finalizer(&rt,val);}
  af=js_mallocz_rt(&rt,sizeof(*af));js_rc(af)->ref_count=100;js_rc(af)->gc_obj_type=JS_GC_OBJ_TYPE_ASYNC_FUNCTION;
  JSAsyncGeneratorData*ag=js_mallocz_rt(&rt,sizeof(*ag));ag->func_state=t%2?af:NULL;init_list_head(&ag->queue);for(int j=0;j<t%5;j++){JSAsyncGeneratorRequest*req=js_mallocz_rt(&rt,sizeof(*req));req->result=async_owned(&rt,held,t+j);req->promise=async_owned(&rt,held,t+j+1);req->resolving_funcs[0]=async_owned(&rt,held,t+j+2);req->resolving_funcs[1]=async_owned(&rt,held,t+j+3);list_add_tail(&req->link,&ag->queue);}holder.class_id=JS_CLASS_ASYNC_GENERATOR;holder.u.async_generator_data=ag;js_async_generator_mark(&rt,val,record_mark);js_async_generator_finalizer(&rt,val);
  holder.u.async_function_data=t%3?af:NULL;js_async_function_resolve_mark(&rt,val,record_mark);js_async_function_resolve_finalizer(&rt,val);num(js_rc(af)->ref_count,4);js_free_rt(&rt,af);
  JSAsyncFromSyncIteratorData*asi=js_mallocz_rt(&rt,sizeof(*asi));asi->sync_iter=async_owned(&rt,held,t);asi->next_method=async_owned(&rt,held,t+1);holder.class_id=JS_CLASS_ASYNC_FROM_SYNC_ITERATOR;holder.u.async_from_sync_iterator_data=asi;js_async_from_sync_iterator_mark(&rt,val,record_mark);js_async_from_sync_iterator_finalizer(&rt,val);
  holder.class_id=0;num(JS_PromiseState(&ctx,val),4);num(JS_IsUndefined(JS_PromiseResult(&ctx,val)),4);JS_SetHostPromiseRejectionTracker(&rt,NULL,(void*)(uintptr_t)t);num(rt.host_promise_rejection_tracker==NULL,4);num((uintptr_t)rt.host_promise_rejection_tracker_opaque,4);num(js_rc(held)->ref_count,4);js_free_rt(&rt,held);
snapshot(&rt,&h);
 }
 cleanup(&rt,&h);return 0;
}
