static JSGCObjectHeader*pool[32];
static void record_mark(JSRuntime*rt,JSGCObjectHeader*p){int id=0;for(int i=0;i<32;i++)if(pool[i]==p)id=i+1;num(id,4);}
static JSValue mark_value(int index){switch(index%8){case 0:return JS_MKPTR(JS_TAG_OBJECT,pool[index%4]);case 1:return JS_MKPTR(JS_TAG_FUNCTION_BYTECODE,pool[4]);case 2:return JS_MKPTR(JS_TAG_MODULE,pool[8]);case 3:return JS_MKPTR(JS_TAG_STRING,(void*)16);case 4:return JS_UNDEFINED;case 5:return JS_MKVAL(JS_TAG_SHORT_BIG_INT,123);case 6:return JS_MKVAL(JS_TAG_INT,456);default:return JS_NULL;}}
int main(void){
 JSRuntime rt={0};struct host h={0};h.trace=1469598103934665603ULL;js_malloc_init(&rt.malloc_ctx);rt.malloc_ctx.mf=(JSMallocFunctions){host_malloc,host_free,host_realloc,NULL};rt.malloc_ctx.malloc_state.opaque=&h;init_list_head(&rt.gc_obj_list);init_list_head(&rt.context_list);
 for(int i=0;i<4;i++){pool[i]=js_mallocz_rt(&rt,sizeof(JSObject));js_rc(pool[i])->gc_obj_type=JS_GC_OBJ_TYPE_JS_OBJECT;}
 pool[4]=js_mallocz_rt(&rt,sizeof(JSFunctionBytecode));pool[5]=js_mallocz_rt(&rt,sizeof(JSVarRef));pool[6]=js_mallocz_rt(&rt,sizeof(JSAsyncFunctionState));pool[7]=js_mallocz_rt(&rt,sizeof(JSContext));pool[8]=js_mallocz_rt(&rt,sizeof(JSModuleDef));pool[9]=js_mallocz_rt(&rt,get_shape_size(4,4));
 js_rc(pool[4])->gc_obj_type=JS_GC_OBJ_TYPE_FUNCTION_BYTECODE;js_rc(pool[5])->gc_obj_type=JS_GC_OBJ_TYPE_VAR_REF;js_rc(pool[6])->gc_obj_type=JS_GC_OBJ_TYPE_ASYNC_FUNCTION;js_rc(pool[7])->gc_obj_type=JS_GC_OBJ_TYPE_JS_CONTEXT;js_rc(pool[8])->gc_obj_type=JS_GC_OBJ_TYPE_MODULE;js_rc(pool[9])->gc_obj_type=JS_GC_OBJ_TYPE_SHAPE;
 JSObject*p=(JSObject*)pool[0];JSFunctionBytecode*b=(JSFunctionBytecode*)pool[4];JSVarRef*vr=(JSVarRef*)pool[5];JSAsyncFunctionState*af=(JSAsyncFunctionState*)pool[6];JSContext*ctx=(JSContext*)pool[7];JSModuleDef*m=(JSModuleDef*)pool[8];JSShape*sh=(JSShape*)pool[9];JSClass classes[JS_CLASS_INIT_COUNT]={0};rt.class_array=classes;rt.class_count=JS_CLASS_INIT_COUNT;
 ctx->rt=&rt;init_list_head(&ctx->loaded_modules);ctx->class_proto=js_mallocz_rt(&rt,rt.class_count*sizeof(JSValue));p->shape=sh;sh->prop_hash_mask=3;sh->prop_size=4;sh->prop_count=4;p->class_id=JS_CLASS_OBJECT;JSProperty props[4]={0};p->prop=props;JSShapeProperty*prs=get_shape_prop(sh);for(int j=0;j<4;j++)prs[j].atom=j+1;
 JSValue values[16];JSVarRef*refs[4]={vr,NULL,vr,NULL};JSReqModuleEntry req[4]={0};JSExportEntry exports[4]={0};b->cpool=values;b->closure_var_count=4;b->realm=ctx;vr->pvalue=&vr->value;af->frame.arg_buf=values;af->frame.cur_sp=values+16;
 m->req_module_entries=req;m->req_module_entries_count=4;m->export_entries=exports;m->export_entries_count=4;
 for(int t=0;t<4096;t++){
  num(t,4);for(int j=0;j<16;j++)values[j]=mark_value(t+j);b->cpool_count=t%16;sh->proto=t%2?(JSObject*)pool[1]:NULL;
  props[0].u.value=mark_value(t);prs[1].flags=JS_PROP_GETSET;props[1].u.getset.getter=t%2?(JSObject*)pool[2]:NULL;props[1].u.getset.setter=t%3?(JSObject*)pool[3]:NULL;prs[2].flags=JS_PROP_VARREF;props[2].u.var_ref=vr;prs[3].flags=JS_PROP_AUTOINIT;props[3].u.init.realm_and_id=(uintptr_t)ctx|t%4;
  vr->is_detached=t%2;if(vr->is_detached){vr->value=mark_value(t+1);vr->pvalue=&vr->value;}else{vr->stack_frame=&af->frame;vr->pvalue=&values[0];}af->is_completed=(t%3)==0;af->frame.js_mode=t%4?JS_MODE_ASYNC:0;af->frame.cur_func=mark_value(t+2);af->frame.cur_sp=t%5?values+16:NULL;af->this_val=mark_value(t+3);af->resolving_funcs[0]=mark_value(t+4);af->resolving_funcs[1]=mark_value(t+5);
  ctx->global_obj=mark_value(t);ctx->global_var_obj=mark_value(t+1);ctx->throw_type_error=mark_value(t+2);ctx->eval_obj=mark_value(t+3);ctx->array_proto_values=mark_value(t+4);for(int j=0;j<JS_NATIVE_ERROR_COUNT;j++)ctx->native_error_proto[j]=mark_value(t+j);for(int j=0;j<rt.class_count;j++)ctx->class_proto[j]=mark_value(t+j);
  ctx->iterator_ctor=mark_value(t+5);ctx->async_iterator_proto=mark_value(t+6);ctx->promise_ctor=mark_value(t+7);ctx->array_ctor=mark_value(t+8);ctx->regexp_ctor=mark_value(t+9);ctx->function_ctor=mark_value(t+10);ctx->function_proto=mark_value(t+11);ctx->array_shape=sh;ctx->arguments_shape=t%2?sh:NULL;ctx->mapped_arguments_shape=t%3?sh:NULL;ctx->regexp_shape=t%4?sh:NULL;ctx->regexp_result_shape=t%5?sh:NULL;
  for(int j=0;j<4;j++){req[j].attributes=mark_value(t+j);exports[j].export_type=j%2?JS_EXPORT_TYPE_INDIRECT:JS_EXPORT_TYPE_LOCAL;exports[j].u.local.var_ref=j%3?vr:NULL;}m->module_ns=mark_value(t);m->func_obj=mark_value(t+1);m->eval_exception=mark_value(t+2);m->meta_obj=mark_value(t+3);m->promise=mark_value(t+4);m->resolving_funcs[0]=mark_value(t+5);m->resolving_funcs[1]=mark_value(t+6);m->private_value=mark_value(t+7);
  list_add_tail(&m->link,&ctx->loaded_modules);for(int j=0;j<10;j++)if(j==0||j>=4){num(100+j,4);mark_children(&rt,pool[j],record_mark);}list_del(&m->link);
  num(200,4);p->u.array.u.values=values;p->u.array.count=t%16;js_array_mark(&rt,JS_MKPTR(JS_TAG_OBJECT,p),record_mark);
  num(201,4);p->u.object_data=mark_value(t);js_object_data_mark(&rt,JS_MKPTR(JS_TAG_OBJECT,p),record_mark);
  num(202,4);p->u.cfunc.realm=t%2?ctx:NULL;js_c_function_mark(&rt,JS_MKPTR(JS_TAG_OBJECT,p),record_mark);
  num(203,4);p->u.func.function_bytecode=t%2?b:NULL;p->u.func.var_refs=t%3?refs:NULL;p->u.func.home_object=t%4?(JSObject*)pool[3]:NULL;js_bytecode_function_mark(&rt,JS_MKPTR(JS_TAG_OBJECT,p),record_mark);
  num(204,4);js_limb_t buf[32];JSBoundFunction*bf=(JSBoundFunction*)buf;bf->func_obj=mark_value(t);bf->this_val=mark_value(t+1);bf->argc=t%8;for(int j=0;j<bf->argc;j++)bf->argv[j]=values[j];p->u.bound_function=bf;js_bound_function_mark(&rt,JS_MKPTR(JS_TAG_OBJECT,p),record_mark);
  num(205,4);JSForInIterator it={0};it.obj=mark_value(t);p->u.for_in_iterator=&it;js_for_in_iterator_mark(&rt,JS_MKPTR(JS_TAG_OBJECT,p),record_mark);
  num(206,4);JSCFunctionDataRecord*cd=(JSCFunctionDataRecord*)buf;cd->data_len=t%8;for(int j=0;j<cd->data_len;j++)cd->data[j]=values[j];p->class_id=JS_CLASS_C_FUNCTION_DATA;p->u.opaque=cd;js_c_function_data_mark(&rt,JS_MKPTR(JS_TAG_OBJECT,p),record_mark);
  num(207,4);p->u.global_object.uninitialized_vars=mark_value(t);js_global_object_mark(&rt,JS_MKPTR(JS_TAG_OBJECT,p),record_mark);
  num(208,4);JSFinalizationRegistryData fr={0};JSFinRecEntry entries[4]={0};init_list_head(&fr.entries);fr.realm=ctx;fr.cb=mark_value(t);for(int j=0;j<4;j++){entries[j].held_val=mark_value(t+j);list_add_tail(&entries[j].link,&fr.entries);}p->class_id=JS_CLASS_FINALIZATION_REGISTRY;p->u.opaque=&fr;js_finrec_mark(&rt,JS_MKPTR(JS_TAG_OBJECT,p),record_mark);
  num(209,4);JSMapState ms={0};JSMapRecord mr[4]={0};init_list_head(&ms.records);ms.is_weak=t%2;for(int j=0;j<4;j++){mr[j].key=mark_value(t+j);mr[j].value=mark_value(t+j+1);list_add_tail(&mr[j].link,&ms.records);}p->u.map_state=&ms;js_map_mark(&rt,JS_MKPTR(JS_TAG_OBJECT,p),record_mark);p->class_id=JS_CLASS_OBJECT;
 }
 js_free_rt(&rt,ctx->class_proto);for(int i=0;i<10;i++)js_free_rt(&rt,pool[i]);while(h.count)host_free(&rt.malloc_ctx.malloc_state,h.pointers[0]);return 0;
}
