struct PromiseFixtureTracking { out:*mut Vec<u8>, calls:i32, handled:i32 }
unsafe fn promise_fixture_tracker(_ctx:*mut JSContext,_promise:JSValueConst,value:JSValueConst,handled:JS_BOOL,opaque:*mut c_void){let t=&mut *opaque.cast::<PromiseFixtureTracking>();t.calls+=1;t.handled+=handled;num(&mut *t.out,handled as u64,4);dump_val(&mut *t.out,value);}
unsafe fn fixture_pending_promise(ctx:*mut JSContext)->JSValue{let obj=JS_NewObjectProtoClass(ctx,JS_NULL,JS_CLASS_PROMISE);let s=js_mallocz(ctx,size_of::<JSPromiseData>()).cast::<JSPromiseData>();assert!(!s.is_null());(*s).promise_state=JS_PROMISE_PENDING;(*s).promise_result=JS_UNDEFINED;for i in 0..2{init_list_head(&mut (*s).promise_reactions[i]);}JS_SetOpaque(obj,s.cast());obj}
unsafe fn promise_fixtures(out:&mut Vec<u8>,ctx:*mut JSContext,classes:&mut [JSClass]){
 let rt=(*ctx).rt;classes[JS_CLASS_PROMISE as usize].finalizer=Some(js_promise_finalizer);classes[JS_CLASS_PROMISE as usize].gc_mark=Some(js_promise_mark);for i in 0..2{classes[JS_CLASS_PROMISE_RESOLVE_FUNCTION as usize+i].finalizer=Some(js_promise_resolve_function_finalizer);classes[JS_CLASS_PROMISE_RESOLVE_FUNCTION as usize+i].gc_mark=Some(js_promise_resolve_function_mark);classes[JS_CLASS_PROMISE_RESOLVE_FUNCTION as usize+i].call=Some(js_promise_resolve_function_call);}
 let mut tracking=PromiseFixtureTracking{out,calls:0,handled:0};JS_SetHostPromiseRejectionTracker(rt,Some(promise_fixture_tracker),(&mut tracking as *mut PromiseFixtureTracking).cast());
 for kind in 0..8{for reject in 0..2{for before in 0..3{for argc in 0..2{
 let promise=fixture_pending_promise(ctx);let mut funcs=[JS_UNDEFINED;2];let mut handlers=[JS_UNDEFINED;2];let mut caps=[JS_UNDEFINED;2];assert_eq!(js_create_resolving_functions(ctx,funcs.as_mut_ptr(),promise),0);for _ in 0..before{num(out,perform_promise_then(ctx,promise,handlers.as_mut_ptr(),caps.as_mut_ptr()) as u64,4);}
 let mut value=match kind{0=>JS_UNDEFINED,1=>JS_NULL,2=>JS_TRUE,3=>JS_NewInt32(ctx,-99),4=>JS_NewFloat64(ctx,-0.0),5=>JS_NewString(ctx,c"promise雪".as_ptr()),6=>JS_NewObject(ctx),_=>JS_DupValue(ctx,promise)};
 for attempt in 0..2{let ret=js_promise_resolve_function_call(ctx,funcs[(reject+attempt)%2],JS_UNDEFINED,argc,&mut value,0);dump_val(out,ret);JS_FreeValue(ctx,ret);num(out,JS_PromiseState(ctx,promise) as u64,4);let result=JS_PromiseResult(ctx,promise);dump_val(out,result);JS_FreeValue(ctx,result);let f=(*JS_VALUE_GET_PTR(funcs[0]).cast::<JSObject>()).u.promise_function_data;num(out,(*(*f).presolved).already_resolved as u64,4);num(out,(*(*f).presolved).ref_count as u64,4);dump_exception(out,ctx);}
 num(out,perform_promise_then(ctx,promise,handlers.as_mut_ptr(),caps.as_mut_ptr()) as u64,4);num(out,JS_IsJobPending(rt) as u64,4);while JS_IsJobPending(rt)!=0{let mut chosen=ptr::null_mut();num(out,JS_ExecutePendingJob(rt,&mut chosen) as u64,4);num(out,(chosen==ctx) as u64,4);dump_exception(out,ctx);}num(out,tracking.calls as u64,4);num(out,tracking.handled as u64,4);JS_FreeValue(ctx,value);JS_FreeValue(ctx,funcs[0]);JS_FreeValue(ctx,funcs[1]);JS_FreeValue(ctx,promise);JS_RunGC(rt);
 }}}}
 JS_SetHostPromiseRejectionTracker(rt,None,ptr::null_mut());
}
