static JSValue fn_generic(JSContext*ctx,JSValueConst self,int argc,JSValueConst*argv){return JS_UNDEFINED;}
static JSValue fn_data(JSContext*ctx,JSValueConst self,int argc,JSValueConst*argv,int magic,JSValue*data){return JS_UNDEFINED;}
static JSValue fn_get(JSContext*ctx,JSValueConst self){return JS_UNDEFINED;}
static JSValue fn_set(JSContext*ctx,JSValueConst self,JSValueConst v){return JS_UNDEFINED;}
static void dump_func(JSValue v){JSObject*p=JS_VALUE_GET_OBJ(v);dump_object(p);num(p->is_constructor,4);num(p->u.cfunc.length,4);num(p->u.cfunc.cproto,4);num(p->u.cfunc.magic,4);num(js_rc(p->u.cfunc.realm)->ref_count,4);}
static JSValue oracle_job(JSContext*ctx,int argc,JSValueConst*argv){int*count=ctx->user_opaque;(*count)++;if(argc>0&&JS_VALUE_GET_INT(argv[0])<0)return JS_Throw(ctx,JS_NewInt32(ctx,-123));return JS_NewInt32(ctx,argc);}
static void jobs_weak_fixtures(JSContext*ctx,JSClass*classes){
 JSRuntime*rt=ctx->rt;init_list_head(&rt->job_list);int count=0;ctx->user_opaque=&count;
 for(int i=-5;i<20;i++){JSValue args[]={JS_NewInt32(ctx,i),JS_NewString(ctx,"job")};num(JS_EnqueueJob(ctx,oracle_job,2,args),4);for(int j=0;j<2;j++)JS_FreeValue(ctx,args[j]);}num(JS_IsJobPending(rt),4);
 for(int i=0;i<26;i++){JSContext*selected=NULL;num(JS_ExecutePendingJob(rt,&selected),4);num(selected!=NULL,4);num(count,4);dump_exception(ctx);}
 classes[JS_CLASS_WEAK_REF].finalizer=js_weakref_finalizer;classes[JS_CLASS_FINALIZATION_REGISTRY].finalizer=js_finrec_finalizer;classes[JS_CLASS_FINALIZATION_REGISTRY].gc_mark=js_finrec_mark;
 for(int i=0;i<20;i++){JSValue target=JS_NewObject(ctx);JSValue args[]={target};JSValue wr=js_weakref_constructor(ctx,JS_TRUE,1,args);assert(!JS_IsException(wr));JSValue v=js_weakref_deref(ctx,wr,0,NULL);dump_val(v);JS_FreeValue(ctx,v);JS_FreeValue(ctx,target);JS_RunGC(rt);v=js_weakref_deref(ctx,wr,0,NULL);dump_val(v);JS_FreeValue(ctx,v);JS_FreeValue(ctx,wr);}
 JSValue cb=JS_NewCFunction2(ctx,fn_generic,"cb",1,JS_CFUNC_generic,0),args[]={cb};JSValue registry=js_finrec_constructor(ctx,JS_TRUE,1,args);assert(!JS_IsException(registry));JSValue token=JS_NewObject(ctx);
 for(int i=0;i<8;i++){JSValue target=JS_NewObject(ctx);JSValue args[]={target,JS_NewInt32(ctx,i),token};JSValue v=js_finrec_register(ctx,registry,3,args);dump_val(v);JS_FreeValue(ctx,v);JS_FreeValue(ctx,target);}JSValue args2[]={token};JSValue v=js_finrec_unregister(ctx,registry,1,args2);dump_val(v);JS_FreeValue(ctx,v);v=js_finrec_unregister(ctx,registry,1,args2);dump_val(v);JS_FreeValue(ctx,v);
 for(int i=0;i<8;i++){JSValue target=JS_NewObject(ctx);JSValue args[]={target,JS_NewInt32(ctx,i),token};JSValue v=js_finrec_register(ctx,registry,3,args);dump_val(v);JS_FreeValue(ctx,v);JS_FreeValue(ctx,target);}JS_FreeValue(ctx,token);JS_RunGC(rt);num(JS_IsJobPending(rt),4);
 struct list_head*el,*el1;list_for_each_safe(el,el1,&rt->job_list){JSJobEntry*e=list_entry(el,JSJobEntry,link);num(e->argc,4);for(int i=0;i<e->argc;i++){dump_val(e->argv[i]);JS_FreeValue(ctx,e->argv[i]);}JS_FreeContext(e->realm);list_del(&e->link);js_free_rt(rt,e);}JS_FreeValue(ctx,registry);JS_FreeValue(ctx,cb);ctx->user_opaque=NULL;
}

int main(void){
 JSRuntime storage={0},*rt=&storage;JSContext initial={0};struct host h={0};JSClass classes[JS_CLASS_INIT_COUNT]={0};JSValue protos[JS_CLASS_INIT_COUNT];for(int i=0;i<JS_CLASS_INIT_COUNT;i++)protos[i]=JS_NULL;
 setup(rt,&initial,&h,classes,protos);JSContext*ctx=js_mallocz_rt(rt,sizeof(*ctx));num(h.trace,8);memcpy(ctx,&initial,sizeof(*ctx));init_list_head(&ctx->loaded_modules);js_rc(ctx)->ref_count=1000;ctx->function_proto=JS_NULL;
 classes[JS_CLASS_C_FUNCTION].finalizer=js_c_function_finalizer;classes[JS_CLASS_C_FUNCTION_DATA].finalizer=js_c_function_data_finalizer;
 const char*names[]={"","f","abc","雪","ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789abcdefghi"};int lengths[]={0,1,255,256},magics[]={-32769,-1,0,65535},nfields[]={0,8};
 for(int n=0;n<5;n++)for(int cp=0;cp<13;cp++)for(int l=0;l<4;l++)for(int m=0;m<4;m++)for(int nf=0;nf<2;nf++){JSValue v=JS_NewCFunction3(ctx,fn_generic,names[n],lengths[l],cp,magics[m],JS_NULL,nfields[nf]);assert(!JS_IsException(v));dump_func(v);JS_FreeValue(ctx,v);}
 JSValue data[]={JS_NewInt32(ctx,123),JS_NewString(ctx,"data"),JS_NULL};for(int n=0;n<4;n++){JSValue v=JS_NewCFunctionData(ctx,fn_data,257,-1,n,data);dump_object(JS_VALUE_GET_OBJ(v));JSCFunctionDataRecord*s=JS_GetOpaque(v,JS_CLASS_C_FUNCTION_DATA);num(s->length,4);num(s->data_len,4);num(s->magic,4);for(int i=0;i<n;i++)dump_val(s->data[i]);JS_FreeValue(ctx,v);}for(int i=0;i<3;i++)JS_FreeValue(ctx,data[i]);
 JSCFunctionListEntry sub[]={JS_PROP_INT32_DEF("answer",42,JS_PROP_C_W_E)};
 JSCFunctionListEntry fields[]={JS_CFUNC_DEF("run",2,fn_generic),JS_PROP_STRING_DEF("str","value",JS_PROP_C_W_E),JS_PROP_INT32_DEF("int",-17,JS_PROP_C_W_E),JS_PROP_INT64_DEF("large",9007199254740991LL,JS_PROP_C_W_E),JS_PROP_DOUBLE_DEF("dbl",-0.0,JS_PROP_C_W_E),JS_PROP_UNDEFINED_DEF("undef",JS_PROP_C_W_E),JS_PROP_BOOL_DEF("bool",1,JS_PROP_C_W_E),JS_PROP_ATOM_DEF("atom",JS_ATOM_name,JS_PROP_C_W_E),JS_OBJECT_DEF("nested",sub,1,JS_PROP_C_W_E),JS_CGETSET_DEF("access",fn_get,fn_set),JS_ALIAS_DEF("alias","str")};
 JSValue obj=JS_NewObject(ctx);num(JS_SetPropertyFunctionList(ctx,obj,fields,countof(fields)),4);for(int i=0;i<countof(fields);i++){JSCFunctionListEntry*e=fields+i;JSAtom atom=find_atom(ctx,e->name);if(e->def_type!=JS_DEF_CGETSET){JSValue v=JS_GetProperty(ctx,obj,atom);dump_val(v);if(JS_IsObject(v))dump_object(JS_VALUE_GET_OBJ(v));JS_FreeValue(ctx,v);}JS_FreeAtom(ctx,atom);}dump_object(JS_VALUE_GET_OBJ(obj));JS_FreeValue(ctx,obj);
 ctx->global_obj=JS_NewObject(ctx);for(int flags=0;flags<16;flags++){if(flags&JS_NEW_CTOR_PROTO_EXIST)protos[JS_CLASS_OBJECT]=JS_NewObjectProtoClass(ctx,JS_NULL,JS_CLASS_OBJECT);JSValue ctor=JS_NewCConstructor(ctx,JS_CLASS_OBJECT,"Custom",fn_generic,2,JS_CFUNC_constructor_or_func,7,JS_UNDEFINED,NULL,0,NULL,0,flags);assert(!JS_IsException(ctor));dump_func(ctor);JSValue proto=JS_GetProperty(ctx,ctor,JS_ATOM_prototype);dump_object(JS_VALUE_GET_OBJ(proto));num(delete_property(ctx,JS_VALUE_GET_OBJ(proto),JS_ATOM_constructor),4);if(!(flags&JS_NEW_CTOR_NO_GLOBAL)){JSAtom a=JS_NewAtom(ctx,"Custom");delete_property(ctx,JS_VALUE_GET_OBJ(ctx->global_obj),a);JS_FreeAtom(ctx,a);}JS_FreeValue(ctx,proto);JS_FreeValue(ctx,ctor);JS_FreeValue(ctx,protos[JS_CLASS_OBJECT]);protos[JS_CLASS_OBJECT]=JS_NULL;}
 JS_FreeValue(ctx,ctx->global_obj);jobs_weak_fixtures(ctx,classes);num(js_rc(ctx)->ref_count,4);assert(js_rc(ctx)->ref_count==1000);num(h.calls,4);num(h.live,4);num(h.trace,8);js_free_shape(rt,ctx->array_shape);js_free_rt(rt,ctx);assert(rt->shape_hash_count==0);assert(list_empty(&rt->gc_obj_list));js_free_rt(rt,rt->shape_hash);cleanup(rt,&h);assert(h.live==0);return 0;
}
