static void objects_ropes_fixtures(JSContext*ctx,struct host*h){
 for(int fail=0;fail<32;fail++){
  JSValue obj=JS_NewObject(ctx),desc=JS_NewObject(ctx);JSAtom atom=JS_ATOM_name;if(fail)h->fail=h->calls+fail;
  for(int step=0;step<12;step++){JS_SetPropertyStr(ctx,desc,"value",JS_NewInt32(ctx,step));JS_SetPropertyStr(ctx,desc,"enumerable",JS_NewBool(ctx,step&1));JS_SetPropertyStr(ctx,desc,"configurable",JS_TRUE);JS_SetPropertyStr(ctx,desc,"writable",JS_TRUE);num(JS_DefinePropertyDesc(ctx,obj,atom,desc,JS_PROP_THROW),4);dump_exception(ctx);JSValue args[]={obj,JS_AtomToValue(ctx,atom),desc};JSValue value=js_object_getOwnPropertyDescriptor(ctx,JS_UNDEFINED,2,args,step&1);dump_val(value);if(JS_IsObject(value))dump_object(JS_VALUE_GET_OBJ(value));JS_FreeValue(ctx,value);JS_FreeValue(ctx,args[1]);dump_exception(ctx);}
  h->fail=0;JSValue excluded=JS_NewObject(ctx);JS_DefinePropertyValue(ctx,excluded,atom,JS_TRUE,JS_PROP_C_W_E);JSValue target=JS_NewObject(ctx);num(JS_CopyDataProperties(ctx,target,obj,excluded,0),4);dump_exception(ctx);dump_object(JS_VALUE_GET_OBJ(target));num(JS_CopyDataProperties(ctx,target,obj,JS_UNDEFINED,1),4);dump_exception(ctx);dump_object(JS_VALUE_GET_OBJ(target));JS_FreeValue(ctx,excluded);JS_FreeValue(ctx,target);
  for(int kind=0;kind<3;kind++){JSValue v=JS_GetOwnPropertyNames2(ctx,obj,JS_GPN_STRING_MASK|JS_GPN_ENUM_ONLY,kind);dump_val(v);if(JS_IsObject(v))dump_object(JS_VALUE_GET_OBJ(v));JS_FreeValue(ctx,v);dump_exception(ctx);}JSValue arg[]={obj};JSValue sealed=js_object_seal(ctx,JS_UNDEFINED,1,arg,fail&1);dump_val(sealed);JS_FreeValue(ctx,sealed);dump_exception(ctx);for(int frozen=0;frozen<2;frozen++){JSValue v=js_object_isSealed(ctx,JS_UNDEFINED,1,arg,frozen);dump_val(v);JS_FreeValue(ctx,v);dump_exception(ctx);}JS_FreeValue(ctx,desc);JS_FreeValue(ctx,obj);
 }
 JSProxyData proxy_data={0};JSValue proxy=JS_NewObjectClass(ctx,JS_CLASS_PROXY);JSObject*p=JS_VALUE_GET_OBJ(proxy);p->u.proxy_data=&proxy_data;proxy_data.target=JS_NewArray(ctx);num(JS_IsArray(ctx,proxy),4);dump_exception(ctx);proxy_data.is_revoked=1;num(JS_IsArray(ctx,proxy),4);dump_exception(ctx);JS_FreeValue(ctx,proxy_data.target);p->u.proxy_data=NULL;JS_FreeValue(ctx,proxy);
 JSValue rope=JS_AtomToString(ctx,JS_ATOM_empty_string);for(int step=0;step<192;step++){uint16_t units[526];int size=513+step%13;for(int i=0;i<size;i++)units[i]=(i+step)%503+32;JSValue leaf=js_new_string16_len(ctx,units,size);rope=(step%7==0)?JS_ConcatString(ctx,leaf,rope):JS_ConcatString(ctx,rope,leaf);num(JS_VALUE_GET_TAG(rope),4);uint32_t len=string_rope_get_len(rope);num(len,4);if(JS_VALUE_GET_TAG(rope)==JS_TAG_STRING_ROPE){JSStringRope*r=JS_VALUE_GET_STRING_ROPE(rope);num(r->depth,4);num(r->is_wide_char,4);}else{num(0,4);num(JS_VALUE_GET_STRING(rope)->is_wide_char,4);}uint32_t indices[]={0,len/2,len-1};for(int i=0;i<3;i++)num(string_rope_get(rope,indices[i]),4);}
 JSValue flat=JS_ToString(ctx,rope);dump_val(flat);JS_FreeValue(ctx,flat);JSValue suffix=JS_NewString(ctx,"tail");rope=JS_ConcatString(ctx,rope,suffix);flat=JS_ToStringFree(ctx,rope);dump_val(flat);JS_FreeValue(ctx,flat);
 for(int fail=1;fail<32;fail++){JSValue left=JS_NewString(ctx,"left");uint16_t units[1024];for(int i=0;i<1024;i++)units[i]=0x100;JSValue right=js_new_string16_len(ctx,units,1024);h->fail=h->calls+fail;JSValue value=JS_ConcatString(ctx,left,right);h->fail=0;JSValue flat=JS_ToStringFree(ctx,value);dump_val(flat);JS_FreeValue(ctx,flat);dump_exception(ctx);}
}
