#!/usr/bin/env python3
"""Generate parser grammar and shorthand metadata from current Blink sources.
Only complete simple return consumers and source keyword grammars are admitted.
Complex consumers remain explicit Unsupported at runtime.
"""
import pathlib, re, sys
HERE=pathlib.Path(__file__).resolve().parent
SRC=pathlib.Path(sys.argv[1]) if len(sys.argv)>1 else HERE.parents[2]/'src'
CORE=SRC/'third_party/blink/renderer/core'
GEN=SRC/'out/Min/gen/third_party/blink/renderer/core'
files=[GEN/'css/properties/longhands.cc', CORE/'css/properties/longhands/longhands_custom.cc']
names={}
for p in [GEN/'css/properties/longhands.cc',GEN/'css/properties/shorthands.cc']:
    names.update({name: prop for prop,name in re.findall(r'const char\* (\w+)::GetPropertyName\(\) const \{\s*return "([^"]+)";',p.read_text())})
keywords={}
text=(CORE/'css/css_properties.json5').read_text()
for m in re.finditer(r'^    \{(.*?)^    \},', text, re.M|re.S):
    block=m[1]
    name=re.search(r'name:\s*"([^"]+)"',block)
    field=re.search(r'field_template:\s*"keyword"',block)
    # WhiteSpaceCollapse uses a primitive enum field, but its generated parser
    # is the same source keyword grammar (css_properties.json5:8159-8172).
    if name and name[1] == "white-space-collapse": field=True
    # FontBuilder-owned fields still use the same generated keyword grammar.
    if name and name[1] in {"font-kerning", "font-optical-sizing", "font-variant-position", "font-variant-emoji", "text-spacing-trim", "font-synthesis-weight", "font-synthesis-style", "font-synthesis-small-caps", "text-rendering", "-webkit-font-smoothing"}: field=True
    # SVG primitive fields are genuine generated keyword grammars too.
    if name and name[1] in {"stroke-linecap", "stroke-linejoin", "fill-rule", "clip-rule", "scroll-behavior"}: field=True
    kw=re.search(r'keywords:\s*\[([^]]*)\]',block,re.S)
    if not(name and field and kw) or '"ParseSingleValue"' in block: continue
    body=re.sub(r'//[^\n]*','',kw[1])
    if re.sub(r'"[^"]+"|[\s,]','',body): continue
    if name[1] in names: keywords[names[name[1]]]=(re.findall(r'"([^"]+)"',body),text.count('\n',0,m.start())+1)
def functions(text, pattern):
    for m in re.finditer(pattern,text):
        start=m.end(); end=start; depth=1
        while depth:
            depth += (text[end]=='{')-(text[end]=='}'); end+=1
        yield m.groups(),text[start:end-1],text.count('\n',0,m.start())+1
out=['// Generated by generate_property_parser_metadata.py; only source-complete grammar branches.','use foundation::{CSSPropertyID, CSSValueID};','use super::production_property_parser::Grammar;','pub fn GrammarFor(id: CSSPropertyID) -> Grammar { match id {']
for prop,(words,line) in keywords.items():
    # Outline's parser uses IsValidKeywordPropertyAndValue rather than the
    # field enum list: css_parser_fast_paths.cc:1288-1291 admits auto, not hidden.
    if prop == 'OutlineStyle': words=['auto','none','inset','groove','outset','ridge','dotted','dashed','solid','double']
    out += [f'// cpp: third_party/blink/renderer/core/css/css_properties.json5:{line}',f'CSSPropertyID::k{prop} => Grammar::Keywords(&[{", ".join(chr(34)+w+chr(34) for w in words)}]),']
seen=set(keywords)
for p in files:
    text=p.read_text()
    for (prop,),body,line in functions(text,r'const CSSValue\* (\w+)::ParseSingleValue\([^)]*\) const \{'):
        if prop in seen: continue
        b=re.sub(r'//[^\n]*','',body).strip()
        # Admit complete one-return consumer bodies only. Parameters select the
        # source range and quirks policy, never inferred from property names.
        m=re.fullmatch(r'return (?:css_parsing_utils::)?((?:Consume|Parse)\w+)\((.*?)\);',b,re.S)
        if not m: continue
        consume,args=m.groups(); grammar=None
        nonnegative='kNonNegative' in args
        quirks='UnitlessQuirk::kAllow' in args
        if consume=='ParseContentValue': grammar='Grammar::Content'
        elif consume=='ConsumeNumber': grammar=f'Grammar::Number {{ nonnegative: {str(nonnegative).lower()} }}'
        elif consume in ['ConsumeLengthOrPercent','ConsumeLength']:
            grammar=f'Grammar::Length {{ percent: {str(consume=="ConsumeLengthOrPercent").lower()}, nonnegative: {str(nonnegative).lower()}, quirks: {str(quirks).lower()}, keywords: &[] }}'
        elif consume=='ConsumeMarginOrOffset': grammar=f'Grammar::Length {{ percent: true, nonnegative: false, quirks: {str(quirks).lower()}, keywords: &["auto"] }}'
        elif consume in ['ConsumeWidthOrHeight','ConsumeMaxWidthOrHeight']:
            keyword='none' if consume=='ConsumeMaxWidthOrHeight' else 'auto'
            grammar=f'Grammar::Length {{ percent: true, nonnegative: true, quirks: {str(quirks).lower()}, keywords: &["{keyword}", "min-content", "max-content", "fit-content", "stretch", "-webkit-fill-available"] }}'
        elif consume in ['ConsumeLineWidth','ConsumeBorderWidth','ParseBorderWidthSide']:
            grammar=f'Grammar::Length {{ percent: false, nonnegative: true, quirks: {str(quirks or consume=="ParseBorderWidthSide").lower()}, keywords: &["thin", "medium", "thick"] }}'
        elif consume=='ParseSpacing': grammar='Grammar::Length { percent: true, nonnegative: false, quirks: true, keywords: &["normal"] }'
        elif consume in ['ConsumeColor','ConsumeColorMaybeQuirky']: grammar='Grammar::Color'
        elif consume=='ConsumeScrollPadding': grammar='Grammar::Length { percent: true, nonnegative: true, quirks: false, keywords: &["auto"] }'
        elif consume in ['ConsumeInteger','ConsumeIntegerOrNumberCalc']:
            minimum=1 if ('kPositiveInteger' in args or re.search(r',\s*1\s*$',args)) else 0 if 'kNonNegativeInteger' in args or re.search(r',\s*0\s*$',args) else -2147483648
            grammar=f'Grammar::Integer {{ minimum: {minimum} }}'
        if grammar:
            seen.add(prop)
            out += [f'// cpp: {p.relative_to(SRC)}:{line}',f'CSSPropertyID::k{prop} => {grammar},']
out += ['_ => Grammar::Unsupported,','} }']
# Chromium's unresolved enum also includes aliases. The foundation helper only
# accepts resolved IDs, so construct aliases from their generated discriminants.
property_names_header=(GEN/'css/css_property_names.h').read_text()
out += ['// cpp: out/Min/gen/third_party/blink/renderer/core/css/css_property_names.h:22-849',
        'pub(crate) fn UnresolvedPropertyIDFromInteger(value: i32) -> CSSPropertyID { match value {']
for name,number in re.findall(r'^\s*(kAlias\w+) = (\d+),',property_names_header,re.M):
    out.append(f'{number} => CSSPropertyID::{name},')
out += ['_ => foundation::ConvertToCSSPropertyID(value),','} }']

short=(GEN/'style_property_shorthand.cc').read_text()
shorthand={}; methods={}; line_runtime_shorthands=set()
for (method,),body,line in functions(short,r'(?:static )?const StylePropertyShorthand[&*] (\w+)\(\) \{'):
    ids=re.findall(r'&GetCSSProperty(\w+)\(\)',body)
    m=re.search(r'CSSPropertyID::k(\w+), longhands',body)
    if ids and m and 'RuntimeEnabledFeatures' not in body:
        shorthand[m[1]]=(ids,line); methods[method]=m[1]
    # TimelineTrigger is stable in this checkout; generated *1 contains
    # the real stable six/two-field list and wrapper methods omit the suffix.
    if ids and m and m[1] == 'GridLanes':
        shorthand[m[1]]=(ids,line); methods[method.removesuffix('1')]=m[1]
    if ids and m and m[1] in {'TimelineTrigger','TimelineTriggerActivationRange','TimelineTriggerActiveRange'}:
        shorthand[m[1]]=(ids,line); methods[method.removesuffix('1')]=m[1]
    if ids and m and m[1] in {'AlternativeLineClampShorthand','AlternativeWebkitLineClampShorthand'}:
        shorthand[m[1]]=(ids,line)
        methods[method.removesuffix('1')]=m[1]
        line_runtime_shorthands.add(m[1])
# Stable runtime defaults: CSSFontSizeAdjust and FontLanguageOverride are true.
# Generated fontShorthand3 retains both conditional reset longhands.
for (method,),body,line in functions(short,r'(?:static )?const StylePropertyShorthand[&*] (\w+)\(\) \{'):
    if method == 'fontShorthand3':
        shorthand['Font']=(re.findall(r'&GetCSSProperty(\w+)\(\)',body),line)
        methods['fontShorthand']='Font'
out += ['pub fn ShorthandFor(id: CSSPropertyID) -> &\'static [CSSPropertyID] { match id {']
for prop,(ids,line) in shorthand.items():
    value=f'&[{", ".join("CSSPropertyID::k"+i for i in ids)}]'
    if prop in line_runtime_shorthands:
        value=f'if foundation::RuntimeEnabledFeatures::CSSLineClampAsShorthandEnabled() {{ {value} }} else {{ &[] }}'
    out += [f'// cpp: out/Min/gen/third_party/blink/renderer/core/style_property_shorthand.cc:{line}',f'CSSPropertyID::k{prop} => {value},']
out += ['_ => &[],','} }','pub fn MatchingShorthands(id: CSSPropertyID) -> Vec<CSSPropertyID> { match id {']
matching=short[short.index('void getMatchingShorthandsForLonghand'):]
for m in re.finditer(r'case CSSPropertyID::k(\w+): \{(.*?)\n    \}',matching,re.S):
    ids=[methods[n] for n in re.findall(r'UncheckedAppend\((\w+)\(\)\)',m[2]) if n in methods]
    if ids:
        value=f'vec![{", ".join("CSSPropertyID::k"+i for i in ids)}]'
        if any(i in line_runtime_shorthands for i in ids):
            value += '.into_iter().filter(|&id| crate::production_line_features::IsExposed(id)).collect()'
        # getMatchingShorthandsForLonghand gates Corner* with IsWebExposed.
        # Filtering is required before the source CSSPropertyValue 2-bit index.
        if any(i.startswith('Corner') and not i.endswith('Shape') for i in ids):
            value += '.into_iter().filter(|&id| crate::production_corner_features::IsExposed(id)).collect()'
        out.append(f'CSSPropertyID::k{m[1]} => {value},')
out += ['_ => Vec::new(),','} }']
color_source=(SRC/'out/Min/gen/third_party/blink/renderer/platform/color_data.cc').read_text()
out += ['pub fn NamedColor(name: &str) -> Option<foundation::Color> { match name {']
for m in re.finditer(r'\{"([^"]+)", (0x[0-9a-f]+)\}',color_source):
    out += [f'// cpp: out/Min/gen/third_party/blink/renderer/platform/color_data.cc:{color_source.count(chr(10),0,m.start())+1}',f'"{m[1]}" => Some(foundation::Color::FromRGBA32({m[2]})),']
out += ['_ => None,','} }']

manual={'Display','FontSize','LineHeight','FontWeight','FontFamily','FontStyle','ZIndex','RowGap','ColumnGap','FlexBasis','Opacity','FillOpacity','FloodOpacity','StopOpacity','StrokeOpacity','GridTemplateColumns','GridTemplateRows','GridAutoColumns','GridAutoRows','BorderTopLeftRadius','BorderTopRightRadius','BorderBottomLeftRadius','BorderBottomRightRadius'}
# Source-complete custom consumers implemented in production_property_parser.
# Keep this list beside generation so regenerating metadata cannot silently
# downgrade their ledger coverage to Unsupported.
animation_cluster={'Animation','AnimationComposition','AnimationDelay','AnimationDirection',
    'AnimationDuration','AnimationFillMode','AnimationIterationCount','AnimationName',
    'AnimationPlayState','AnimationTimingFunction','AnimationTimeline','AnimationTrigger','AnimationRange',
    'AnimationRangeStart','AnimationRangeEnd','Transition','TransitionBehavior',
    'TransitionDelay','TransitionDuration','TransitionProperty','TransitionTimingFunction'}
manual.update(animation_cluster)
timeline_cluster={'ScrollTimelineName','ScrollTimelineAxis','ScrollTimeline','ViewTimelineName','ViewTimelineAxis','ViewTimelineInset','ViewTimeline','TimelineScope'}
manual.update(timeline_cluster)
initial_scope_cluster={'InitialLetter','ScrollMarkerGroup','TriggerScope'}
manual.update(initial_scope_cluster)
border_image_cluster={'BorderImageSource','BorderImageSlice','BorderImageWidth','BorderImageOutset','BorderImageRepeat','BorderImage','WebkitBorderImage'}
manual.update(border_image_cluster)
mask_cluster={'Mask','MaskImage','MaskClip','MaskOrigin','MaskComposite','MaskMode','MaskSize','MaskRepeat','WebkitMaskPositionX','WebkitMaskPositionY','WebkitMaskBoxImage','WebkitMaskBoxImageSource','WebkitMaskBoxImageSlice','WebkitMaskBoxImageWidth','WebkitMaskBoxImageOutset','WebkitMaskBoxImageRepeat'}
manual.update(mask_cluster)
motion_cluster={"Offset","OffsetPath","OffsetRotate","OffsetDistance","OffsetPosition","OffsetAnchor"}
manual.update(motion_cluster)
grid_lanes_cluster={'GridLanes','GridLanesDirection','GridLanesPack'}
manual.update(grid_lanes_cluster)
rule_behavior_cluster={'RuleBreak','RuleVisibilityItems','ColumnRuleBreak','RowRuleBreak','ColumnRuleVisibilityItems','RowRuleVisibilityItems'}
manual.update(rule_behavior_cluster)
rule_inset_cluster={axis+'RuleInset'+suffix for axis in ('Column','Row','') for suffix in ('','Cap','Junction','Start','End')} | {axis+'RuleInset'+suffix for axis in ('Column','Row') for suffix in ('CapStart','CapEnd','JunctionStart','JunctionEnd')}
manual.update(rule_inset_cluster)
render_delay_cluster={'DynamicRangeLimit','FlowTolerance','InterestDelay','InterestDelayStart','InterestDelayEnd'}
manual.update(render_delay_cluster)
timeline_trigger_cluster={'TimelineTriggerName','TimelineTriggerSource','TimelineTriggerActivationRangeStart','TimelineTriggerActivationRangeEnd','TimelineTriggerActiveRangeStart','TimelineTriggerActiveRangeEnd','TimelineTrigger','TimelineTriggerActivationRange','TimelineTriggerActiveRange'}
manual.update(timeline_trigger_cluster)
view_transition_cluster={"ViewTransitionName","ViewTransitionClass","ViewTransitionGroup"}
manual.update(view_transition_cluster)
interaction_cluster={'TouchAction','WillChange','Appearance','ImageOrientation','HangingPunctuation','MarginTrim'}
manual.update(interaction_cluster)
grid_core_cluster={'GridTemplateAreas','GridTemplate','Grid'}
manual.update(grid_core_cluster)
manual.update({'FontFeatureSettings', 'FontVariationSettings'})
font_cluster={'Font','FontVariant','FontVariantCaps','FontVariantLigatures','FontVariantNumeric','FontVariantEastAsian','FontVariantAlternates','FontVariantPosition','FontVariantEmoji','FontLanguageOverride','FontSizeAdjust'}
manual.update(font_cluster)
effects_cluster={'Filter','BackdropFilter','ClipPath','Cursor','ShapeOutside','ShapeImageThreshold'}
manual.update(effects_cluster)
color_ui_cluster={'AccentColor','CaretColor','ColorScheme','InternalVisitedCaretColor','InternalVisitedOutlineColor',
    'InternalVisitedBorderTopColor','InternalVisitedBorderRightColor','InternalVisitedBorderBottomColor','InternalVisitedBorderLeftColor',
    'InternalVisitedBorderBlockStartColor','InternalVisitedBorderBlockEndColor','InternalVisitedBorderInlineStartColor','InternalVisitedBorderInlineEndColor'}
manual.update(color_ui_cluster)
manual.update({'OutlineColor'})
manual.update({'ContainerName', 'ContainerType', 'Container'})
manual.update({'BoxShadow', 'TextShadow', 'BackgroundImage'})
layout_misc_cluster={'AspectRatio','ColumnCount','ColumnWidth','ColumnHeight','Columns','Contain',
    'ContainIntrinsicWidth','ContainIntrinsicHeight','ContainIntrinsicInlineSize',
    'ContainIntrinsicBlockSize','ContainIntrinsicSize','Orphans','Widows'}
manual.update(layout_misc_cluster)
list_counter_cluster={'CounterIncrement','CounterReset','CounterSet','Quotes','ListStyleType','ListStyleImage','ListStylePosition','ListStyle'}
manual.update(list_counter_cluster)
scroll_sides={'ScrollMarginTop','ScrollMarginRight','ScrollMarginBottom','ScrollMarginLeft',
    'ScrollMarginBlockStart','ScrollMarginBlockEnd','ScrollMarginInlineStart','ScrollMarginInlineEnd',
    'ScrollPaddingTop','ScrollPaddingRight','ScrollPaddingBottom','ScrollPaddingLeft',
    'ScrollPaddingBlockStart','ScrollPaddingBlockEnd','ScrollPaddingInlineStart','ScrollPaddingInlineEnd'}
scroll_shorthands={'OverscrollBehavior','ScrollMarginBlock','ScrollMarginInline','ScrollPaddingBlock','ScrollPaddingInline'}
scroll_properties={'ScrollbarColor','ScrollbarGutter','OverscrollBehaviorX','OverscrollBehaviorY','ScrollSnapAlign','ScrollSnapType'}
manual.update(scroll_properties | scroll_sides | scroll_shorthands)
line_stable={'VerticalAlign','TabSize','WebkitLineClamp','BreakBefore','BreakAfter','BreakInside','PageBreakBefore','PageBreakAfter','PageBreakInside'}
line_runtime={'LineClamp','MaxLines','Continue','BlockEllipsis','AlternativeWebkitLineClampLonghand','AlternativeLineClampShorthand','AlternativeWebkitLineClampShorthand'}
manual.update(line_stable | line_runtime)
anchor_cluster={'AnchorName','AnchorScope','PositionAnchor','PositionArea','PositionVisibility','PositionTryFallbacks','PositionTryOrder','PositionTry'}
manual.update(anchor_cluster)
typography_cluster={'TextEmphasisStyle','TextEmphasisPosition','TextEmphasisColor','TextEmphasis','HyphenateCharacter','HyphenateLimitChars','RubyPosition','RubyOverhang','TextSizeAdjust','TextDecorationSkipSpaces'}
manual.update(typography_cluster)
text_box_cluster={'TextBoxEdge','TextBoxTrim','TextBox','TextFit','TextAutospace','TextSpacingTrim','TextSpacing','TextDecorationInset','WebkitTextDecorationsInEffect'}
manual.update(text_box_cluster)
column_rule_cluster={'ColumnRuleColor','ColumnRuleStyle','ColumnRuleWidth','ColumnRule','WebkitColumnBreakBefore','WebkitColumnBreakAfter','WebkitColumnBreakInside'}
manual.update(column_rule_cluster)
row_rule_cluster={'RowRuleColor','RowRuleStyle','RowRuleWidth','RowRule','RuleColor','RuleStyle','RuleWidth','Rule'}
manual.update(row_rule_cluster)
stable_misc_cluster={'FontSynthesis','FontSynthesisWeight','FontSynthesisStyle','FontSynthesisSmallCaps','MathDepth','WebkitBoxOrdinalGroup','ScrollBehavior'}
manual.update(stable_misc_cluster)
reflection_visited_cluster={'InternalVisitedFill','InternalVisitedStroke','WebkitBoxReflect'}
manual.update(reflection_visited_cluster)
palette_internal_cluster={'FontPalette','InternalAlignContentBlock','InternalEmptyLineHeight'}
manual.update(palette_internal_cluster)

text_cluster={'TextAlign','TextTransform','TextOverflow','TextIndent','TextDecorationLine',
    'TextDecorationThickness','TextUnderlineOffset','TextUnderlinePosition','TextJustify','TextDecoration'}
manual.update(text_cluster)
svg_properties={'Fill','Stroke','StrokeWidth','StrokeDashoffset','StrokeDasharray',
                'Cx','Cy','R','Rx','Ry','X','Y','PathLength','PaintOrder','FillRule','ClipRule'}
manual.update(svg_properties)
svg_presentation={'D','MarkerStart','MarkerMid','MarkerEnd','Marker','BaselineShift',
                  'StrokeLinecap','StrokeLinejoin','StrokeMiterlimit',
                  'WebkitTextStrokeWidth','WebkitTextStrokeColor','WebkitTextStroke'}
manual.update(svg_presentation)
viewport_cluster={'Zoom','Clip','Size','Page','WebkitLocale','ObjectViewBox'}
manual.update(viewport_cluster)
border_colors={'BorderTopColor','BorderRightColor','BorderBottomColor','BorderLeftColor'}
border_radii={'BorderStartStartRadius','BorderStartEndRadius','BorderEndStartRadius','BorderEndEndRadius',
              'BorderTopLeftRadius','BorderTopRightRadius','BorderBottomRightRadius','BorderBottomLeftRadius','BorderRadius'}
border_shorthands={'BorderSpacing','BorderBlockColor','BorderInlineColor','BorderBlockStyle','BorderInlineStyle',
                  'BorderBlockWidth','BorderInlineWidth'}
border_styles={'BorderBlockStartStyle','BorderBlockEndStyle','BorderInlineStartStyle','BorderInlineEndStyle'}
border_widths={'BorderTopWidth','BorderRightWidth','BorderBottomWidth','BorderLeftWidth',
    'BorderBlockStartWidth','BorderBlockEndWidth','BorderInlineStartWidth','BorderInlineEndWidth'}
manual.update(border_colors | border_radii | border_shorthands | border_styles)
logical_border_shorthands={'BorderBlock','BorderInline','BorderBlockStart','BorderBlockEnd','BorderInlineStart','BorderInlineEnd'}
manual.update(logical_border_shorthands)
transform_cluster={'Transform','Translate','Rotate','Scale','Perspective',
    'TransformOrigin','PerspectiveOrigin','WebkitTransformOriginX',
    'WebkitTransformOriginY','WebkitTransformOriginZ','WebkitPerspectiveOriginX',
    'WebkitPerspectiveOriginY'}
manual.update(transform_cluster)
position_cluster={'BackgroundPosition','MaskPosition','BackgroundRepeat','MaskRepeat',
    'ObjectPosition','PerspectiveOrigin','OffsetAnchor','OffsetPosition','TransformOrigin'}
manual.update(position_cluster)
manual.update({
    'BackgroundAttachment','BackgroundBlendMode','BackgroundClip','BackgroundOrigin',
    'BackgroundSize','BackgroundPositionX','BackgroundPositionY','MaskClip',
    'MaskComposite','MaskMode','MaskOrigin','MaskSize','WebkitMaskPositionX',
    'WebkitMaskPositionY','WebkitPerspectiveOriginX','WebkitPerspectiveOriginY',
    'WebkitTransformOriginX','WebkitTransformOriginY','GridAutoFlow',
    'GridColumnStart','GridColumnEnd','GridRowStart','GridRowEnd','GridColumn',
    'GridRow','GridArea','OverflowClipMargin','FontStretch',
    'AlignContent','AlignItems','AlignSelf','JustifyContent','JustifyItems',
    'JustifySelf','PlaceContent','PlaceItems','PlaceSelf','TextWrap','FlexWrap',
})
# These keyword consumers and shorthands are source-complete at stable defaults.
complete={'AlignContent','AlignItems','AlignSelf','JustifyContent','JustifyItems',
          'JustifySelf','PlaceContent','PlaceItems','PlaceSelf','WhiteSpace',
          'WhiteSpaceCollapse','TextWrap','TextWrapMode','TextWrapStyle','FlexWrap','FlexFlow'}
complete.update({'BackgroundRepeat','MaskRepeat'})
complete.update({'FontKerning', 'FontOpticalSizing'})
complete.update(font_cluster - {'Font','FontSizeAdjust'})
complete.update({'OutlineStyle', 'OverflowX', 'OverflowY', 'Overflow'})
complete.add('ContainerType')
complete.update({'Direction','WritingMode'})
complete.add('TextDecorationStyle')
complete.update({'AnimationComposition','AnimationDirection','AnimationFillMode',
                 'AnimationPlayState','TransitionBehavior'})
animation_pending={
    'Animation': 'extended CSSMath functions/typed exponent arithmetic; CSSIdentFunction runtime option; use counters; shadow name TreeScope population',
    'AnimationDuration': 'extended CSSMath functions/typed exponent arithmetic',
    'AnimationDelay': 'extended CSSMath functions/typed exponent arithmetic',
    'AnimationIterationCount': 'extended CSSMath functions/typed exponent arithmetic',
    'AnimationName': 'CSSIdentFunction runtime option; quoted-name use counters; shadow TreeScope population/HasTreeScopedReference',
    'AnimationTimeline': 'CSSScrollValue/CSSViewValue; CSSIdentFunction runtime option; TreeScope population',
    'AnimationTrigger': 'CSSIdentFunction runtime option; TreeScope population',
    'AnimationRange': 'extended CSSMath functions/typed arithmetic; alternate ScrollTimelineNamedRangeScroll runtime option',
    'AnimationRangeStart': 'extended CSSMath functions/typed arithmetic; alternate ScrollTimelineNamedRangeScroll runtime option',
    'AnimationRangeEnd': 'extended CSSMath functions/typed arithmetic; alternate ScrollTimelineNamedRangeScroll runtime option',
    'AnimationTimingFunction': 'extended CSSMath functions/typed exponent arithmetic; element-dependent easing arguments; CSSLinearEasing use counter',
    'Transition': 'extended CSSMath functions/typed exponent arithmetic; ExecutionContext property exposure; CSSIdentFunction runtime option; custom-name TreeScope population',
    'TransitionDuration': 'extended CSSMath functions/typed exponent arithmetic',
    'TransitionDelay': 'extended CSSMath functions/typed exponent arithmetic',
    'TransitionProperty': 'ExecutionContext property exposure; CSSIdentFunction runtime option; custom-name TreeScope population',
    'TransitionTimingFunction': 'extended CSSMath functions/typed exponent arithmetic; element-dependent easing arguments; CSSLinearEasing use counter',
}
position_pending={
    'BackgroundPosition': 'CSSMathFunctionValue / negative percentage reference; three-valued position use counter',
    'MaskPosition': 'CSSMathFunctionValue / negative percentage reference; alias three-valued position use counter',
    'ObjectPosition': 'ConsumePosition CSSMathFunctionValue',
    'PerspectiveOrigin': 'ConsumePosition CSSMathFunctionValue',
    'OffsetAnchor': 'ConsumePosition CSSMathFunctionValue',
    'OffsetPosition': 'ConsumePosition CSSMathFunctionValue; CSSOffsetInEffect use counter',
    'TransformOrigin': 'ConsumeOneOrTwoValuedPosition / ConsumeLength CSSMathFunctionValue',
}
locations={prop:('third_party/blink/renderer/core/css/css_properties.json5',line,'generated keyword grammar') for prop,(_,line) in keywords.items()}
for p in files:
    for (prop,),body,line in functions(p.read_text(),r'const CSSValue\* (\w+)::ParseSingleValue\([^)]*\) const \{'):
        consumer=re.search(r'(?:css_parsing_utils::)?((?:Consume|Parse)\w+)',body)
        locations[prop]=(str(p.relative_to(SRC)),line,consumer[1] if consumer else prop+'::ParseSingleValue')
for prop,line in [('BorderBlockEndStyle',3950),('BorderBlockStartStyle',4061),('BorderInlineEndStyle',4718),('BorderInlineStartStyle',4829)]:
    locations[prop]=('out/Min/gen/third_party/blink/renderer/core/css/properties/longhands.cc',line,'SurrogateFor physical border-style grammar')
short_supported={'Margin','Padding','BorderWidth','BorderStyle','BorderColor','Inset','ScrollMargin','ScrollPadding','Gap','Overflow','Outline','Container','MarginBlock','MarginInline','PaddingBlock','PaddingInline','InsetBlock','InsetInline','WhiteSpace','FlexFlow','Flex','Border','BorderTop','BorderRight','BorderBottom','BorderLeft','Background','BorderRadius'}
short_custom=CORE/'css/properties/shorthands/shorthands_custom.cc'
for (prop,),body,line in functions(short_custom.read_text(),r'bool (\w+)::ParseShorthand\([^)]*\) const \{'):
    locations[prop]=(str(short_custom.relative_to(SRC)),line,prop+'::ParseShorthand')
    if prop in short_supported: manual.add(prop)
# Compound transform consumers must not be mislabeled as their first `none`
# ConsumeIdent branch. Keep the actual typed source consumer visible.
for prop,consumer in {
    'ScrollbarColor': 'ScrollbarColor::ParseSingleValue / ConsumeColor pair',
    'ScrollbarGutter': 'ScrollbarGutter::ParseSingleValue / stable both-edges',
    'ScrollSnapAlign': 'ScrollSnapAlign::ParseSingleValue / block-inline identifier pair',
    'ScrollSnapType': 'ScrollSnapType::ParseSingleValue / axis-strictness identifier pair',
    'VerticalAlign': 'VerticalAlign::ParseSingleValue / ConsumeIdentRange / ConsumeLengthOrPercent',
    'TabSize': 'TabSize::ParseSingleValue / ConsumeNumber then ConsumeLength',
    'WebkitLineClamp': 'WebkitLineClamp::ParseSingleValue / none or ConsumePositiveInteger',
    'AlternativeWebkitLineClampLonghand': 'AlternativeWebkitLineClampLonghand::ParseSingleValue / none or ConsumePositiveInteger',
    'LineClamp': 'LineClamp::ParseSingleValue / ConsumePositiveInteger auto block-ellipsis legacy list',
    'MaxLines': 'MaxLines::ParseSingleValue / ConsumePositiveInteger auto pair',
    'AnchorName': 'AnchorName::ParseSingleValue / none or ConsumeDashedIdent comma list',
    'AnchorScope': 'ConsumeNameScope / CSSScopedKeywordValue all / ConsumeDashedIdent comma list',
    'PositionAnchor': 'PositionAnchor::ParseSingleValue / auto-none-normal or ConsumeDashedIdent',
    'PositionArea': 'PositionArea::ParseSingleValue / none or ConsumePositionArea compatible canonical pair',
    'PositionVisibility': 'PositionVisibility::ParseSingleValue / always or anchors-visible no-overflow list',
    'PositionTryFallbacks': 'ConsumePositionTryFallbacks / ConsumeDashedIdentOrTactic or ConsumePositionArea',
    'TextEmphasisStyle': 'TextEmphasisStyle::ParseSingleValue / none-string-fill-shape canonical list',
    'TextEmphasisPosition': 'TextEmphasisPosition::ParseSingleValue / over-under optional left-right canonical list',
    'TextEmphasis': 'ConsumeShorthandGreedilyViaLonghands / TextEmphasisStyle and existing ConsumeColor',
    'HyphenateCharacter': 'HyphenateCharacter::ParseSingleValue / auto or ConsumeString',
    'HyphenateLimitChars': 'ConsumeHyphenateLimitChars / positive integer-number calc or auto 1-3 list',
    'RubyPosition': 'RubyPosition::ParseSingleValue / over-under; alternate/inter-character rejected',
    'RubyOverhang': 'RubyOverhang::ParseSingleValue / none alias to spaces, auto',
    'TextSizeAdjust': 'TextSizeAdjust::ParseSingleValue / auto-none or nonnegative ConsumePercent',
    'TextDecorationSkipSpaces': 'ConsumeTextDecorationSkipSpaces / none-all-start-end canonical list (internal)',
    'TextBoxEdge': 'ConsumeTextBoxEdge / auto or over-under canonical identifier-list',
    'TextBox': 'TextBox::ParseShorthand / normal or trim-edge; omitted trim-both and auto edge',
    'TextFit': 'ConsumeTextFit / type-target-nonnegative percentage canonical list',
    'TextSpacing': 'TextSpacing::ParseShorthand / none or autospace-spacing-trim-normal combinations (internal)',
    'TextDecorationInset': 'TextDecorationInset::ParseSingleValue / auto or length-percent drop-identical pair (internal)',
    'WebkitTextDecorationsInEffect': 'ConsumeTextDecorationLine / existing canonical decoration-line consumer',
    'ColumnRuleColor': 'ConsumeGapDecorationPropertyList / comma-list of existing ConsumeColor (repeat typed Unsupported)',
    'ColumnRuleStyle': 'ConsumeGapDecorationPropertyList / comma-list of existing border-style keywords (repeat typed Unsupported)',
    'ColumnRuleWidth': 'ConsumeGapDecorationPropertyList / comma-list of ConsumeLineWidth with unitless quirk forbidden (repeat typed Unsupported)',
    'ColumnRule': 'ConsumeGapDecorationsRuleShorthand / comma-segment greedy width-style-color and explicit source defaults',
    'RowRuleColor': 'ConsumeGapDecorationPropertyList / reuse column-rule typed color list consumer',
    'RowRuleStyle': 'ConsumeGapDecorationPropertyList / reuse column-rule typed border-style list consumer',
    'RowRuleWidth': 'ConsumeGapDecorationPropertyList / reuse column-rule typed line-width list consumer',
    'RowRule': 'ConsumeGapDecorationsRuleShorthand / existing lists into row width-style-color with source defaults',
    'RuleColor': 'ConsumeGapDecorationPropertyList / one color list shared by column and row',
    'RuleStyle': 'ConsumeGapDecorationPropertyList / one style list shared by column and row',
    'RuleWidth': 'ConsumeGapDecorationPropertyList / one width list shared by column and row',
    'Rule': 'ConsumeGapDecorationsRuleShorthand / same width-style-color lists into column then row; no inset reset',
    **{prop: 'ConsumeGapDecorationsRuleInsetStartEndShorthand / overlap-join or signed length-percent into native Length' for prop in rule_inset_cluster if prop.endswith(('CapStart','CapEnd','JunctionStart','JunctionEnd'))},
    **{prop: 'ConsumeGapDecorationsRuleInsetShorthand / cap pair, optional slash junction pair and source repetition defaults' for prop in ('ColumnRuleInset','RowRuleInset','RuleInset')},
    **{prop: 'ConsumeGapDecorationsRuleInsetCapJunctionShorthand / start and optional end, source provenance preserved' for prop in rule_inset_cluster if prop.endswith(('InsetCap','InsetJunction'))},
    **{prop: 'ConsumeGapDecorationsRuleInsetStartEndShorthand / one shared value for cap and junction on the selected end' for prop in rule_inset_cluster if prop.endswith(('InsetStart','InsetEnd'))},
    'FontSynthesis': 'FontSynthesis::ParseShorthand / complete source weight-style-small-caps reset (no position property in checkout)',
    'FontSynthesisWeight': 'source keyword grammar / auto-none native FontDescription bitfield',
    'FontSynthesisStyle': 'source keyword grammar / auto-none native FontDescription bitfield',
    'FontSynthesisSmallCaps': 'source keyword grammar / auto-none native FontDescription bitfield',
    'MathDepth': 'ConsumeMathDepth / auto-add, unrestricted integer math or typed add(integer)',
    'WebkitBoxOrdinalGroup': 'ConsumePositiveInteger / positive integer math and native unsigned clamp',
    'InternalVisitedFill': 'ConsumeSVGPaint / existing typed ordinary paint consumer into separate visited native slot',
    'InternalVisitedStroke': 'ConsumeSVGPaint / existing typed ordinary paint consumer into separate visited native slot',
    'WebkitBoxReflect': 'ConsumeReflect / typed direction-offset-mask; reuse ConsumeWebkitBorderImage; bare none Invalid in source parser',
    'WebkitColumnBreakBefore': 'ConsumeFromColumnBreakBetween / always to column, auto-avoid',
    'WebkitColumnBreakAfter': 'ConsumeFromColumnBreakBetween / always to column, auto-avoid',
    'WebkitColumnBreakInside': 'ConsumeFromColumnOrPageBreakInside / auto-avoid',
    'BorderImageSlice': 'ConsumeBorderImageSlice / Complete4Sides / fill',
    'BorderImageWidth': 'ConsumeBorderImageWidth / number then standard-mode length-percent-auto',
    'BorderImageOutset': 'ConsumeBorderImageOutset / number then standard-mode length',
    'BorderImageRepeat': 'ConsumeBorderImageRepeat / horizontal-vertical CSSValuePair',
    'WebkitBorderImage': 'ConsumeWebkitBorderImage / ConsumeBorderImageComponents / default fill',
    'TouchAction': 'TouchAction::ParseSingleValue / ConsumePan grouped canonical axes',
    'WillChange': 'WillChange::ParseSingleValue / comma-separated ident tokens / ConsumeCustomIdent',
    'MarginTrim': 'MarginTrim::ParseSingleValue / block sides canonicalization',
    'Appearance': 'CSSParser::ParseValue resolved-id alias normalization / Appearance::ParseSingleValue / CSSParserFastPaths::IsValidKeywordPropertyAndValue',
    'GridTemplateAreas': 'GridTemplateAreas::ParseSingleValue / ParseGridTemplateAreasRow',
    'ListStyleType': 'ListStyleType::ParseSingleValue / ConsumeCounterStyleName / ConsumeString',
    'Quotes': 'Quotes::ParseSingleValue / ConsumeString',
    'Perspective': 'Perspective::ParseSingleValue / ConsumeLength / alias ConsumeNumber',
    'Rotate': 'Rotate::ParseSingleValue / ConsumeAxis / ConsumeAngle',
    'Scale': 'Scale::ParseSingleValue / ConsumeNumberOrPercent',
    'Translate': 'Translate::ParseSingleValue / ConsumeLengthOrPercent / ConsumeLength',
    'ClipPath': 'ClipPath::ParseSingleValue / ConsumeBasicShape / ConsumeGeometryBox / ConsumeUrl',
    'BorderShape': 'BorderShape::ParseSingleValue / ConsumeBasicShapeAndGeometryBox',
    'Cursor': 'Cursor::ParseSingleValue / keyword branch / ConsumeImage',
    'ShapeOutside': 'ShapeOutside::ParseSingleValue / ConsumeImageOrNone / ConsumeBasicShape / ConsumeShapeBox',
    'AccentColor': 'AccentColor::ParseSingleValue / auto or ConsumeColor',
    'CaretColor': 'CaretColor::ParseSingleValue / stable single auto or ConsumeColor',
    'ColorScheme': 'ColorScheme::ParseSingleValue / light-dark-only-custom-ident list',
    'InternalVisitedCaretColor': 'CaretColor::ParseSingleValue delegate / stable single auto or ConsumeColor',
    'InternalVisitedOutlineColor': 'OutlineColor::ParseSingleValue delegate / focus-ring or ConsumeColor',
}.items():
    file,line,_=locations[prop]
    locations[prop]=(file,line,consumer)
# The outline keyword consumer is defined here, not by the field enum list.
locations['OutlineStyle']=('third_party/blink/renderer/core/css/parser/css_parser_fast_paths.cc',1288,'IsValidKeywordPropertyAndValue')
locations['Continue']=('third_party/blink/renderer/core/css/css_properties.json5',7566,'generated keyword grammar / CSSLineClampAsShorthand Exposure')
out += ['pub fn ParserSourceFor(id: CSSPropertyID) -> (&\'static str, u32, &\'static str) { match id {']
ledger_rows=['property\tcoverage\tsource\tline\tconsumer\tpending']
for prop,(file,line,consumer) in sorted(locations.items()):
    covered=prop in seen or prop in manual
    out.append(f'CSSPropertyID::k{prop} => ("{file}", {line}, "{consumer}"),')
    pending='functions/math/var and context-dependent extensions' if covered else 'whole property consumer'
    coverage='literal branches' if covered else 'unsupported'
    if prop in complete:
        coverage='stable consumer complete'
        pending='alternate DisableAnchorCenterOnAlignJustifyItems runtime flag' if prop in {'AlignItems','JustifyItems','PlaceItems'} else 'alternate FlexWrapBalance runtime flag' if prop in {'FlexWrap','FlexFlow'} else 'none'
        if prop == 'JustifyItems': pending += '; use counters'
    if prop in initial_scope_cluster:
        coverage='typed consumer branches'; pending='shared CSSMath unsupported functions/typed arithmetic; native DCHECK size>=1 mathematical branch and explicit out-of-int-range sink conversion boundary'
        if prop == 'ScrollMarkerGroup':
            coverage='stable consumer complete'
            pending='CSSPseudoScrollMarkers stable enabled (runtime JSON:1858-1860; depends_on PseudoElementsFocusable stable:4914-4915); alternate disabled parser/Exposure branch; CSSScrollMarkerGroupModes experimental:1923-1924 is NOT checked by this parser'
        if prop == 'TriggerScope':
            coverage='stable literal consumer branches'
            pending='AnimationTrigger stable enabled (runtime JSON:628-630); alternate disabled Exposure branch; CSSIdentFunction test branch stable disabled:1658-1659; shared AnchorScope native ScopedCSSNameList/StyleNameScope document-root null scope mapped; shadow TreeScope population and HasTreeScopedReference owner partial'
    if prop in timeline_cluster:
        coverage='stable consumer complete'; pending='none'
        if prop in {'ScrollTimelineName','ViewTimelineName','ScrollTimeline','ViewTimeline','TimelineScope'}:
            coverage='stable literal consumer branches'; pending='CSSIdentFunction test runtime branch (stable disabled); definition names use native unscoped AtomicString; shadow timeline consumption/HasTreeScopedReference owner outside this batch'
        if prop == 'TimelineScope': pending += '; CSSTimelineScopeAll experimental runtime branch (stable disabled)'
        if prop in {'ViewTimelineInset','ViewTimeline'}:
            coverage='typed consumer branches'
            pending=('' if pending == 'none' else pending+'; ')+'shared CSSMath unsupported functions/typed arithmetic; font-metric/container-relative length conversion; standardized-browser-zoom parent re-conversion owner (stable enabled)'
    if prop in border_image_cluster:
        coverage='typed consumer branches'
        pending='shared CSSMath unsupported functions/typed arithmetic'
        if prop == 'BorderImageRepeat': coverage='stable consumer complete'; pending='none'
        if prop in {'BorderImageSource','BorderImage','WebkitBorderImage'}:
            pending='generated/image-set/light-dark image subtypes; URL context/request modifiers/referrer; shared CSSMath unsupported functions/typed arithmetic and extended gradient/color collaborators'
    if prop in grid_lanes_cluster:
        coverage='runtime-gated typed consumer'; pending='CSSGridLanesLayout experimental stable-disabled Exposure; real internal typed/native branches translated'
        if prop=='GridLanes': pending += '; shared track-list bracketed/line names/repeat/minmax/fit-content/subgrid; shared CSSMath/length/changed-zoom contexts'
    if prop in rule_behavior_cluster:
        coverage='stable consumer complete'; pending='none'
    if prop in rule_inset_cluster:
        coverage='typed consumer branches'; pending='shared CSSMath unsupported functions/typed arithmetic; real font-metric/container-relative length conversion; changed-zoom inheritance requires standardized browser zoom owner'
    if prop in render_delay_cluster:
        coverage='typed consumer branches'; pending='extended shared CSSMath functions/typed arithmetic'
        if prop=='DynamicRangeLimit': pending += '; CSSParserLocalContext::FunctionLocalContext adapter'
        if prop=='FlowTolerance': coverage='runtime-gated typed consumer'; pending='CSSGridLanesLayout experimental stable-disabled Exposure; internal typed consumer/native apply translated; shared CSSMath/length metrics/container/changed-zoom reconversion collaborators'
    if prop in timeline_trigger_cluster:
        coverage='typed consumer branches'; pending='shared CSSMath unsupported functions/typed arithmetic; length metric/container/changed-zoom contexts'
        if prop == 'TimelineTriggerName': pending='CSSIdentFunction test runtime branch (stable disabled); shadow CSSCustomIdentValue TreeScope population/HasTreeScopedReference owner'
        if prop == 'TimelineTriggerSource': pending='CSSScrollValue/CSSViewValue production owner; CSSIdentFunction test runtime branch (stable disabled); timeline source names retain native unscoped AtomicString'
        if prop == 'TimelineTrigger': pending += '; CSSIdentFunction test runtime branch (stable disabled); shadow trigger-name TreeScope/HasTreeScopedReference owner; CSSScrollValue/CSSViewValue production owner'
    if prop in view_transition_cluster:
        coverage='stable literal consumer branches'; pending='CSSIdentFunction test runtime branch (stable disabled); shadow CSSCustomIdentValue TreeScope population and HasTreeScopedReference owner'
        if prop == 'ViewTransitionName': pending += '; CSSViewTransitionAutoName experimental runtime branch (stable disabled); match-element requires real Document TreeScope binding'
        if prop == 'ViewTransitionGroup': pending += '; contextual nearest/contain/group hierarchy resolution belongs to view-transition runtime, outside style conversion'
    if prop in motion_cluster:
        coverage='typed consumer branches'; pending='shared CSSMath unsupported functions/typed arithmetic'
        if prop in {'OffsetPath','Offset'}:
            pending += '; BasicShape/StylePath/StyleShape vector Path owner; CSSURIValue/SVG resource owner; CSSOffsetInEffect document use counter'
        if prop == 'OffsetPosition': pending += '; CSSOffsetInEffect document use counter'
    if prop in mask_cluster:
        coverage='typed consumer branches'; pending='shared CSSMath unsupported functions/typed arithmetic'
        if prop in {'MaskClip','MaskOrigin','MaskComposite','MaskMode','MaskRepeat','WebkitMaskBoxImageRepeat'}:
            coverage='stable consumer complete'; pending='none'
        if prop in {'MaskImage','Mask','WebkitMaskBoxImageSource','WebkitMaskBoxImage'}:
            pending='generated/image-set/light-dark image subtypes; URL context/request modifiers/referrer; extended gradient/color collaborators; shared CSSMath unsupported functions/typed arithmetic'
        if prop in {'WebkitMaskPositionX','WebkitMaskPositionY','Mask'}:
            pending += '; source position use counters (document owner)'
    if prop in interaction_cluster:
        coverage='stable consumer complete'; pending='none'
        if prop == 'Appearance':
            coverage='typed consumer branches'
            pending='document CountKeywordOnlyPropertyUsage/WarnInvalidKeywordPropertyUsage and slider-vertical deprecation counters; alternate AppearanceBase experimental runtime flag (stable disabled)'
        if prop in {'HangingPunctuation','MarginTrim'}:
            coverage='runtime-gated typed consumer'
            pending=('CSSHangingPunctuation test' if prop == 'HangingPunctuation' else 'MarginTrim experimental') + ' runtime flag disabled at stable defaults; host ExecutionContext exposure owner'
    if prop in {'GridTemplateAreas','GridAutoFlow'}:
        coverage='stable consumer complete'; pending='none'
    if prop in {'GridTemplate','Grid','GridTemplateRows','GridTemplateColumns','GridAutoRows','GridAutoColumns'}:
        coverage='typed consumer branches'
        pending='CSSBracketedValueList/line names; repeat()/minmax()/fit-content() typed values; subgrid; shared CSSMath unsupported functions/typed arithmetic; GridLanes experimental runtime branches (stable default)'
    if prop in animation_pending:
        pending=animation_pending[prop]
        if prop in {'Animation','AnimationDuration','AnimationDelay','AnimationIterationCount',
                    'AnimationName','AnimationTimingFunction','TransitionDuration',
                    'TransitionDelay','TransitionTimingFunction'}:
            coverage='typed consumer branches'
    if prop in position_pending: pending=position_pending[prop]
    if prop in {'FontFeatureSettings', 'FontVariationSettings', 'FontStretch'}: pending='CSSMathFunctionValue'
    if prop == 'LineHeight':
        coverage='typed consumer branches'
        pending='shared CSSMath unsupported function/typed-arithmetic branches; font-metric/container-relative length conversion; standardized text/zoom adapter'
    if prop in font_cluster:
        pending='none'
        if prop in {'Font','FontSizeAdjust'}:
            coverage='typed consumer branches'
            pending={'Font':'CSSPendingSystemFontValue/platform system font; explicit oblique angle; shared CSSMath unsupported branches; alternate CSSFontSizeAdjust/FontLanguageOverride runtime flags',
                     'FontVariant':'ConsumeCustomIdent ident() runtime option',
                     'FontVariantAlternates':'ConsumeCustomIdent ident() runtime option',
                     'FontSizeAdjust':'shared CSSMath unsupported function/typed-arithmetic branches; alternate CSSFontSizeAdjust runtime flag'}[prop]
        if prop in {'FontVariant','FontVariantAlternates'}: pending='alternate CSSIdentFunction runtime flag (test; stable disabled)'
        if prop == 'FontLanguageOverride': pending='alternate FontLanguageOverride runtime flag'
    if prop in effects_cluster:
        coverage='typed consumer branches'
        pending={
            'Filter':'SVG URL request/referrer and resource owner/reuse; shared CSSMath unsupported branches; drop-shadow advanced color/relative-unit collaborators',
            'BackdropFilter':'SVG URL request/referrer and resource owner/reuse; shared CSSMath unsupported branches; drop-shadow advanced color/relative-unit collaborators',
            'ClipPath':'circle/ellipse/inset native Path/equality; rect/xywh/path/shape typed/native collaborators; SVG URL resource owner; shared CSSMath unsupported branches; use counters; alternate BasicShapeCornerRadius runtime flag (experimental; stable disabled)',
            'ShapeOutside':'circle/ellipse/inset native Path/equality; rect/xywh/path/shape typed/native collaborators; generated/image-set and URL StyleImage owner; shared CSSMath unsupported branches; alternate CSSShapeOutsidePathAndShapeSupport/CSSShapeOutsideRectAndXywhSupport/CSSPolygonRounding flags (stable enabled); BasicShapeCornerRadius (experimental; stable disabled)',
            'Cursor':'CSSCursorImageValue/StyleImage owner and image/hotspot branches; prefixed/quirks use counters and was_quirky payload',
            'ShapeImageThreshold':'shared CSSMath unsupported function/typed-arithmetic branches',
        }[prop]
        if prop == 'ClipPath': pending += '; alternate CSSPolygonRounding runtime flag (stable enabled)'
        if prop in {'Filter','BackdropFilter','ClipPath','ShapeOutside'}: pending += '; standardized cross-zoom reapplication and relative-unit contexts'
        if prop in {'ClipPath','ShapeOutside'}: pending += '; native BasicShapePolygon GetPath collaborator (typed native data mapped)'

    if prop in color_ui_cluster:
        coverage='typed consumer branches'
        pending='shared ConsumeColor advanced/relative/math/mix/light-dark/alpha/contrast functional syntax; ColorParserContext OnlyAbsoluteColors branch; system/accent/provider/text-link contexts; native Color::ResolveNonFiniteValues'
        if prop == 'ColorScheme':
            coverage='stable consumer complete'
            pending='alternate CSSIdentFunction runtime flag (test; stable disabled); real page/meta color-scheme and force-dark host publication adapter; root use counter'
        if prop in {'CaretColor','InternalVisitedCaretColor'}: pending += '; alternate CSSCaretColorWithOptionalSecondValue runtime flag (experimental; stable disabled)'
        if prop.startswith('InternalVisited'): pending += '; real visited-history/matching/cascade adapter (native ordinary/visited slots mapped)'
    if prop in {'Outline', 'OutlineColor'}: pending='ConsumeColor functions beyond rgb/rgba; SystemAccentColorAllowed parser context' + ('; ConsumeLineWidth CSSMathFunctionValue' if prop == 'Outline' else '')
    if prop in {'OutlineWidth', 'OutlineOffset', 'ZIndex'}: pending='CSSMathFunctionValue'
    if prop in {'ContainerName', 'Container'}: pending='CSSIdentFunction runtime option; name TreeScope population'
    if prop == 'ContainerType': pending='scroll-state use counter'
    if prop in {'BoxShadow', 'TextShadow'}: pending='ConsumeLength CSSMathFunctionValue; ConsumeColor functions beyond rgb/rgba; SystemAccentColorAllowed parser context'
    if prop == 'BackgroundImage': pending='ConsumeAngle CSSMathFunctionValue; ConsumeColorInterpolationSpace; radial/conic/other generated image subtypes; URL request modifiers/referrer context; ConsumeColor functions beyond rgb/rgba'
    if prop in scroll_properties | scroll_sides | scroll_shorthands:
        coverage='typed consumer branches'
        pending='shared CSSMath unsupported functions and real relative-unit contexts'
        if prop in {'OverscrollBehaviorX','OverscrollBehaviorY','OverscrollBehavior','ScrollbarGutter','ScrollSnapAlign'}:
            coverage='stable consumer complete'; pending='none'
        if prop == 'ScrollSnapType': pending='alternate CSSScrollSnapTypePair runtime flag/native pair-axis branch'
        if prop == 'ScrollbarColor': pending='ConsumeColor advanced/system-color and provider context collaborators'
    if prop in line_stable:
        coverage='stable consumer complete';pending='none'
        if prop in {'VerticalAlign','TabSize','WebkitLineClamp'}:
            coverage='typed consumer branches';pending='shared CSSMath unsupported functions/typed arithmetic' + ('; real relative-unit contexts' if prop != 'WebkitLineClamp' else '')
    if prop in line_runtime:
        coverage='runtime-gated typed consumer'
        pending='CSSLineClamp experimental / CSSLineClampAsShorthand test runtime flags: disabled at stable defaults; host ExecutionContext exposure/alternate-property selection; shared CSSMath unsupported functions/typed arithmetic'
    if prop in anchor_cluster:
        coverage='typed consumer branches';pending='CSSIdentFunction test runtime branch (stable disabled); document-root scope mapped, shadow/non-null TreeScope population remains owner-dependent'
        if prop in {'PositionArea','PositionVisibility','PositionTryOrder'}:
            coverage='stable consumer complete';pending='none'
    if prop in column_rule_cluster | row_rule_cluster:
        coverage='typed consumer branches';pending='CSSRepeatValue / gap-decoration repeat() collaborator'
        if prop.startswith('WebkitColumnBreak'):
            coverage='stable consumer complete';pending='none'
        if prop in {'ColumnRuleColor','ColumnRule','RowRuleColor','RowRule','RuleColor','Rule'}:
            pending += '; shared ConsumeColor advanced/system/provider context; native InsideLink honored when supplied, document link/visited owner remains partial'
        if prop in {'ColumnRuleWidth','ColumnRule','RowRuleWidth','RowRule','RuleWidth','Rule'}:
            pending += '; shared CSSMath unsupported functions/typed arithmetic; real relative-unit conversion contexts; changed-zoom inheritance requires standardized browser zoom owner'
    if prop in stable_misc_cluster:
        coverage='stable consumer complete';pending='none'
        if prop in {'MathDepth','WebkitBoxOrdinalGroup'}:
            coverage='typed consumer branches';pending='shared CSSMath unsupported functions/typed arithmetic and real context-dependent math resolver'
    if prop in palette_internal_cluster:
        coverage='stable consumer complete';pending='UA-only exposure enforced before CSS-wide and variable handling' if prop != 'FontPalette' else 'none'
        if prop == 'FontPalette':
            coverage='typed consumer branches';pending='ConsumePaletteMixFunction/CSSPaletteMixValue; CSSIdentFunction stable-disabled branch; real TreeScope and @font-palette-values/font-family provider lookup; native request owner/name retained without fabricated definitions'
    if prop in reflection_visited_cluster:
        coverage='typed consumer branches'
        if prop=='WebkitBoxReflect':
            pending='real fetched URL image binding; shared image/gradient and CSSMath/relative-unit contexts; standardized changed-zoom inheritance owner'
        else:
            pending='real history/visited cascade owner; document StyleSVGResource reference binding; shared advanced/system color contexts; context paint use-counter owner'
    if prop in text_box_cluster:
        coverage='stable consumer complete';pending='none'
        if prop == 'TextFit':
            coverage='typed consumer branches';pending='shared CSSMath unsupported functions/typed arithmetic; CssTextFitReshaping remains stable-default disabled in native Method'
        if prop == 'TextDecorationInset':
            coverage='runtime-gated typed consumer';pending='CSSTextDecorationInset experimental stable-disabled Exposure; shared CSSMath and relative-unit conversion; standardized-browser-zoom parent re-conversion owner'
        if prop == 'TextSpacing':
            coverage='runtime-gated typed consumer';pending='CSSTextSpacing test-only stable-disabled Exposure; internal shorthand and real native longhand applications translated'
    if prop in typography_cluster:
        coverage='stable consumer complete';pending='none'
        if prop in {'HyphenateLimitChars','TextSizeAdjust'}:
            coverage='typed consumer branches';pending='shared CSSMath unsupported functions/typed arithmetic'
        if prop in {'TextEmphasis','TextEmphasisColor'}:
            coverage='typed consumer branches';pending='shared ConsumeColor advanced/system/provider/context collaborators'
        if prop == 'RubyPosition':
            coverage='typed consumer branches';pending='context Count use counters for rejected alternate/inter-character keywords'
        if prop == 'TextEmphasisPosition':
            pending='TextEmphasisPositionAuto experimental runtime branch: stable disabled; existing runtime flag preserved'
        if prop == 'TextDecorationSkipSpaces':
            coverage='runtime-gated typed consumer';pending='CSSTextDecorationSkipSpaces experimental runtime flag: stable disabled; internal consumer/native apply translated, real ExecutionContext override absent'
    if prop in list_counter_cluster:
        coverage='typed consumer branches'
        pending='shared CSSMath unsupported functions; ident() collaborator'
        if prop == 'CounterReset': pending += '; alternate CSSCounterResetReversed runtime flag'
        if prop in {'Quotes', 'ListStylePosition'}: coverage='stable consumer complete'; pending='none'
        if prop == 'ListStyleType': pending='TreeScope population for overridable/custom counter-style names; alternate symbols() runtime flag/native symbols collaborator'
        if prop in {'ListStyleImage', 'ListStyle'}: pending='image generated/image-set subtypes and URL context; counter-style TreeScope and symbols() collaborators' if prop == 'ListStyle' else 'image generated/image-set subtypes; URL context/request modifiers/referrer'

    if prop == 'TextDecorationColor':
        coverage='typed consumer branches'
        pending='ConsumeColor advanced/system-color collaborators'
    if prop in text_cluster:
        coverage='stable consumer complete'
        pending='alternate TextOverflowString runtime flag' if prop == 'TextOverflow' else 'alternate CSSTextTransformFullWidth/FullSizeKana/MultiKeyword runtime flags' if prop == 'TextTransform' else 'none'
        if prop == 'TextAlign': pending='alternate CSSTextAlignMatchParent runtime flag; -internal-center UA only'
        if prop == 'TextDecoration':
            coverage='typed consumer branches'
            pending='ConsumeColor advanced/system-color collaborators'
    if prop in svg_properties:
        coverage='typed consumer branches' if prop in {'Fill','Stroke'} else 'stable consumer complete'
        pending='URL request modifiers/referrer context; ConsumeColor advanced/system-color collaborators' if prop in {'Fill','Stroke'} else 'none'
    if prop in svg_presentation:
        coverage='stable consumer complete'; pending='none'
        if prop == 'D':
            coverage='typed none branch / typed Unsupported path owner'
            pending='ConsumePathStringArg BuildByteStreamFromString/SVGPathStringSource/SVGPathByteStreamBuilder/CSSPathValue owner; native foundation Path is uninhabited'
        if prop in {'Marker','MarkerStart','MarkerMid','MarkerEnd'}:
            coverage='typed consumer branches'
            pending='ConsumeUrl CSSURLRequestModifiers stable enabled/request modifiers/referrer/Document URL context; StyleSVGResource adapter at Apply'
        if prop in {'BaselineShift','StrokeMiterlimit','WebkitTextStrokeWidth','WebkitTextStroke'}:
            coverage='typed consumer branches'
            pending='shared CSSMath unsupported functions/typed arithmetic'
            if prop != 'StrokeMiterlimit': pending += '; font-metric/container-relative length conversion; standardized browser zoom parent re-conversion owner (stable enabled)'
        if prop in {'WebkitTextStrokeColor','WebkitTextStroke'}:
            coverage='typed consumer branches'
            pending=('' if pending == 'none' else pending + '; ') + 'ConsumeColor advanced/system/provider context and NonFiniteValues; CSSAlphaColorFunction/CSSContrastColor stable enabled'
    if prop in viewport_cluster:
        coverage='typed consumer branches'; pending='shared CSSMath unsupported functions/typed arithmetic; real font-metric/container-relative length conversion'
        if prop == 'Zoom':
            pending='shared CSSMath unsupported functions/typed arithmetic; effective-zoom changes require real production FontBuilderBackend/dirty/update-font phase and document/frame conversion hooks (typed Unsupported)'
        if prop == 'Clip': pending += '; standardized-browser-zoom parent re-conversion owner (stable enabled)'
        if prop == 'Size': pending += '; @page ConsumeAtRuleContents entry point/page style cascade/pagination owner is typed Unsupported'
        if prop == 'Page':
            coverage='stable literal consumer branches'
            pending='CSSIdentFunction test runtime branch (stable disabled); actual native field is unscoped AtomicString, document-root name mapped; shadow/TreeScope population and paginated page-name selection owner remain pending'
        if prop == 'WebkitLocale':
            coverage='stable consumer complete'
            pending='native LayoutLocale::GetShared handle/FontDescription staging mapped; existing native cache is global rather than Chromium per-thread, ICU script collaborator partial; full production FontBuilderBackend font-selector/metrics lifecycle and shadow/document locale context owner remain pending'
        if prop == 'ObjectViewBox':
            coverage='typed none branch / typed Unsupported shape owner'
            pending='actual BasicShapeInset/Rect/XYWH CSSValue/native Path owner; standardized-browser-zoom parent re-conversion owner (stable enabled)'
    if prop in border_colors | {'BorderBlockColor','BorderInlineColor'}:
        pending='ConsumeColor functions beyond rgb/rgba; system color provider/context'
    if prop in border_radii | border_widths | {'BorderSpacing','WebkitBorderHorizontalSpacing','WebkitBorderVerticalSpacing','BorderBlockWidth','BorderInlineWidth'}:
        pending='font-metric/container-relative length conversion; standardized browser zoom inheritance adapter'
        coverage='typed consumer branches'
    if prop in border_styles | {'BorderBlockStyle','BorderInlineStyle'}: coverage='stable consumer complete'; pending='none'
    if prop in logical_border_shorthands:
        coverage='typed shorthand expansion branches'
        pending='reuses existing border color/style/width consumers and native physical mapping; alternate shared greedy use_initial_value_function branch (selected default false); advanced/system/provider color collaborators; shared CSSMath unsupported function/typed-arithmetic branches; font-metric/container-relative length conversion; standardized browser zoom inheritance adapter'
    if prop in layout_misc_cluster:
        coverage='stable consumer complete'
        pending='contain-style use counter' if prop == 'Contain' else 'shared CSSMath unsupported function/typed-arithmetic branches'
        if prop != 'Contain': coverage='typed consumer branches'
        if prop in {'ColumnWidth','ColumnHeight','Columns','ContainIntrinsicWidth','ContainIntrinsicHeight',
                    'ContainIntrinsicInlineSize','ContainIntrinsicBlockSize','ContainIntrinsicSize'}:
            coverage='typed consumer branches'
            pending='shared CSSMath unsupported function/typed-arithmetic branches; font-metric/container-relative conversion; standardized browser zoom inheritance adapter'
    if prop in transform_cluster:
        coverage='typed consumer branches'
        pending='extended CSSMath functions (trig/round/mod/rem/pow/sqrt/hypot/log/exp/anchor/calc-size/progress/random); typed exponent arithmetic; use counters'
    if prop == 'Content':
        coverage='typed consumer branches'
        pending='non-linear generated/image-set/light-dark images; anonymous symbols CounterStyle and TreeScope population; attr uses shared substitution'
    if prop == 'BorderShape':
        coverage='typed consumer branches'
        pending='circle/ellipse/inset/rect/xywh/path/shape shared typed/native BasicShape owners; native polygon GetPath; computed-value serialization; cross-zoom inheritance reapplication; relative-unit conversion contexts'
    if prop.startswith('Corner'):
        if prop.endswith('Shape'):
            coverage='typed consumer branches'
            pending='shared CSSMath unsupported functions/typed arithmetic and contextual number resolution; computed-value serialization'
        else:
            coverage='runtime-gated typed consumer'
            pending='CSSCornersShorthand experimental (stable disabled): enabled ExecutionContext exposure, matching-shorthand index capacity and CSSOM serialization; shared CSSMath and radius length contexts'
    ledger_rows.append(f'{prop}\t{coverage}\t{file}\t{line}\t{consumer}\t{pending}')
out += ['_ => ("third_party/blink/renderer/core/css/parser/css_property_parser.cc", 129, "CSSProperty::ParseShorthand / generated ParseSingleValue"),','} }']
(HERE/'production_property_parser_ledger.tsv').write_text('\n'.join(ledger_rows)+'\n')
header=(GEN/'css/properties/longhands.h').read_text()
excluded=[]
for m in re.finditer(r'class CORE_EXPORT (\w+) final : public Longhand \{(.*?)\n \};',header,re.S):
    if 'bool IsAffectedByAll() const override { return false; }' in m[2]: excluded.append(m[1])
out += ['pub fn ExcludedFromAll(id: CSSPropertyID) -> bool { matches!(id, '+ '|'.join('CSSPropertyID::k'+prop for prop in excluded)+') }']
out += [
    '// Source-complete layered consumers translated from their ParserSourceFor entries.',
    '// css_parsing_utils.h:963 ConsumeCommaSeparatedList; css_parsing_utils.cc:5106-5319.',
    'pub(super) fn IsLayerConsumer(id: CSSPropertyID) -> bool { matches!(id,',
    'CSSPropertyID::kBackgroundAttachment | CSSPropertyID::kBackgroundBlendMode |',
    'CSSPropertyID::kBackgroundClip | CSSPropertyID::kBackgroundOrigin |',
    'CSSPropertyID::kBackgroundSize | CSSPropertyID::kBackgroundPositionX |',
    'CSSPropertyID::kBackgroundPositionY | CSSPropertyID::kWebkitMaskPositionX |',
    'CSSPropertyID::kWebkitMaskPositionY | CSSPropertyID::kMaskClip |',
    'CSSPropertyID::kMaskComposite | CSSPropertyID::kMaskMode |',
    'CSSPropertyID::kMaskOrigin | CSSPropertyID::kMaskSize) }',
]
(HERE/'src/parser/production_property_metadata.rs').write_text('\n'.join(out)+'\n')
print('Generated',len(seen),'longhand grammars and',len(shorthand),'shorthands')
