// qjs.c:107..118. Original factory is shared by workers and the main thread.
#[allow(non_snake_case)]
pub unsafe fn JS_NewCustomContext(rt: *mut JSRuntime) -> *mut JSContext {
    use crate::quickjs_libc::*;
    use quickjs::quickjs::*;
    let ctx = JS_NewContext(rt);
    if ctx.is_null() {
        return ctx;
    }
    js_init_module_std(ctx, c"std".as_ptr());
    js_init_module_os(ctx, c"os".as_ptr());
    ctx
}
// The original Makefile compiles repl.js with qjsc -s -c -m. This is that
// original bytecode, generated by the translated compiler (not a new REPL).
include!("qjs_repl_bytes.rs");

// qjs.c:454..568. Original initialization, execution, failure cleanup and
// benchmark branches. OS and FILE functions stay within the tools host.
pub unsafe fn run_bytes(argv: &[Vec<u8>]) -> Result<i32, ByteCliError> {
    use crate::quickjs_libc::*;
    use quickjs::quickjs::*;
    use std::{ffi::CString, ptr};
    let raw = parse_raw_options(argv)?;
    let mut options = raw.scalar;
    let mut trace_data = TraceMallocData::default();
    let rt = if options.trace_memory != 0 {
        js_trace_malloc_init(&mut trace_data);
        JS_NewRuntime2(
            &trace_mf(&trace_data),
            (&mut trace_data as *mut TraceMallocData).cast(),
        )
    } else {
        new_cli_runtime()
    };
    if rt.is_null() {
        return Err(ByteCliError::new("qjs: cannot allocate JS runtime\n", 2));
    }
    if options.memory_limit != 0 {
        JS_SetMemoryLimit(rt, options.memory_limit);
    }
    if options.stack_size != 0 {
        JS_SetMaxStackSize(rt, options.stack_size);
    }
    JS_SetStripInfo(rt, options.strip_flags);
    js_std_set_worker_new_context_func(Some(JS_NewCustomContext));
    js_std_init_handlers(rt);
    let ctx = JS_NewCustomContext(rt);
    if ctx.is_null() {
        return Err(ByteCliError::new("qjs: cannot allocate JS context\n", 2));
    }
    JS_SetModuleLoaderFunc2(
        rt,
        None,
        Some(js_module_loader),
        Some(js_module_check_attributes),
        ptr::null_mut(),
    );
    if options.dump_unhandled_promise_rejection != 0 {
        JS_SetHostPromiseRejectionTracker(
            rt,
            Some(js_std_promise_rejection_tracker),
            ptr::null_mut(),
        );
    }
    let mut failed = false;
    if options.empty_run == 0 {
        let strings = argv[options.optind..]
            .iter()
            .map(|s| CString::new(s.as_slice()).unwrap())
            .collect::<Vec<_>>();
        let mut args = strings
            .iter()
            .map(|s| s.as_ptr().cast_mut())
            .collect::<Vec<_>>();
        js_std_add_helpers(ctx, args.len() as i32, args.as_mut_ptr());
        if options.load_std != 0 {
            let source = c"import * as std from 'std';\nimport * as os from 'os';\nglobalThis.std = std;\nglobalThis.os = os;\n";
            eval_buf(
                ctx,
                source.as_ptr().cast(),
                source.to_bytes().len() as i32,
                c"<input>".as_ptr(),
                JS_EVAL_TYPE_MODULE,
            );
        }
        for name in &raw.include_list {
            let name = CString::new(name.as_slice()).unwrap();
            if eval_file_bytes(ctx, name.as_ptr(), 0, options.strict)? != 0 {
                failed = true;
                break;
            }
        }
        if !failed {
            if let Some(expr) = &raw.expr {
                let expr = CString::new(expr.as_slice()).unwrap();
                let flags = if options.module > 0 {
                    JS_EVAL_TYPE_MODULE
                } else {
                    JS_EVAL_TYPE_GLOBAL
                        | if options.strict != 0 {
                            JS_EVAL_FLAG_STRICT
                        } else {
                            0
                        }
                };
                failed = eval_buf(
                    ctx,
                    expr.as_ptr().cast(),
                    expr.to_bytes().len() as i32,
                    c"<cmdline>".as_ptr(),
                    flags,
                ) != 0;
            } else if options.optind >= argv.len() {
                options.interactive = 1;
            } else {
                let name = CString::new(argv[options.optind].as_slice()).unwrap();
                failed = eval_file_bytes(ctx, name.as_ptr(), options.module, options.strict)? != 0;
            }
        }
        if !failed {
            if options.interactive != 0 {
                JS_SetHostPromiseRejectionTracker(rt, None, ptr::null_mut());
                js_std_eval_binary(ctx, QJSC_REPL.as_ptr(), QJSC_REPL.len(), 0);
            }
            js_std_loop(ctx);
        }
    }
    if !failed && options.dump_memory != 0 {
        let mut stats = std::mem::zeroed();
        JS_ComputeMemoryUsage(rt, &mut stats);
        JS_DumpMemoryUsage(ptr::null_mut(), &stats, rt);
    }
    js_std_free_handlers(rt);
    JS_FreeContext(ctx);
    JS_FreeRuntime(rt);
    if failed {
        return Ok(1);
    }
    if options.empty_run != 0 && options.dump_memory != 0 {
        // Retain the original host clock_t and CLOCKS_PER_SEC boundary.
        #[cfg(unix)]
        type HostClock = libc::clock_t;
        #[cfg(windows)]
        type HostClock = i32;
        extern "C" {
            fn clock() -> HostClock;
        }
        let mut best = [0.0f64; 5];
        for i in 0..100 {
            let t0 = clock();
            let rt = new_cli_runtime();
            let t1 = clock();
            let ctx = JS_NewContext(rt);
            let t2 = clock();
            JS_FreeContext(ctx);
            let t3 = clock();
            JS_FreeRuntime(rt);
            let t4 = clock();
            let ticks = [t0, t1, t2, t3, t4];
            for j in (1..=4).rev() {
                let ms = 1000.0 * ticks[j].wrapping_sub(ticks[j - 1]) as f64 / crate::quickjs_libc::CLOCKS_PER_SEC as f64;
                if i == 0 || best[j] > ms {
                    best[j] = ms;
                }
            }
        }
        println!(
            "\nInstantiation times (ms): {:.3} = {:.3}+{:.3}+{:.3}+{:.3}",
            best[1] + best[2] + best[3] + best[4],
            best[1],
            best[2],
            best[3],
            best[4]
        );
    }
    Ok(0)
}
// Public String adapter preserves the existing embedding interface.
pub unsafe fn run(argv: &[String]) -> Result<i32, CliError> {
    let args = argv
        .iter()
        .map(|s| s.as_bytes().to_vec())
        .collect::<Vec<_>>();
    run_bytes(&args).map_err(|e| CliError {
        message: String::from_utf8_lossy(&e.message).into_owned(),
        help: e.help,
        exit: e.exit,
    })
}
pub fn main_entry() -> i32 {
    let argv = match crate::quickjs_libc::args_bytes() {
        Ok(argv) => argv,
        Err(error) => { eprintln!("qjs: {error}"); return 1; }
    };
    match unsafe { run_bytes(&argv) } {
        Ok(status) => status,
        Err(error) => {
            let _ = std::io::stderr().lock().write_all(&error.message);
            if error.help {
                print!("{}", help("2026-06-04"));
            }
            error.exit
        }
    }
}
