// quickjs-libc.c:3927..4010. All POSIX entries in source order.
#[cfg(target_os = "macos")] const OS_PLATFORM: &CStr = c"darwin";
#[cfg(not(target_os = "macos"))] const OS_PLATFORM: &CStr = c"linux";
const js_os_funcs: [JSCFunctionListEntry; 71] = [
JS_CFUNC_DEF(c"open".as_ptr(), 2, Some(js_os_open)),
JS_PROP_INT32_DEF(c"O_RDONLY".as_ptr(), libc::O_RDONLY as i32, JS_PROP_CONFIGURABLE),
JS_PROP_INT32_DEF(c"O_WRONLY".as_ptr(), libc::O_WRONLY as i32, JS_PROP_CONFIGURABLE),
JS_PROP_INT32_DEF(c"O_RDWR".as_ptr(), libc::O_RDWR as i32, JS_PROP_CONFIGURABLE),
JS_PROP_INT32_DEF(c"O_APPEND".as_ptr(), libc::O_APPEND as i32, JS_PROP_CONFIGURABLE),
JS_PROP_INT32_DEF(c"O_CREAT".as_ptr(), libc::O_CREAT as i32, JS_PROP_CONFIGURABLE),
JS_PROP_INT32_DEF(c"O_EXCL".as_ptr(), libc::O_EXCL as i32, JS_PROP_CONFIGURABLE),
JS_PROP_INT32_DEF(c"O_TRUNC".as_ptr(), libc::O_TRUNC as i32, JS_PROP_CONFIGURABLE),
JS_CFUNC_DEF(c"close".as_ptr(), 1, Some(js_os_close)),
JS_CFUNC_DEF(c"seek".as_ptr(), 3, Some(js_os_seek)),
JS_CFUNC_MAGIC_DEF(c"read".as_ptr(), 4, Some(js_os_read_write), 0),
JS_CFUNC_MAGIC_DEF(c"write".as_ptr(), 4, Some(js_os_read_write), 1),
JS_CFUNC_DEF(c"isatty".as_ptr(), 1, Some(js_os_isatty)),
JS_CFUNC_DEF(c"ttyGetWinSize".as_ptr(), 1, Some(js_os_ttyGetWinSize)),
JS_CFUNC_DEF(c"ttySetRaw".as_ptr(), 1, Some(js_os_ttySetRaw)),
JS_CFUNC_DEF(c"remove".as_ptr(), 1, Some(js_os_remove)),
JS_CFUNC_DEF(c"rename".as_ptr(), 2, Some(js_os_rename)),
JS_CFUNC_MAGIC_DEF(c"setReadHandler".as_ptr(), 2, Some(js_os_setReadHandler), 0),
JS_CFUNC_MAGIC_DEF(c"setWriteHandler".as_ptr(), 2, Some(js_os_setReadHandler), 1),
JS_CFUNC_DEF(c"signal".as_ptr(), 2, Some(js_os_signal)),
JS_PROP_INT32_DEF(c"SIGINT".as_ptr(), libc::SIGINT as i32, JS_PROP_CONFIGURABLE),
JS_PROP_INT32_DEF(c"SIGABRT".as_ptr(), libc::SIGABRT as i32, JS_PROP_CONFIGURABLE),
JS_PROP_INT32_DEF(c"SIGFPE".as_ptr(), libc::SIGFPE as i32, JS_PROP_CONFIGURABLE),
JS_PROP_INT32_DEF(c"SIGILL".as_ptr(), libc::SIGILL as i32, JS_PROP_CONFIGURABLE),
JS_PROP_INT32_DEF(c"SIGSEGV".as_ptr(), libc::SIGSEGV as i32, JS_PROP_CONFIGURABLE),
JS_PROP_INT32_DEF(c"SIGTERM".as_ptr(), libc::SIGTERM as i32, JS_PROP_CONFIGURABLE),
JS_PROP_INT32_DEF(c"SIGQUIT".as_ptr(), libc::SIGQUIT as i32, JS_PROP_CONFIGURABLE),
JS_PROP_INT32_DEF(c"SIGPIPE".as_ptr(), libc::SIGPIPE as i32, JS_PROP_CONFIGURABLE),
JS_PROP_INT32_DEF(c"SIGALRM".as_ptr(), libc::SIGALRM as i32, JS_PROP_CONFIGURABLE),
JS_PROP_INT32_DEF(c"SIGUSR1".as_ptr(), libc::SIGUSR1 as i32, JS_PROP_CONFIGURABLE),
JS_PROP_INT32_DEF(c"SIGUSR2".as_ptr(), libc::SIGUSR2 as i32, JS_PROP_CONFIGURABLE),
JS_PROP_INT32_DEF(c"SIGCHLD".as_ptr(), libc::SIGCHLD as i32, JS_PROP_CONFIGURABLE),
JS_PROP_INT32_DEF(c"SIGCONT".as_ptr(), libc::SIGCONT as i32, JS_PROP_CONFIGURABLE),
JS_PROP_INT32_DEF(c"SIGSTOP".as_ptr(), libc::SIGSTOP as i32, JS_PROP_CONFIGURABLE),
JS_PROP_INT32_DEF(c"SIGTSTP".as_ptr(), libc::SIGTSTP as i32, JS_PROP_CONFIGURABLE),
JS_PROP_INT32_DEF(c"SIGTTIN".as_ptr(), libc::SIGTTIN as i32, JS_PROP_CONFIGURABLE),
JS_PROP_INT32_DEF(c"SIGTTOU".as_ptr(), libc::SIGTTOU as i32, JS_PROP_CONFIGURABLE),
JS_CFUNC_DEF(c"now".as_ptr(), 0, Some(js_os_now)),
JS_CFUNC_DEF(c"setTimeout".as_ptr(), 2, Some(js_os_setTimeout)),
JS_CFUNC_DEF(c"clearTimeout".as_ptr(), 1, Some(js_os_clearTimeout)),
JS_CFUNC_DEF(c"sleepAsync".as_ptr(), 1, Some(js_os_sleepAsync)),
JS_PROP_STRING_DEF(c"platform".as_ptr(), OS_PLATFORM.as_ptr(), 0),
JS_CFUNC_DEF(c"getcwd".as_ptr(), 0, Some(js_os_getcwd)),
JS_CFUNC_DEF(c"chdir".as_ptr(), 0, Some(js_os_chdir)),
JS_CFUNC_DEF(c"mkdir".as_ptr(), 1, Some(js_os_mkdir)),
JS_CFUNC_DEF(c"readdir".as_ptr(), 1, Some(js_os_readdir)),
JS_PROP_INT32_DEF(c"S_IFMT".as_ptr(), libc::S_IFMT as i32, JS_PROP_CONFIGURABLE),
JS_PROP_INT32_DEF(c"S_IFIFO".as_ptr(), libc::S_IFIFO as i32, JS_PROP_CONFIGURABLE),
JS_PROP_INT32_DEF(c"S_IFCHR".as_ptr(), libc::S_IFCHR as i32, JS_PROP_CONFIGURABLE),
JS_PROP_INT32_DEF(c"S_IFDIR".as_ptr(), libc::S_IFDIR as i32, JS_PROP_CONFIGURABLE),
JS_PROP_INT32_DEF(c"S_IFBLK".as_ptr(), libc::S_IFBLK as i32, JS_PROP_CONFIGURABLE),
JS_PROP_INT32_DEF(c"S_IFREG".as_ptr(), libc::S_IFREG as i32, JS_PROP_CONFIGURABLE),
JS_PROP_INT32_DEF(c"S_IFSOCK".as_ptr(), libc::S_IFSOCK as i32, JS_PROP_CONFIGURABLE),
JS_PROP_INT32_DEF(c"S_IFLNK".as_ptr(), libc::S_IFLNK as i32, JS_PROP_CONFIGURABLE),
JS_PROP_INT32_DEF(c"S_ISGID".as_ptr(), libc::S_ISGID as i32, JS_PROP_CONFIGURABLE),
JS_PROP_INT32_DEF(c"S_ISUID".as_ptr(), libc::S_ISUID as i32, JS_PROP_CONFIGURABLE),
JS_CFUNC_MAGIC_DEF(c"stat".as_ptr(), 1, Some(js_os_stat), 0),
JS_CFUNC_DEF(c"utimes".as_ptr(), 3, Some(js_os_utimes)),
JS_CFUNC_DEF(c"sleep".as_ptr(), 1, Some(js_os_sleep)),
JS_CFUNC_DEF(c"realpath".as_ptr(), 1, Some(js_os_realpath)),
JS_CFUNC_MAGIC_DEF(c"lstat".as_ptr(), 1, Some(js_os_stat), 1),
JS_CFUNC_DEF(c"symlink".as_ptr(), 2, Some(js_os_symlink)),
JS_CFUNC_DEF(c"readlink".as_ptr(), 1, Some(js_os_readlink)),
JS_CFUNC_DEF(c"exec".as_ptr(), 1, Some(js_os_exec)),
JS_CFUNC_DEF(c"getpid".as_ptr(), 0, Some(js_os_getpid)),
JS_CFUNC_DEF(c"waitpid".as_ptr(), 2, Some(js_os_waitpid)),
JS_PROP_INT32_DEF(c"WNOHANG".as_ptr(), libc::WNOHANG as i32, JS_PROP_CONFIGURABLE),
JS_CFUNC_DEF(c"pipe".as_ptr(), 0, Some(js_os_pipe)),
JS_CFUNC_DEF(c"kill".as_ptr(), 2, Some(js_os_kill)),
JS_CFUNC_DEF(c"dup".as_ptr(), 1, Some(js_os_dup)),
JS_CFUNC_DEF(c"dup2".as_ptr(), 2, Some(js_os_dup2)),
];
