// Exact official quickjs.c Math table order and descriptors. MIT.
static mut js_math_funcs: [JSCFunctionListEntry; 46] = [
    JS_CFUNC_MAGIC_DEF(c"min".as_ptr(), 2, Some(js_math_min_max), (0) as i32),
    JS_CFUNC_MAGIC_DEF(c"max".as_ptr(), 2, Some(js_math_min_max), (1) as i32),
    JS_CFUNC_SPECIAL_DEF(c"abs".as_ptr(), 1, JS_CFUNC_f_f, JSCFunctionType { f_f: Some(js_math_f64_fabs) }),
    JS_CFUNC_SPECIAL_DEF(c"floor".as_ptr(), 1, JS_CFUNC_f_f, JSCFunctionType { f_f: Some(js_math_f64_floor) }),
    JS_CFUNC_SPECIAL_DEF(c"ceil".as_ptr(), 1, JS_CFUNC_f_f, JSCFunctionType { f_f: Some(js_math_f64_ceil) }),
    JS_CFUNC_SPECIAL_DEF(c"round".as_ptr(), 1, JS_CFUNC_f_f, JSCFunctionType { f_f: Some(js_math_round) }),
    JS_CFUNC_SPECIAL_DEF(c"sqrt".as_ptr(), 1, JS_CFUNC_f_f, JSCFunctionType { f_f: Some(js_math_f64_sqrt) }),
    JS_CFUNC_SPECIAL_DEF(c"acos".as_ptr(), 1, JS_CFUNC_f_f, JSCFunctionType { f_f: Some(js_math_f64_acos) }),
    JS_CFUNC_SPECIAL_DEF(c"asin".as_ptr(), 1, JS_CFUNC_f_f, JSCFunctionType { f_f: Some(js_math_f64_asin) }),
    JS_CFUNC_SPECIAL_DEF(c"atan".as_ptr(), 1, JS_CFUNC_f_f, JSCFunctionType { f_f: Some(js_math_f64_atan) }),
    JS_CFUNC_SPECIAL_DEF(c"atan2".as_ptr(), 2, JS_CFUNC_f_f_f, JSCFunctionType { f_f_f: Some(js_math_f64_atan2) }),
    JS_CFUNC_SPECIAL_DEF(c"cos".as_ptr(), 1, JS_CFUNC_f_f, JSCFunctionType { f_f: Some(js_math_f64_cos) }),
    JS_CFUNC_SPECIAL_DEF(c"exp".as_ptr(), 1, JS_CFUNC_f_f, JSCFunctionType { f_f: Some(js_math_f64_exp) }),
    JS_CFUNC_SPECIAL_DEF(c"log".as_ptr(), 1, JS_CFUNC_f_f, JSCFunctionType { f_f: Some(js_math_f64_log) }),
    JS_CFUNC_SPECIAL_DEF(c"pow".as_ptr(), 2, JS_CFUNC_f_f_f, JSCFunctionType { f_f_f: Some(js_pow) }),
    JS_CFUNC_SPECIAL_DEF(c"sin".as_ptr(), 1, JS_CFUNC_f_f, JSCFunctionType { f_f: Some(js_math_f64_sin) }),
    JS_CFUNC_SPECIAL_DEF(c"tan".as_ptr(), 1, JS_CFUNC_f_f, JSCFunctionType { f_f: Some(js_math_f64_tan) }),
    JS_CFUNC_SPECIAL_DEF(c"trunc".as_ptr(), 1, JS_CFUNC_f_f, JSCFunctionType { f_f: Some(js_math_f64_trunc) }),
    JS_CFUNC_SPECIAL_DEF(c"sign".as_ptr(), 1, JS_CFUNC_f_f, JSCFunctionType { f_f: Some(js_math_sign) }),
    JS_CFUNC_SPECIAL_DEF(c"cosh".as_ptr(), 1, JS_CFUNC_f_f, JSCFunctionType { f_f: Some(js_math_f64_cosh) }),
    JS_CFUNC_SPECIAL_DEF(c"sinh".as_ptr(), 1, JS_CFUNC_f_f, JSCFunctionType { f_f: Some(js_math_f64_sinh) }),
    JS_CFUNC_SPECIAL_DEF(c"tanh".as_ptr(), 1, JS_CFUNC_f_f, JSCFunctionType { f_f: Some(js_math_f64_tanh) }),
    JS_CFUNC_SPECIAL_DEF(c"acosh".as_ptr(), 1, JS_CFUNC_f_f, JSCFunctionType { f_f: Some(js_math_f64_acosh) }),
    JS_CFUNC_SPECIAL_DEF(c"asinh".as_ptr(), 1, JS_CFUNC_f_f, JSCFunctionType { f_f: Some(js_math_f64_asinh) }),
    JS_CFUNC_SPECIAL_DEF(c"atanh".as_ptr(), 1, JS_CFUNC_f_f, JSCFunctionType { f_f: Some(js_math_f64_atanh) }),
    JS_CFUNC_SPECIAL_DEF(c"expm1".as_ptr(), 1, JS_CFUNC_f_f, JSCFunctionType { f_f: Some(js_math_f64_expm1) }),
    JS_CFUNC_SPECIAL_DEF(c"log1p".as_ptr(), 1, JS_CFUNC_f_f, JSCFunctionType { f_f: Some(js_math_f64_log1p) }),
    JS_CFUNC_SPECIAL_DEF(c"log2".as_ptr(), 1, JS_CFUNC_f_f, JSCFunctionType { f_f: Some(js_math_f64_log2) }),
    JS_CFUNC_SPECIAL_DEF(c"log10".as_ptr(), 1, JS_CFUNC_f_f, JSCFunctionType { f_f: Some(js_math_f64_log10) }),
    JS_CFUNC_SPECIAL_DEF(c"cbrt".as_ptr(), 1, JS_CFUNC_f_f, JSCFunctionType { f_f: Some(js_math_f64_cbrt) }),
    JS_CFUNC_DEF(c"hypot".as_ptr(), 2, Some(js_math_hypot)),
    JS_CFUNC_DEF(c"random".as_ptr(), 0, Some(js_math_random)),
    JS_CFUNC_SPECIAL_DEF(c"f16round".as_ptr(), 1, JS_CFUNC_f_f, JSCFunctionType { f_f: Some(js_math_f16round) }),
    JS_CFUNC_SPECIAL_DEF(c"fround".as_ptr(), 1, JS_CFUNC_f_f, JSCFunctionType { f_f: Some(js_math_fround) }),
    JS_CFUNC_DEF(c"imul".as_ptr(), 2, Some(js_math_imul)),
    JS_CFUNC_DEF(c"clz32".as_ptr(), 1, Some(js_math_clz32)),
    JS_CFUNC_DEF(c"sumPrecise".as_ptr(), 1, Some(js_math_sumPrecise)),
    JS_PROP_STRING_DEF(c"[Symbol.toStringTag]".as_ptr(), c"Math".as_ptr(), JS_PROP_CONFIGURABLE),
    JS_PROP_DOUBLE_DEF(c"E".as_ptr(), 2.718281828459045, 0),
    JS_PROP_DOUBLE_DEF(c"LN10".as_ptr(), 2.302585092994046, 0),
    JS_PROP_DOUBLE_DEF(c"LN2".as_ptr(), 0.6931471805599453, 0),
    JS_PROP_DOUBLE_DEF(c"LOG2E".as_ptr(), 1.4426950408889634, 0),
    JS_PROP_DOUBLE_DEF(c"LOG10E".as_ptr(), 0.4342944819032518, 0),
    JS_PROP_DOUBLE_DEF(c"PI".as_ptr(), 3.141592653589793, 0),
    JS_PROP_DOUBLE_DEF(c"SQRT1_2".as_ptr(), 0.7071067811865476, 0),
    JS_PROP_DOUBLE_DEF(c"SQRT2".as_ptr(), 1.4142135623730951, 0),
];
static mut js_math_obj: [JSCFunctionListEntry; 1] = [
    JS_OBJECT_DEF(c"Math".as_ptr(), ptr::addr_of!(js_math_funcs).cast(), 46, JS_PROP_WRITABLE | JS_PROP_CONFIGURABLE),
];
