// Exact official quickjs.c Array/Iterator table order and descriptors. MIT.
static mut js_array_funcs: [JSCFunctionListEntry; 4] = [
    JS_CFUNC_DEF(c"isArray".as_ptr(), 1, Some(js_array_isArray)),
    JS_CFUNC_DEF(c"from".as_ptr(), 1, Some(js_array_from)),
    JS_CFUNC_DEF(c"of".as_ptr(), 0, Some(js_array_of)),
    JS_CGETSET_DEF(c"[Symbol.species]".as_ptr(), Some(js_get_this), None),
];
static mut js_iterator_wrap_proto_funcs: [JSCFunctionListEntry; 2] = [
    JS_ITERATOR_NEXT_DEF(c"next".as_ptr(), 0, Some(js_iterator_wrap_next), GEN_MAGIC_NEXT),
    JS_ITERATOR_NEXT_DEF(c"return".as_ptr(), 0, Some(js_iterator_wrap_next), GEN_MAGIC_RETURN),
];
static mut js_iterator_concat_proto_funcs: [JSCFunctionListEntry; 3] = [
    JS_ITERATOR_NEXT_DEF(c"next".as_ptr(), 0, Some(js_iterator_concat_next), 0),
    JS_CFUNC_DEF(c"return".as_ptr(), 0, Some(js_iterator_concat_return)),
    JS_PROP_STRING_DEF(c"[Symbol.toStringTag]".as_ptr(), c"Iterator Concat".as_ptr(), JS_PROP_CONFIGURABLE),
];
static mut js_iterator_funcs: [JSCFunctionListEntry; 2] = [
    JS_CFUNC_DEF(c"concat".as_ptr(), 0, Some(js_iterator_concat)),
    JS_CFUNC_DEF(c"from".as_ptr(), 1, Some(js_iterator_from)),
];
static mut js_iterator_proto_funcs: [JSCFunctionListEntry; 13] = [
    JS_CFUNC_MAGIC_DEF(c"drop".as_ptr(), 1, Some(js_create_iterator_helper), (JS_ITERATOR_HELPER_KIND_DROP) as i32),
    JS_CFUNC_MAGIC_DEF(c"filter".as_ptr(), 1, Some(js_create_iterator_helper), (JS_ITERATOR_HELPER_KIND_FILTER) as i32),
    JS_CFUNC_MAGIC_DEF(c"flatMap".as_ptr(), 1, Some(js_create_iterator_helper), (JS_ITERATOR_HELPER_KIND_FLAT_MAP) as i32),
    JS_CFUNC_MAGIC_DEF(c"map".as_ptr(), 1, Some(js_create_iterator_helper), (JS_ITERATOR_HELPER_KIND_MAP) as i32),
    JS_CFUNC_MAGIC_DEF(c"take".as_ptr(), 1, Some(js_create_iterator_helper), (JS_ITERATOR_HELPER_KIND_TAKE) as i32),
    JS_CFUNC_MAGIC_DEF(c"every".as_ptr(), 1, Some(js_iterator_proto_func), (JS_ITERATOR_HELPER_KIND_EVERY) as i32),
    JS_CFUNC_MAGIC_DEF(c"find".as_ptr(), 1, Some(js_iterator_proto_func), (JS_ITERATOR_HELPER_KIND_FIND) as i32),
    JS_CFUNC_MAGIC_DEF(c"forEach".as_ptr(), 1, Some(js_iterator_proto_func), (JS_ITERATOR_HELPER_KIND_FOR_EACH) as i32),
    JS_CFUNC_MAGIC_DEF(c"some".as_ptr(), 1, Some(js_iterator_proto_func), (JS_ITERATOR_HELPER_KIND_SOME) as i32),
    JS_CFUNC_DEF(c"reduce".as_ptr(), 1, Some(js_iterator_proto_reduce)),
    JS_CFUNC_DEF(c"toArray".as_ptr(), 0, Some(js_iterator_proto_toArray)),
    JS_CFUNC_DEF(c"[Symbol.iterator]".as_ptr(), 0, Some(js_iterator_proto_iterator)),
    JS_CGETSET_DEF(c"[Symbol.toStringTag]".as_ptr(), Some(js_iterator_proto_get_toStringTag), Some(js_iterator_proto_set_toStringTag)),
];
static mut js_iterator_helper_proto_funcs: [JSCFunctionListEntry; 3] = [
    JS_ITERATOR_NEXT_DEF(c"next".as_ptr(), 0, Some(js_iterator_helper_next), GEN_MAGIC_NEXT),
    JS_ITERATOR_NEXT_DEF(c"return".as_ptr(), 0, Some(js_iterator_helper_next), GEN_MAGIC_RETURN),
    JS_PROP_STRING_DEF(c"[Symbol.toStringTag]".as_ptr(), c"Iterator Helper".as_ptr(), JS_PROP_CONFIGURABLE),
];
static mut js_array_unscopables_funcs: [JSCFunctionListEntry; 16] = [
    JS_PROP_BOOL_DEF(c"at".as_ptr(), 1, JS_PROP_C_W_E),
    JS_PROP_BOOL_DEF(c"copyWithin".as_ptr(), 1, JS_PROP_C_W_E),
    JS_PROP_BOOL_DEF(c"entries".as_ptr(), 1, JS_PROP_C_W_E),
    JS_PROP_BOOL_DEF(c"fill".as_ptr(), 1, JS_PROP_C_W_E),
    JS_PROP_BOOL_DEF(c"find".as_ptr(), 1, JS_PROP_C_W_E),
    JS_PROP_BOOL_DEF(c"findIndex".as_ptr(), 1, JS_PROP_C_W_E),
    JS_PROP_BOOL_DEF(c"findLast".as_ptr(), 1, JS_PROP_C_W_E),
    JS_PROP_BOOL_DEF(c"findLastIndex".as_ptr(), 1, JS_PROP_C_W_E),
    JS_PROP_BOOL_DEF(c"flat".as_ptr(), 1, JS_PROP_C_W_E),
    JS_PROP_BOOL_DEF(c"flatMap".as_ptr(), 1, JS_PROP_C_W_E),
    JS_PROP_BOOL_DEF(c"includes".as_ptr(), 1, JS_PROP_C_W_E),
    JS_PROP_BOOL_DEF(c"keys".as_ptr(), 1, JS_PROP_C_W_E),
    JS_PROP_BOOL_DEF(c"toReversed".as_ptr(), 1, JS_PROP_C_W_E),
    JS_PROP_BOOL_DEF(c"toSorted".as_ptr(), 1, JS_PROP_C_W_E),
    JS_PROP_BOOL_DEF(c"toSpliced".as_ptr(), 1, JS_PROP_C_W_E),
    JS_PROP_BOOL_DEF(c"values".as_ptr(), 1, JS_PROP_C_W_E),
];
static mut js_array_proto_funcs: [JSCFunctionListEntry; 40] = [
    JS_CFUNC_DEF(c"at".as_ptr(), 1, Some(js_array_at)),
    JS_CFUNC_DEF(c"with".as_ptr(), 2, Some(js_array_with)),
    JS_CFUNC_DEF(c"concat".as_ptr(), 1, Some(js_array_concat)),
    JS_CFUNC_MAGIC_DEF(c"every".as_ptr(), 1, Some(js_array_every), (special_every) as i32),
    JS_CFUNC_MAGIC_DEF(c"some".as_ptr(), 1, Some(js_array_every), (special_some) as i32),
    JS_CFUNC_MAGIC_DEF(c"forEach".as_ptr(), 1, Some(js_array_every), (special_forEach) as i32),
    JS_CFUNC_MAGIC_DEF(c"map".as_ptr(), 1, Some(js_array_every), (special_map) as i32),
    JS_CFUNC_MAGIC_DEF(c"filter".as_ptr(), 1, Some(js_array_every), (special_filter) as i32),
    JS_CFUNC_MAGIC_DEF(c"reduce".as_ptr(), 1, Some(js_array_reduce), (special_reduce) as i32),
    JS_CFUNC_MAGIC_DEF(c"reduceRight".as_ptr(), 1, Some(js_array_reduce), (special_reduceRight) as i32),
    JS_CFUNC_DEF(c"fill".as_ptr(), 1, Some(js_array_fill)),
    JS_CFUNC_MAGIC_DEF(c"find".as_ptr(), 1, Some(js_array_find), (ArrayFind) as i32),
    JS_CFUNC_MAGIC_DEF(c"findIndex".as_ptr(), 1, Some(js_array_find), (ArrayFindIndex) as i32),
    JS_CFUNC_MAGIC_DEF(c"findLast".as_ptr(), 1, Some(js_array_find), (ArrayFindLast) as i32),
    JS_CFUNC_MAGIC_DEF(c"findLastIndex".as_ptr(), 1, Some(js_array_find), (ArrayFindLastIndex) as i32),
    JS_CFUNC_DEF(c"indexOf".as_ptr(), 1, Some(js_array_indexOf)),
    JS_CFUNC_DEF(c"lastIndexOf".as_ptr(), 1, Some(js_array_lastIndexOf)),
    JS_CFUNC_DEF(c"includes".as_ptr(), 1, Some(js_array_includes)),
    JS_CFUNC_MAGIC_DEF(c"join".as_ptr(), 1, Some(js_array_join), (0) as i32),
    JS_CFUNC_DEF(c"toString".as_ptr(), 0, Some(js_array_toString)),
    JS_CFUNC_MAGIC_DEF(c"toLocaleString".as_ptr(), 0, Some(js_array_join), (1) as i32),
    JS_CFUNC_MAGIC_DEF(c"pop".as_ptr(), 0, Some(js_array_pop), (0) as i32),
    JS_CFUNC_MAGIC_DEF(c"push".as_ptr(), 1, Some(js_array_push), (0) as i32),
    JS_CFUNC_MAGIC_DEF(c"shift".as_ptr(), 0, Some(js_array_pop), (1) as i32),
    JS_CFUNC_MAGIC_DEF(c"unshift".as_ptr(), 1, Some(js_array_push), (1) as i32),
    JS_CFUNC_DEF(c"reverse".as_ptr(), 0, Some(js_array_reverse)),
    JS_CFUNC_DEF(c"toReversed".as_ptr(), 0, Some(js_array_toReversed)),
    JS_CFUNC_DEF(c"sort".as_ptr(), 1, Some(js_array_sort)),
    JS_CFUNC_DEF(c"toSorted".as_ptr(), 1, Some(js_array_toSorted)),
    JS_CFUNC_MAGIC_DEF(c"slice".as_ptr(), 2, Some(js_array_slice), (0) as i32),
    JS_CFUNC_MAGIC_DEF(c"splice".as_ptr(), 2, Some(js_array_slice), (1) as i32),
    JS_CFUNC_DEF(c"toSpliced".as_ptr(), 2, Some(js_array_toSpliced)),
    JS_CFUNC_DEF(c"copyWithin".as_ptr(), 2, Some(js_array_copyWithin)),
    JS_CFUNC_MAGIC_DEF(c"flatMap".as_ptr(), 1, Some(js_array_flatten), (1) as i32),
    JS_CFUNC_MAGIC_DEF(c"flat".as_ptr(), 0, Some(js_array_flatten), (0) as i32),
    JS_CFUNC_MAGIC_DEF(c"values".as_ptr(), 0, Some(js_create_array_iterator), (JS_ITERATOR_KIND_VALUE) as i32),
    JS_ALIAS_DEF(c"[Symbol.iterator]".as_ptr(), c"values".as_ptr()),
    JS_CFUNC_MAGIC_DEF(c"keys".as_ptr(), 0, Some(js_create_array_iterator), (JS_ITERATOR_KIND_KEY) as i32),
    JS_CFUNC_MAGIC_DEF(c"entries".as_ptr(), 0, Some(js_create_array_iterator), (JS_ITERATOR_KIND_KEY_AND_VALUE) as i32),
    JS_OBJECT_DEF(c"[Symbol.unscopables]".as_ptr(), ptr::addr_of!(js_array_unscopables_funcs).cast(), 16, JS_PROP_CONFIGURABLE),
];
static mut js_array_iterator_proto_funcs: [JSCFunctionListEntry; 2] = [
    JS_ITERATOR_NEXT_DEF(c"next".as_ptr(), 0, Some(js_array_iterator_next), 0),
    JS_PROP_STRING_DEF(c"[Symbol.toStringTag]".as_ptr(), c"Array Iterator".as_ptr(), JS_PROP_CONFIGURABLE),
];
