// Exact official quickjs.c Buffer/TypedArray/DataView/Atomics table order and descriptors. MIT.
static mut js_array_buffer_funcs: [JSCFunctionListEntry; 2] = [
    JS_CFUNC_DEF(c"isView".as_ptr(), 1, Some(js_array_buffer_isView)),
    JS_CGETSET_DEF(c"[Symbol.species]".as_ptr(), Some(js_get_this), None),
];
static mut js_array_buffer_proto_funcs: [JSCFunctionListEntry; 9] = [
    JS_CGETSET_MAGIC_DEF(c"byteLength".as_ptr(), Some(js_array_buffer_get_byteLength), None, (JS_CLASS_ARRAY_BUFFER) as i32),
    JS_CGETSET_MAGIC_DEF(c"maxByteLength".as_ptr(), Some(js_array_buffer_get_maxByteLength), None, (JS_CLASS_ARRAY_BUFFER) as i32),
    JS_CGETSET_MAGIC_DEF(c"resizable".as_ptr(), Some(js_array_buffer_get_resizable), None, (JS_CLASS_ARRAY_BUFFER) as i32),
    JS_CGETSET_DEF(c"detached".as_ptr(), Some(js_array_buffer_get_detached), None),
    JS_CFUNC_MAGIC_DEF(c"resize".as_ptr(), 1, Some(js_array_buffer_resize), (JS_CLASS_ARRAY_BUFFER) as i32),
    JS_CFUNC_MAGIC_DEF(c"slice".as_ptr(), 2, Some(js_array_buffer_slice), (JS_CLASS_ARRAY_BUFFER) as i32),
    JS_CFUNC_MAGIC_DEF(c"transfer".as_ptr(), 0, Some(js_array_buffer_transfer), (0) as i32),
    JS_CFUNC_MAGIC_DEF(c"transferToFixedLength".as_ptr(), 0, Some(js_array_buffer_transfer), (1) as i32),
    JS_PROP_STRING_DEF(c"[Symbol.toStringTag]".as_ptr(), c"ArrayBuffer".as_ptr(), JS_PROP_CONFIGURABLE),
];
static mut js_shared_array_buffer_funcs: [JSCFunctionListEntry; 1] = [
    JS_CGETSET_DEF(c"[Symbol.species]".as_ptr(), Some(js_get_this), None),
];
static mut js_shared_array_buffer_proto_funcs: [JSCFunctionListEntry; 6] = [
    JS_CGETSET_MAGIC_DEF(c"byteLength".as_ptr(), Some(js_array_buffer_get_byteLength), None, (JS_CLASS_SHARED_ARRAY_BUFFER) as i32),
    JS_CGETSET_MAGIC_DEF(c"maxByteLength".as_ptr(), Some(js_array_buffer_get_maxByteLength), None, (JS_CLASS_SHARED_ARRAY_BUFFER) as i32),
    JS_CGETSET_MAGIC_DEF(c"growable".as_ptr(), Some(js_array_buffer_get_resizable), None, (JS_CLASS_SHARED_ARRAY_BUFFER) as i32),
    JS_CFUNC_MAGIC_DEF(c"grow".as_ptr(), 1, Some(js_array_buffer_resize), (JS_CLASS_SHARED_ARRAY_BUFFER) as i32),
    JS_CFUNC_MAGIC_DEF(c"slice".as_ptr(), 2, Some(js_array_buffer_slice), (JS_CLASS_SHARED_ARRAY_BUFFER) as i32),
    JS_PROP_STRING_DEF(c"[Symbol.toStringTag]".as_ptr(), c"SharedArrayBuffer".as_ptr(), JS_PROP_CONFIGURABLE),
];
static mut js_typed_array_base_funcs: [JSCFunctionListEntry; 3] = [
    JS_CFUNC_DEF(c"from".as_ptr(), 1, Some(js_typed_array_from)),
    JS_CFUNC_DEF(c"of".as_ptr(), 0, Some(js_typed_array_of)),
    JS_CGETSET_DEF(c"[Symbol.species]".as_ptr(), Some(js_get_this), None),
];
static mut js_typed_array_base_proto_funcs: [JSCFunctionListEntry; 36] = [
    JS_CGETSET_DEF(c"length".as_ptr(), Some(js_typed_array_get_length), None),
    JS_CFUNC_DEF(c"at".as_ptr(), 1, Some(js_typed_array_at)),
    JS_CFUNC_DEF(c"with".as_ptr(), 2, Some(js_typed_array_with)),
    JS_CGETSET_DEF(c"buffer".as_ptr(), Some(js_typed_array_get_buffer), None),
    JS_CGETSET_DEF(c"byteLength".as_ptr(), Some(js_typed_array_get_byteLength), None),
    JS_CGETSET_DEF(c"byteOffset".as_ptr(), Some(js_typed_array_get_byteOffset), None),
    JS_CFUNC_DEF(c"set".as_ptr(), 1, Some(js_typed_array_set)),
    JS_CFUNC_MAGIC_DEF(c"values".as_ptr(), 0, Some(js_create_typed_array_iterator), (JS_ITERATOR_KIND_VALUE) as i32),
    JS_ALIAS_DEF(c"[Symbol.iterator]".as_ptr(), c"values".as_ptr()),
    JS_CFUNC_MAGIC_DEF(c"keys".as_ptr(), 0, Some(js_create_typed_array_iterator), (JS_ITERATOR_KIND_KEY) as i32),
    JS_CFUNC_MAGIC_DEF(c"entries".as_ptr(), 0, Some(js_create_typed_array_iterator), (JS_ITERATOR_KIND_KEY_AND_VALUE) as i32),
    JS_CGETSET_DEF(c"[Symbol.toStringTag]".as_ptr(), Some(js_typed_array_get_toStringTag), None),
    JS_CFUNC_DEF(c"copyWithin".as_ptr(), 2, Some(js_typed_array_copyWithin)),
    JS_CFUNC_MAGIC_DEF(c"every".as_ptr(), 1, Some(js_array_every), (special_every | special_TA) as i32),
    JS_CFUNC_MAGIC_DEF(c"some".as_ptr(), 1, Some(js_array_every), (special_some | special_TA) as i32),
    JS_CFUNC_MAGIC_DEF(c"forEach".as_ptr(), 1, Some(js_array_every), (special_forEach | special_TA) as i32),
    JS_CFUNC_MAGIC_DEF(c"map".as_ptr(), 1, Some(js_array_every), (special_map | special_TA) as i32),
    JS_CFUNC_MAGIC_DEF(c"filter".as_ptr(), 1, Some(js_array_every), (special_filter | special_TA) as i32),
    JS_CFUNC_MAGIC_DEF(c"reduce".as_ptr(), 1, Some(js_array_reduce), (special_reduce | special_TA) as i32),
    JS_CFUNC_MAGIC_DEF(c"reduceRight".as_ptr(), 1, Some(js_array_reduce), (special_reduceRight | special_TA) as i32),
    JS_CFUNC_DEF(c"fill".as_ptr(), 1, Some(js_typed_array_fill)),
    JS_CFUNC_MAGIC_DEF(c"find".as_ptr(), 1, Some(js_typed_array_find), (ArrayFind) as i32),
    JS_CFUNC_MAGIC_DEF(c"findIndex".as_ptr(), 1, Some(js_typed_array_find), (ArrayFindIndex) as i32),
    JS_CFUNC_MAGIC_DEF(c"findLast".as_ptr(), 1, Some(js_typed_array_find), (ArrayFindLast) as i32),
    JS_CFUNC_MAGIC_DEF(c"findLastIndex".as_ptr(), 1, Some(js_typed_array_find), (ArrayFindLastIndex) as i32),
    JS_CFUNC_DEF(c"reverse".as_ptr(), 0, Some(js_typed_array_reverse)),
    JS_CFUNC_DEF(c"toReversed".as_ptr(), 0, Some(js_typed_array_toReversed)),
    JS_CFUNC_DEF(c"slice".as_ptr(), 2, Some(js_typed_array_slice)),
    JS_CFUNC_DEF(c"subarray".as_ptr(), 2, Some(js_typed_array_subarray)),
    JS_CFUNC_DEF(c"sort".as_ptr(), 1, Some(js_typed_array_sort)),
    JS_CFUNC_DEF(c"toSorted".as_ptr(), 1, Some(js_typed_array_toSorted)),
    JS_CFUNC_MAGIC_DEF(c"join".as_ptr(), 1, Some(js_typed_array_join), (0) as i32),
    JS_CFUNC_MAGIC_DEF(c"toLocaleString".as_ptr(), 0, Some(js_typed_array_join), (1) as i32),
    JS_CFUNC_MAGIC_DEF(c"indexOf".as_ptr(), 1, Some(js_typed_array_indexOf), (special_indexOf) as i32),
    JS_CFUNC_MAGIC_DEF(c"lastIndexOf".as_ptr(), 1, Some(js_typed_array_indexOf), (special_lastIndexOf) as i32),
    JS_CFUNC_MAGIC_DEF(c"includes".as_ptr(), 1, Some(js_typed_array_indexOf), (special_includes) as i32),
];
static mut js_typed_array_funcs: [JSCFunctionListEntry; 4] = [
    JS_PROP_INT32_DEF(c"BYTES_PER_ELEMENT".as_ptr(), 1, 0),
    JS_PROP_INT32_DEF(c"BYTES_PER_ELEMENT".as_ptr(), 2, 0),
    JS_PROP_INT32_DEF(c"BYTES_PER_ELEMENT".as_ptr(), 4, 0),
    JS_PROP_INT32_DEF(c"BYTES_PER_ELEMENT".as_ptr(), 8, 0),
];
static mut js_uint8array_proto_funcs: [JSCFunctionListEntry; 5] = [
    JS_PROP_INT32_DEF(c"BYTES_PER_ELEMENT".as_ptr(), 1, 0),
    JS_CFUNC_DEF(c"toBase64".as_ptr(), 0, Some(js_uint8array_to_base64)),
    JS_CFUNC_DEF(c"toHex".as_ptr(), 0, Some(js_uint8array_to_hex)),
    JS_CFUNC_DEF(c"setFromBase64".as_ptr(), 1, Some(js_uint8array_set_from_base64)),
    JS_CFUNC_DEF(c"setFromHex".as_ptr(), 1, Some(js_uint8array_set_from_hex)),
];
static mut js_uint8array_funcs: [JSCFunctionListEntry; 3] = [
    JS_PROP_INT32_DEF(c"BYTES_PER_ELEMENT".as_ptr(), 1, 0),
    JS_CFUNC_DEF(c"fromBase64".as_ptr(), 1, Some(js_uint8array_from_base64)),
    JS_CFUNC_DEF(c"fromHex".as_ptr(), 1, Some(js_uint8array_from_hex)),
];
static mut js_dataview_proto_funcs: [JSCFunctionListEntry; 26] = [
    JS_CGETSET_DEF(c"buffer".as_ptr(), Some(js_dataview_get_buffer), None),
    JS_CGETSET_DEF(c"byteLength".as_ptr(), Some(js_dataview_get_byteLength), None),
    JS_CGETSET_DEF(c"byteOffset".as_ptr(), Some(js_dataview_get_byteOffset), None),
    JS_CFUNC_MAGIC_DEF(c"getInt8".as_ptr(), 1, Some(js_dataview_getValue), (JS_CLASS_INT8_ARRAY) as i32),
    JS_CFUNC_MAGIC_DEF(c"getUint8".as_ptr(), 1, Some(js_dataview_getValue), (JS_CLASS_UINT8_ARRAY) as i32),
    JS_CFUNC_MAGIC_DEF(c"getInt16".as_ptr(), 1, Some(js_dataview_getValue), (JS_CLASS_INT16_ARRAY) as i32),
    JS_CFUNC_MAGIC_DEF(c"getUint16".as_ptr(), 1, Some(js_dataview_getValue), (JS_CLASS_UINT16_ARRAY) as i32),
    JS_CFUNC_MAGIC_DEF(c"getInt32".as_ptr(), 1, Some(js_dataview_getValue), (JS_CLASS_INT32_ARRAY) as i32),
    JS_CFUNC_MAGIC_DEF(c"getUint32".as_ptr(), 1, Some(js_dataview_getValue), (JS_CLASS_UINT32_ARRAY) as i32),
    JS_CFUNC_MAGIC_DEF(c"getBigInt64".as_ptr(), 1, Some(js_dataview_getValue), (JS_CLASS_BIG_INT64_ARRAY) as i32),
    JS_CFUNC_MAGIC_DEF(c"getBigUint64".as_ptr(), 1, Some(js_dataview_getValue), (JS_CLASS_BIG_UINT64_ARRAY) as i32),
    JS_CFUNC_MAGIC_DEF(c"getFloat16".as_ptr(), 1, Some(js_dataview_getValue), (JS_CLASS_FLOAT16_ARRAY) as i32),
    JS_CFUNC_MAGIC_DEF(c"getFloat32".as_ptr(), 1, Some(js_dataview_getValue), (JS_CLASS_FLOAT32_ARRAY) as i32),
    JS_CFUNC_MAGIC_DEF(c"getFloat64".as_ptr(), 1, Some(js_dataview_getValue), (JS_CLASS_FLOAT64_ARRAY) as i32),
    JS_CFUNC_MAGIC_DEF(c"setInt8".as_ptr(), 2, Some(js_dataview_setValue), (JS_CLASS_INT8_ARRAY) as i32),
    JS_CFUNC_MAGIC_DEF(c"setUint8".as_ptr(), 2, Some(js_dataview_setValue), (JS_CLASS_UINT8_ARRAY) as i32),
    JS_CFUNC_MAGIC_DEF(c"setInt16".as_ptr(), 2, Some(js_dataview_setValue), (JS_CLASS_INT16_ARRAY) as i32),
    JS_CFUNC_MAGIC_DEF(c"setUint16".as_ptr(), 2, Some(js_dataview_setValue), (JS_CLASS_UINT16_ARRAY) as i32),
    JS_CFUNC_MAGIC_DEF(c"setInt32".as_ptr(), 2, Some(js_dataview_setValue), (JS_CLASS_INT32_ARRAY) as i32),
    JS_CFUNC_MAGIC_DEF(c"setUint32".as_ptr(), 2, Some(js_dataview_setValue), (JS_CLASS_UINT32_ARRAY) as i32),
    JS_CFUNC_MAGIC_DEF(c"setBigInt64".as_ptr(), 2, Some(js_dataview_setValue), (JS_CLASS_BIG_INT64_ARRAY) as i32),
    JS_CFUNC_MAGIC_DEF(c"setBigUint64".as_ptr(), 2, Some(js_dataview_setValue), (JS_CLASS_BIG_UINT64_ARRAY) as i32),
    JS_CFUNC_MAGIC_DEF(c"setFloat16".as_ptr(), 2, Some(js_dataview_setValue), (JS_CLASS_FLOAT16_ARRAY) as i32),
    JS_CFUNC_MAGIC_DEF(c"setFloat32".as_ptr(), 2, Some(js_dataview_setValue), (JS_CLASS_FLOAT32_ARRAY) as i32),
    JS_CFUNC_MAGIC_DEF(c"setFloat64".as_ptr(), 2, Some(js_dataview_setValue), (JS_CLASS_FLOAT64_ARRAY) as i32),
    JS_PROP_STRING_DEF(c"[Symbol.toStringTag]".as_ptr(), c"DataView".as_ptr(), JS_PROP_CONFIGURABLE),
];
static mut js_atomics_funcs: [JSCFunctionListEntry; 14] = [
    JS_CFUNC_MAGIC_DEF(c"add".as_ptr(), 3, Some(js_atomics_op), (ATOMICS_OP_ADD) as i32),
    JS_CFUNC_MAGIC_DEF(c"and".as_ptr(), 3, Some(js_atomics_op), (ATOMICS_OP_AND) as i32),
    JS_CFUNC_MAGIC_DEF(c"or".as_ptr(), 3, Some(js_atomics_op), (ATOMICS_OP_OR) as i32),
    JS_CFUNC_MAGIC_DEF(c"sub".as_ptr(), 3, Some(js_atomics_op), (ATOMICS_OP_SUB) as i32),
    JS_CFUNC_MAGIC_DEF(c"xor".as_ptr(), 3, Some(js_atomics_op), (ATOMICS_OP_XOR) as i32),
    JS_CFUNC_MAGIC_DEF(c"exchange".as_ptr(), 3, Some(js_atomics_op), (ATOMICS_OP_EXCHANGE) as i32),
    JS_CFUNC_MAGIC_DEF(c"compareExchange".as_ptr(), 4, Some(js_atomics_op), (ATOMICS_OP_COMPARE_EXCHANGE) as i32),
    JS_CFUNC_MAGIC_DEF(c"load".as_ptr(), 2, Some(js_atomics_op), (ATOMICS_OP_LOAD) as i32),
    JS_CFUNC_DEF(c"store".as_ptr(), 3, Some(js_atomics_store)),
    JS_CFUNC_DEF(c"isLockFree".as_ptr(), 1, Some(js_atomics_isLockFree)),
    JS_CFUNC_DEF(c"pause".as_ptr(), 0, Some(js_atomics_pause)),
    JS_CFUNC_DEF(c"wait".as_ptr(), 4, Some(js_atomics_wait)),
    JS_CFUNC_DEF(c"notify".as_ptr(), 3, Some(js_atomics_notify)),
    JS_PROP_STRING_DEF(c"[Symbol.toStringTag]".as_ptr(), c"Atomics".as_ptr(), JS_PROP_CONFIGURABLE),
];
static mut js_atomics_obj: [JSCFunctionListEntry; 1] = [
    JS_OBJECT_DEF(c"Atomics".as_ptr(), ptr::addr_of!(js_atomics_funcs).cast(), 14, JS_PROP_WRITABLE | JS_PROP_CONFIGURABLE),
];
