// Exact official quickjs.c Number/Boolean table order and descriptors. MIT.
static mut js_date_funcs: [JSCFunctionListEntry; 3] = [
    JS_CFUNC_DEF(c"now".as_ptr(), 0, Some(js_Date_now)),
    JS_CFUNC_DEF(c"parse".as_ptr(), 1, Some(js_Date_parse)),
    JS_CFUNC_DEF(c"UTC".as_ptr(), 7, Some(js_Date_UTC)),
];
static mut js_date_proto_funcs: [JSCFunctionListEntry; 47] = [
    JS_CFUNC_DEF(c"valueOf".as_ptr(), 0, Some(js_date_getTime)),
    JS_CFUNC_MAGIC_DEF(c"toString".as_ptr(), 0, Some(get_date_string), (0x13) as i32),
    JS_CFUNC_DEF(c"[Symbol.toPrimitive]".as_ptr(), 1, Some(js_date_Symbol_toPrimitive)),
    JS_CFUNC_MAGIC_DEF(c"toUTCString".as_ptr(), 0, Some(get_date_string), (0x03) as i32),
    JS_ALIAS_DEF(c"toGMTString".as_ptr(), c"toUTCString".as_ptr()),
    JS_CFUNC_MAGIC_DEF(c"toISOString".as_ptr(), 0, Some(get_date_string), (0x23) as i32),
    JS_CFUNC_MAGIC_DEF(c"toDateString".as_ptr(), 0, Some(get_date_string), (0x11) as i32),
    JS_CFUNC_MAGIC_DEF(c"toTimeString".as_ptr(), 0, Some(get_date_string), (0x12) as i32),
    JS_CFUNC_MAGIC_DEF(c"toLocaleString".as_ptr(), 0, Some(get_date_string), (0x33) as i32),
    JS_CFUNC_MAGIC_DEF(c"toLocaleDateString".as_ptr(), 0, Some(get_date_string), (0x31) as i32),
    JS_CFUNC_MAGIC_DEF(c"toLocaleTimeString".as_ptr(), 0, Some(get_date_string), (0x32) as i32),
    JS_CFUNC_DEF(c"getTimezoneOffset".as_ptr(), 0, Some(js_date_getTimezoneOffset)),
    JS_CFUNC_DEF(c"getTime".as_ptr(), 0, Some(js_date_getTime)),
    JS_CFUNC_MAGIC_DEF(c"getYear".as_ptr(), 0, Some(get_date_field), (0x101) as i32),
    JS_CFUNC_MAGIC_DEF(c"getFullYear".as_ptr(), 0, Some(get_date_field), (0x01) as i32),
    JS_CFUNC_MAGIC_DEF(c"getUTCFullYear".as_ptr(), 0, Some(get_date_field), (0x00) as i32),
    JS_CFUNC_MAGIC_DEF(c"getMonth".as_ptr(), 0, Some(get_date_field), (0x11) as i32),
    JS_CFUNC_MAGIC_DEF(c"getUTCMonth".as_ptr(), 0, Some(get_date_field), (0x10) as i32),
    JS_CFUNC_MAGIC_DEF(c"getDate".as_ptr(), 0, Some(get_date_field), (0x21) as i32),
    JS_CFUNC_MAGIC_DEF(c"getUTCDate".as_ptr(), 0, Some(get_date_field), (0x20) as i32),
    JS_CFUNC_MAGIC_DEF(c"getHours".as_ptr(), 0, Some(get_date_field), (0x31) as i32),
    JS_CFUNC_MAGIC_DEF(c"getUTCHours".as_ptr(), 0, Some(get_date_field), (0x30) as i32),
    JS_CFUNC_MAGIC_DEF(c"getMinutes".as_ptr(), 0, Some(get_date_field), (0x41) as i32),
    JS_CFUNC_MAGIC_DEF(c"getUTCMinutes".as_ptr(), 0, Some(get_date_field), (0x40) as i32),
    JS_CFUNC_MAGIC_DEF(c"getSeconds".as_ptr(), 0, Some(get_date_field), (0x51) as i32),
    JS_CFUNC_MAGIC_DEF(c"getUTCSeconds".as_ptr(), 0, Some(get_date_field), (0x50) as i32),
    JS_CFUNC_MAGIC_DEF(c"getMilliseconds".as_ptr(), 0, Some(get_date_field), (0x61) as i32),
    JS_CFUNC_MAGIC_DEF(c"getUTCMilliseconds".as_ptr(), 0, Some(get_date_field), (0x60) as i32),
    JS_CFUNC_MAGIC_DEF(c"getDay".as_ptr(), 0, Some(get_date_field), (0x71) as i32),
    JS_CFUNC_MAGIC_DEF(c"getUTCDay".as_ptr(), 0, Some(get_date_field), (0x70) as i32),
    JS_CFUNC_DEF(c"setTime".as_ptr(), 1, Some(js_date_setTime)),
    JS_CFUNC_MAGIC_DEF(c"setMilliseconds".as_ptr(), 1, Some(set_date_field), (0x671) as i32),
    JS_CFUNC_MAGIC_DEF(c"setUTCMilliseconds".as_ptr(), 1, Some(set_date_field), (0x670) as i32),
    JS_CFUNC_MAGIC_DEF(c"setSeconds".as_ptr(), 2, Some(set_date_field), (0x571) as i32),
    JS_CFUNC_MAGIC_DEF(c"setUTCSeconds".as_ptr(), 2, Some(set_date_field), (0x570) as i32),
    JS_CFUNC_MAGIC_DEF(c"setMinutes".as_ptr(), 3, Some(set_date_field), (0x471) as i32),
    JS_CFUNC_MAGIC_DEF(c"setUTCMinutes".as_ptr(), 3, Some(set_date_field), (0x470) as i32),
    JS_CFUNC_MAGIC_DEF(c"setHours".as_ptr(), 4, Some(set_date_field), (0x371) as i32),
    JS_CFUNC_MAGIC_DEF(c"setUTCHours".as_ptr(), 4, Some(set_date_field), (0x370) as i32),
    JS_CFUNC_MAGIC_DEF(c"setDate".as_ptr(), 1, Some(set_date_field), (0x231) as i32),
    JS_CFUNC_MAGIC_DEF(c"setUTCDate".as_ptr(), 1, Some(set_date_field), (0x230) as i32),
    JS_CFUNC_MAGIC_DEF(c"setMonth".as_ptr(), 2, Some(set_date_field), (0x131) as i32),
    JS_CFUNC_MAGIC_DEF(c"setUTCMonth".as_ptr(), 2, Some(set_date_field), (0x130) as i32),
    JS_CFUNC_DEF(c"setYear".as_ptr(), 1, Some(js_date_setYear)),
    JS_CFUNC_MAGIC_DEF(c"setFullYear".as_ptr(), 3, Some(set_date_field), (0x031) as i32),
    JS_CFUNC_MAGIC_DEF(c"setUTCFullYear".as_ptr(), 3, Some(set_date_field), (0x030) as i32),
    JS_CFUNC_DEF(c"toJSON".as_ptr(), 1, Some(js_date_toJSON)),
];
static mut js_bigint_funcs: [JSCFunctionListEntry; 2] = [
    JS_CFUNC_MAGIC_DEF(c"asUintN".as_ptr(), 2, Some(js_bigint_asUintN), (0) as i32),
    JS_CFUNC_MAGIC_DEF(c"asIntN".as_ptr(), 2, Some(js_bigint_asUintN), (1) as i32),
];
static mut js_bigint_proto_funcs: [JSCFunctionListEntry; 3] = [
    JS_CFUNC_DEF(c"toString".as_ptr(), 0, Some(js_bigint_toString)),
    JS_CFUNC_DEF(c"valueOf".as_ptr(), 0, Some(js_bigint_valueOf)),
    JS_PROP_STRING_DEF(c"[Symbol.toStringTag]".as_ptr(), c"BigInt".as_ptr(), JS_PROP_CONFIGURABLE),
];
