// Exact official quickjs.c String table order and descriptors. MIT.
static mut js_string_funcs: [JSCFunctionListEntry; 3] = [
    JS_CFUNC_DEF(c"fromCharCode".as_ptr(), 1, Some(js_string_fromCharCode)),
    JS_CFUNC_DEF(c"fromCodePoint".as_ptr(), 1, Some(js_string_fromCodePoint)),
    JS_CFUNC_DEF(c"raw".as_ptr(), 1, Some(js_string_raw)),
];
static mut js_string_proto_funcs: [JSCFunctionListEntry; 50] = [
    JS_PROP_INT32_DEF(c"length".as_ptr(), 0, JS_PROP_CONFIGURABLE),
    JS_CFUNC_MAGIC_DEF(c"at".as_ptr(), 1, Some(js_string_charAt), (1) as i32),
    JS_CFUNC_DEF(c"charCodeAt".as_ptr(), 1, Some(js_string_charCodeAt)),
    JS_CFUNC_MAGIC_DEF(c"charAt".as_ptr(), 1, Some(js_string_charAt), (0) as i32),
    JS_CFUNC_DEF(c"concat".as_ptr(), 1, Some(js_string_concat)),
    JS_CFUNC_DEF(c"codePointAt".as_ptr(), 1, Some(js_string_codePointAt)),
    JS_CFUNC_DEF(c"isWellFormed".as_ptr(), 0, Some(js_string_isWellFormed)),
    JS_CFUNC_DEF(c"toWellFormed".as_ptr(), 0, Some(js_string_toWellFormed)),
    JS_CFUNC_MAGIC_DEF(c"indexOf".as_ptr(), 1, Some(js_string_indexOf), (0) as i32),
    JS_CFUNC_MAGIC_DEF(c"lastIndexOf".as_ptr(), 1, Some(js_string_indexOf), (1) as i32),
    JS_CFUNC_MAGIC_DEF(c"includes".as_ptr(), 1, Some(js_string_includes), (0) as i32),
    JS_CFUNC_MAGIC_DEF(c"endsWith".as_ptr(), 1, Some(js_string_includes), (2) as i32),
    JS_CFUNC_MAGIC_DEF(c"startsWith".as_ptr(), 1, Some(js_string_includes), (1) as i32),
    JS_CFUNC_MAGIC_DEF(c"match".as_ptr(), 1, Some(js_string_match), (crate::quickjs_atom::JS_ATOM_Symbol_match) as i32),
    JS_CFUNC_MAGIC_DEF(c"matchAll".as_ptr(), 1, Some(js_string_match), (crate::quickjs_atom::JS_ATOM_Symbol_matchAll) as i32),
    JS_CFUNC_MAGIC_DEF(c"search".as_ptr(), 1, Some(js_string_match), (crate::quickjs_atom::JS_ATOM_Symbol_search) as i32),
    JS_CFUNC_DEF(c"split".as_ptr(), 2, Some(js_string_split)),
    JS_CFUNC_DEF(c"substring".as_ptr(), 2, Some(js_string_substring)),
    JS_CFUNC_DEF(c"substr".as_ptr(), 2, Some(js_string_substr)),
    JS_CFUNC_DEF(c"slice".as_ptr(), 2, Some(js_string_slice)),
    JS_CFUNC_DEF(c"repeat".as_ptr(), 1, Some(js_string_repeat)),
    JS_CFUNC_MAGIC_DEF(c"replace".as_ptr(), 2, Some(js_string_replace), (0) as i32),
    JS_CFUNC_MAGIC_DEF(c"replaceAll".as_ptr(), 2, Some(js_string_replace), (1) as i32),
    JS_CFUNC_MAGIC_DEF(c"padEnd".as_ptr(), 1, Some(js_string_pad), (1) as i32),
    JS_CFUNC_MAGIC_DEF(c"padStart".as_ptr(), 1, Some(js_string_pad), (0) as i32),
    JS_CFUNC_MAGIC_DEF(c"trim".as_ptr(), 0, Some(js_string_trim), (3) as i32),
    JS_CFUNC_MAGIC_DEF(c"trimEnd".as_ptr(), 0, Some(js_string_trim), (2) as i32),
    JS_ALIAS_DEF(c"trimRight".as_ptr(), c"trimEnd".as_ptr()),
    JS_CFUNC_MAGIC_DEF(c"trimStart".as_ptr(), 0, Some(js_string_trim), (1) as i32),
    JS_ALIAS_DEF(c"trimLeft".as_ptr(), c"trimStart".as_ptr()),
    JS_CFUNC_DEF(c"toString".as_ptr(), 0, Some(js_string_toString)),
    JS_CFUNC_DEF(c"valueOf".as_ptr(), 0, Some(js_string_toString)),
    JS_CFUNC_MAGIC_DEF(c"toLowerCase".as_ptr(), 0, Some(js_string_toLowerCase), (1) as i32),
    JS_CFUNC_MAGIC_DEF(c"toUpperCase".as_ptr(), 0, Some(js_string_toLowerCase), (0) as i32),
    JS_CFUNC_MAGIC_DEF(c"toLocaleLowerCase".as_ptr(), 0, Some(js_string_toLowerCase), (1) as i32),
    JS_CFUNC_MAGIC_DEF(c"toLocaleUpperCase".as_ptr(), 0, Some(js_string_toLowerCase), (0) as i32),
    JS_CFUNC_MAGIC_DEF(c"[Symbol.iterator]".as_ptr(), 0, Some(js_create_array_iterator), (JS_ITERATOR_KIND_VALUE | 4) as i32),
    JS_CFUNC_MAGIC_DEF(c"anchor".as_ptr(), 1, Some(js_string_CreateHTML), (magic_string_anchor) as i32),
    JS_CFUNC_MAGIC_DEF(c"big".as_ptr(), 0, Some(js_string_CreateHTML), (magic_string_big) as i32),
    JS_CFUNC_MAGIC_DEF(c"blink".as_ptr(), 0, Some(js_string_CreateHTML), (magic_string_blink) as i32),
    JS_CFUNC_MAGIC_DEF(c"bold".as_ptr(), 0, Some(js_string_CreateHTML), (magic_string_bold) as i32),
    JS_CFUNC_MAGIC_DEF(c"fixed".as_ptr(), 0, Some(js_string_CreateHTML), (magic_string_fixed) as i32),
    JS_CFUNC_MAGIC_DEF(c"fontcolor".as_ptr(), 1, Some(js_string_CreateHTML), (magic_string_fontcolor) as i32),
    JS_CFUNC_MAGIC_DEF(c"fontsize".as_ptr(), 1, Some(js_string_CreateHTML), (magic_string_fontsize) as i32),
    JS_CFUNC_MAGIC_DEF(c"italics".as_ptr(), 0, Some(js_string_CreateHTML), (magic_string_italics) as i32),
    JS_CFUNC_MAGIC_DEF(c"link".as_ptr(), 1, Some(js_string_CreateHTML), (magic_string_link) as i32),
    JS_CFUNC_MAGIC_DEF(c"small".as_ptr(), 0, Some(js_string_CreateHTML), (magic_string_small) as i32),
    JS_CFUNC_MAGIC_DEF(c"strike".as_ptr(), 0, Some(js_string_CreateHTML), (magic_string_strike) as i32),
    JS_CFUNC_MAGIC_DEF(c"sub".as_ptr(), 0, Some(js_string_CreateHTML), (magic_string_sub) as i32),
    JS_CFUNC_MAGIC_DEF(c"sup".as_ptr(), 0, Some(js_string_CreateHTML), (magic_string_sup) as i32),
];
static mut js_string_iterator_proto_funcs: [JSCFunctionListEntry; 2] = [
    JS_ITERATOR_NEXT_DEF(c"next".as_ptr(), 0, Some(js_string_iterator_next), 0),
    JS_PROP_STRING_DEF(c"[Symbol.toStringTag]".as_ptr(), c"String Iterator".as_ptr(), JS_PROP_CONFIGURABLE),
];
static mut js_string_proto_normalize: [JSCFunctionListEntry; 2] = [
    JS_CFUNC_DEF(c"normalize".as_ptr(), 0, Some(js_string_normalize)),
    JS_CFUNC_DEF(c"localeCompare".as_ptr(), 1, Some(js_string_localeCompare)),
];
