//! Rust replay adapter combining several official kernel responsibilities.
//! Function-level algorithm correspondences are recorded in translation_map.json.

// CPU implementation moved from renderer/glyphs/glyph_position.rs.

//! Device-space glyph positioning from the Skia CPU mask replay contract.
use crate::raster::{Point, Transform};

// SkGlyph.cpp: SkGlyphPositionRoundingSpec::HalfAxisSampleFreq and
// IgnorePositionMask; SkGlyph.h: SkPackedGlyphID::kSubPixelPosLen (2).
// Axis-aligned horizontal text uses quarter pixels along its baseline and
// whole pixels perpendicular to it. Quantization happens after the CTM.
pub(crate) fn position_transform(transform: Transform, x: f32, y: f32) -> Transform {
    let mut origin = Point::from_xy(x, y);
    transform.map_point(&mut origin);
    let (x_steps, y_steps) = if transform.ky == 0.0 {
        (4.0, 1.0)
    } else if transform.sx == 0.0 {
        (1.0, 4.0)
    } else {
        (4.0, 4.0)
    };
    Transform {
        tx: quantize(origin.x, x_steps),
        ty: quantize(origin.y, y_steps),
        ..transform
    }
}

// SkScalerContext::MakeRecAndEffects / sk_relax quantizes the glyph-mask
// matrix to 1/1024. The actual baseline is still mapped through the full CTM.
pub(crate) fn mask_transform(mut transform: Transform) -> Transform {
    let relax = |v: f32| (v * 1024.0 + 0.5).floor() / 1024.0;
    transform.sx = relax(transform.sx);
    transform.sy = relax(transform.sy);
    transform.kx = relax(transform.kx);
    transform.ky = relax(transform.ky);
    transform
}

pub(crate) fn mask_position_transform(transform: Transform, x: f32, y: f32) -> Transform {
    let mut origin = Point::from_xy(x, y);
    transform.map_point(&mut origin);
    let mut mask = mask_transform(transform);
    mask.tx = origin.x;
    mask.ty = origin.y;
    position_transform(mask, 0.0, 0.0)
}

fn quantize(value: f32, steps: f32) -> f32 {
    // SkGlyphRunPainter first adds half the sample period, then separates
    // floor(position) and its two-bit fractional glyph-cache key.
    ((value + 0.5 / steps) * steps).floor() / steps
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn device_positions_match_skia_cpu_mask_oracle() {
        // Generated by tests/oracles/glyph_position.cc, including negative
        // positions, ties, translation, scale, rotation and skew.
        let oracle = include_bytes!("../tests/fixtures/glyph_position.f32");
        let matrices = [
            [1.0, 0.0, 0.0, 1.0, 0.0, 0.0],
            [1.0, 0.0, 0.0, 1.0, 10.125, -7.625],
            [2.0, 0.0, 0.0, 0.75, 4.0, 5.0],
            [0.0, 1.0, -1.0, 0.0, 3.0, 5.0],
            [1.0, 0.0, 0.25, 1.0, 0.0, 0.0],
            [1.0, 0.25, 0.125, 1.0, 0.0, 0.0],
        ];
        for (m_index, m) in matrices.into_iter().enumerate() {
            for i in 0..1024 {
                let x = (i as i32 - 512) as f32 / 64.0;
                let y = ((i * 37) % 1024) as f32 / 64.0 - 8.0;
                let actual = position_transform(
                    Transform::from_row(m[0], m[1], m[2], m[3], m[4], m[5]),
                    x,
                    y,
                );
                let offset = (m_index * 1024 + i) * 8;
                let expected_x = f32::from_le_bytes(oracle[offset..offset + 4].try_into().unwrap());
                let expected_y =
                    f32::from_le_bytes(oracle[offset + 4..offset + 8].try_into().unwrap());
                assert_eq!(
                    (actual.tx, actual.ty),
                    (expected_x, expected_y),
                    "matrix={m_index} sample={i}"
                );
                assert_eq!(
                    (actual.sx, actual.ky, actual.kx, actual.sy),
                    (m[0], m[1], m[2], m[3])
                );
            }
        }
    }
}
